/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of AutoChips Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AutoChips SOFTWARE") RECEIVED
 *     FROM AutoChips AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. AutoChips EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES AutoChips PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE AutoChips SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AutoChips SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY AutoChips SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND AutoChips'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE AutoChips SOFTWARE RELEASED HEREUNDER WILL BE, AT AutoChips'S OPTION,
 *     TO REVISE OR REPLACE THE AutoChips SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO AutoChips FOR SUCH AutoChips SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/

/******************************************************************************
*[File]                     apcm_txrx_reg.h
*[Author]                   tongfa.luo@autochips.com
*[Description]
*
******************************************************************************/
#ifndef _APCM_TXRX_REG_H_
#define _APCM_TXRX_REG_H_

#include "apcm_txrx.h"


#define REG_TXRX_SET_MODE(mode)	\
	AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_MODE_SEL, BIT_NUM_MODE_SEL, mode);


#define REG_TXRX_SET_HW_MODE(mode)	\
	AUDREG_BITS_W(REGENV_RGBK2_CFG5, BIT_STR_PCM_LOOP_MODE,BIT_NUM_PCM_LOOP_MODE, mode);


#define REG_TXRX_SET_SYNC_CFG(mode, cycle, length)	\
	do {	\
		AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_SYNC_MODE_SEL, BIT_NUM_SYNC_MODE_SEL, mode);	\
		AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_SYNC_CYCLE, BIT_NUM_SYNC_CYCLE, cycle);		\
		AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_SYNC_LENGTH, BIT_NUM_SYNC_LENGTH, length);	\
	} while (0);


#define REG_TXRX_SET_DATA_FMT(data_order, bit_num, bit_mode)	\
	do {	\
		AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_BIT_DATA_ORDER, BIT_NUM_BIT_DATA_ORDER, data_order);	\
		AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_BIT_NUM_SEL, BIT_NUM_BIT_NUM_SEL, bit_num);		\
		AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_PCM_16BIT, BIT_NUM_PCM_16BIT, bit_mode);			\
	} while (0);


#define REG_TXRX_SET_TX_ADR(sadr, eadr, blk)	\
	do {	\
		AUDREG_BITS_W(REGENV_PCMTX_DRAM_SADR, BIT_STR_PCMTX_DRAM_SADR, BIT_NUM_PCMTX_DRAM_SADR, sadr);		\
		AUDREG_BITS_W(REGENV_PCMTX_DRAM_EADR, BIT_STR_PCMTX_DRAM_EADR, BIT_NUM_PCMTX_DRAM_EADR, eadr);		\
		AUDREG_BITS_W(REGENV_BT_PCM_BLK_CFG, BIT_STR_PCM_TX_DRAM_BLK, BIT_NUM_PCM_TX_DRAM_BLK, blk);		\
	} while (0);


#define REG_TXRX_SET_TX_NSADR(nasdr)	\
	AUDREG_BITS_W(REGENV_PCMTX_DRAM_NSADR, BIT_STR_PCM_TX_DRAM_NSADR, BIT_NUM_PCM_TX_DRAM_NSADR, nasdr)


#define REG_TXRX_SET_TX_INT_CFG(int_samples, burst_samples)	\
	do {	\
		AUDREG_BITS_W(REGENV_PCMTX_INTR, BIT_STR_TX_SAMPLE_NUM, BIT_NUM_TX_SAMPLE_NUM, int_samples);		\
		AUDREG_BITS_W(REGENV_PCMTX_INTR, BIT_STR_TX_INTR_RENUM, BIT_NUM_TX_INTR_RENUM, burst_samples);	\
	} while (0);


#define REG_TXRX_SET_RX_ADR(sadr, eadr, blk)	\
	do {	\
		AUDREG_BITS_W(REGENV_PCMRX_DRAM_SADR, BIT_STR_PCMRX_DRAM_SADR, BIT_NUM_PCMRX_DRAM_SADR, sadr);		\
		AUDREG_BITS_W(REGENV_PCMRX_DRAM_EADR, BIT_STR_PCMRX_DRAM_EADR, BIT_NUM_PCMRX_DRAM_EADR, eadr);		\
		AUDREG_BITS_W(REGENV_BT_PCM_BLK_CFG, BIT_STR_PCM_RX_DRAM_BLK, BIT_NUM_PCM_RX_DRAM_BLK, blk);		\
	} while (0);


#define REG_TXRX_GET_RX_WP				AUDREG_READ(REGENV_PCMRX_WRADR)


#define REG_TXRX_SET_BANK_ADR(bank_adr)		\
	AUDREG_BITS_W(REGENV_RGBK2_CFG4, BIT_STR_PCM_DRAM_BANK, BIT_NUM_PCM_DRAM_BANK, bank_adr);


#define REG_TXRX_ENABLE_TX(enable)		\
	AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_TX_EN, BIT_NUM_TX_EN, enable);


#define REG_TXRX_ENABLE_RX(enable)		\
	AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_RX_EN, BIT_NUM_RX_EN, enable);


#define REG_TXRX_ENABLE(enable)		\
	AUDREG_BITS_W(REGENV_PCM_CTRL, BIT_STR_PCM_EN, BIT_NUM_PCM_EN, enable);


#endif //_APCM_TXRX_REG_H_

