/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of AutoChips Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AutoChips SOFTWARE") RECEIVED
 *     FROM AutoChips AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. AutoChips EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES AutoChips PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE AutoChips SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AutoChips SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY AutoChips SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND AutoChips'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE AutoChips SOFTWARE RELEASED HEREUNDER WILL BE, AT AutoChips'S OPTION,
 *     TO REVISE OR REPLACE THE AutoChips SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO AutoChips FOR SUCH AutoChips SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/

/******************************************************************************
*[File]                     apcm_mic_reg.h
*[Author]                   tongfa.luo@autochips.com
*[Description]
*
******************************************************************************/
#ifndef _APCM_MIC_REG_H_
#define _APCM_MIC_REG_H_

#include "apcm_mic.h"

#define REG_MIC_SET_CLK_SRC(clk_src)        \
	do { \
		AUDREG_BITS_W(REGENV_AFE_TOP_CFG0, BIT_STR_MIC_USE_AO2_GIM, BIT_NUM_MIC_USE_AO2_GIM, \
			((MIC_CLK_AOUT2 == clk_src) ? true : false));\
		AUDREG_BITS_W(REGENV_AIN_CFG, BIT_STR_MPCLK_IND, BIT_NUM_MPCLK_IND, \
			((MIC_CLK_MPH == clk_src) ? true : false));\
		AUDREG_BITS_W(REGENV_AENV_BAK, BIT_STR_MPHONE_SLAVE, BIT_NUM_MPHONE_SLAVE, false);\
		AUDREG_BITS_W(REGENV_BYPS_VLUM_CFG1, BIT_STR_MPH_WE_SEL, BIT_NUM_MPH_WE_SEL, 1); \
	} while(0);


#define REG_MIC_SET_DIVIDER(mclk_type, cycle) \
	do {    \
		AUDREG_BITS_W(REGENV_MISC_CTRL, BIT_STR_MPHONE_BCK_DIV, BIT_NUM_MPHONE_BCK_DIV, \
			(IoClk_GetMclkToFsRatio(mclk_type) / (32 * 4)));\
		AUDREG_BITS_W(REGENV_MISC_CTRL, BIT_STR_MPHONE_LRCK_DIV_SEL, BIT_NUM_MPHONE_LRCK_DIV_SEL, cycle);\
	} while(0);


#define REG_MIC_SET_INVERT(bck_invert, lrck_invert) \
	do {    \
		AUDREG_BITS_W(REGENV_AIN_CFG, BIT_STR_MPBCK_INV, BIT_NUM_MPBCK_INV, bck_invert); \
		AUDREG_BITS_W(REGENV_AIN_CFG, BIT_STR_M_INV_LRCK, BIT_NUM_M_INV_LRCK, lrck_invert); \
	} while(0);


#define REG_MIC_SET_DATA_FMT(src_bit_num, out_bit_num, fmt)   \
	do { \
		AUDREG_BITS_W(REGENV_AIN_CFG, BIT_STR_MP_BNUM, BIT_NUM_MP_BNUM, \
			(src_bit_num - 1)); \
		AUDREG_BITS_W(REGENV_AFE_TOP_CFG0, BIT_STR_MPH_16BIT_MODE, BIT_NUM_MPH_16BIT_MODE, \
			((16 == out_bit_num) ? true : false));\
		AUDREG_BITS_W(REGENV_AIN_CFG, BIT_STR_M_LEFT_A, BIT_NUM_M_LEFT_A, (fmt & 0x1));    \
		AUDREG_BITS_W(REGENV_AIN_CFG, BIT_STR_M_DAT_D, BIT_NUM_M_DAT_D,((fmt & 0x2) >> 1)); \
	} while(0);


#define REG_MIC_SET_BUF_INFO(sadr, len) \
	do {    \
		AUDREG_BITS_W(REGENV_RGBK2_CFG2, BIT_STR_MPBUF1_SADR, BIT_NUM_MPBUF1_SADR,   ( (sadr & 0xff) >> 2)); \
		AUDREG_BITS_W(REGENV_RGBK2_CFG2, BIT_STR_MPBUF2_SADR, BIT_NUM_MPBUF2_SADR,   (((sadr & 0xff) >> 2) + (len >> 2))); \
		AUDREG_BITS_W(REGENV_RGBK2_CFG3, BIT_STR_MPBUF3_SADR, BIT_NUM_MPBUF3_SADR,   (((sadr & 0xff) >> 2) + (len >> 1))); \
		AUDREG_BITS_W(REGENV_RGBK2_CFG5, BIT_STR_ARM_MIC_BLK6, BIT_NUM_ARM_MIC_BLK6, ( (sadr & 0x0fff00) >> 8));\
		AUDREG_BITS_W(REGENV_RGBK2_CFG4, BIT_STR_MPHONE_BANK, BIT_NUM_MPHONE_BANK,   ( (sadr >> 20) & 0xfff)); \
	} while(0);


#define REG_MIC_SET_SRC(src)            \
	do {	\
		AUDREG_BITS_W(REGENV_BYPS_VLUM_CFG1, BIT_STR_MPH_AFE_MODE, BIT_NUM_MPH_AFE_MODE, \
			((EXT_MICIN == src) ? LIN_EXT_ADC : LIN_INT_ADC)); \
	} while (0);


#define REG_MIC_SET_AFE_DATA(adc_id)    \
	AUDREG_BITS_W(REGENV_AFE_TOP_CFG0, BIT_STR_MIC_AFEX_SEL, BIT_NUM_MIC_AFEX_SEL, (AUD_ADC1 == adc_id) ? 0 : 1)


#define REG_MIC_SET_ARM_CTRL(enable)    \
	AUDREG_BITS_W(REGENV_RGBK2_CFG1, BIT_STR_MIC_IN_ARM_CTRL_EN, BIT_NUM_MIC_IN_ARM_CTRL_EN, enable)


#define REG_MIC_ENABLE(enable)  \
	AUDREG_BITS_W(REGENV_RGBK2_CFG3, BIT_STR_MPHONE_BUF_EN, BIT_NUM_MPHONE_BUF_EN, enable)


#define REG_MIC_GET_SADR()    \
	AUDREG_BITS_R(REGENV_RGBK2_CFG2, BIT_STR_MPBUF1_SADR, BIT_NUM_MPBUF1_SADR)


#define REG_MIC_GET_WP()  \
	AUDREG_READ(REGENV_MPHONE_WADR)

#endif  //_APCM_MIC_REG_H_

