#include <stdint.h>
#include <string.h>
#include "addr2func.h"

/*
 * Bare-metal parser for table.bin generated by gen_dwarf_table.py
 *
 * Binary layout (little-endian):
 * - Header:
 *     uint32 MAGIC        = 0x46554E43 ('FUNC')
 *     uint16 VERSION      = 1
 *     uint16 entry_count
 *     uint32 strings_size
 * - Entries (entry_count times):
 *     uint32 name_off     // offset into strings blob
 *     uint32 start        // inclusive
 *     uint32 end          // exclusive
 *     int8   flags        // bit0: inline
 * - Strings blob: strings_size bytes consisting of NUL-terminated utf-8 names
 *
 * This implementation does not allocate or read files. It uses a linker-
 * provided base address for the table and builds an in-place view.
 */

#define FT_MAGIC      0x46554E43u /* 'FUNC' */
#define FT_VERSION    1u
#define FT_FLAG_INLINE  (1u << 0)

#pragma pack(push, 1)
struct FtHeaderRaw {
    uint32_t magic;
    uint16_t version;
    uint16_t entry_count;
    uint32_t strings_size;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct FtEntryRaw {
    uint32_t name_off;
    uint32_t start;
    uint32_t end;
    int8_t   flags;
};
#pragma pack(pop)

static int parse_header(const unsigned char* buf, size_t size, struct FtHeaderRaw* hdr) {
    if (size < sizeof(*hdr)) return -1;
    memcpy(hdr, buf, sizeof(*hdr));
    if (hdr->magic != FT_MAGIC) return -2;
    if (hdr->version != FT_VERSION) return -3;
    return 0;
}

extern const unsigned char _start[];

/*
 * Linker-provided base address of table.bin.
 * Define FT_BIN_BASE to override the symbol name if needed.
 */
#ifndef FT_BIN_BASE
extern const unsigned char __func_table_start[]; /* provided by LDS */
#define FT_BIN_BASE (__func_table_start)
#endif
#ifndef FT_BIN_DEST
extern const unsigned char __heap_end[]; /* provided by LDS */
#define FT_BIN_DEST (__heap_end)
#endif

#define FT_INVALID_POINT  (void *)0xFFFFFFFF
#define FT_INVALID_U16    (uint16_t)0xFFFF
#define FT_INVALID_U32    (uint32_t)0xFFFFFFFF

/* Internal module state (in-place view)
 *
 * Note: force ft-variables in 'data' section to prevent
 *       being cleared during 'bss-clear'
 */
static const struct FtHeaderRaw* ft_hdr = FT_INVALID_POINT;
static const struct FtEntryRaw*  ft_entries = FT_INVALID_POINT;
static const char*               ft_strings = FT_INVALID_POINT;
static uint16_t                  ft_entry_count = FT_INVALID_U16;
static uint32_t                  ft_strings_size = FT_INVALID_U32;
static uint32_t                  ft_total_size = FT_INVALID_U32;

/*
 * func_table_init - initialize in-place view from linker-provided base
 *
 * Return: 0 on success, negative error code on failure.
 */
int func_table_init(void) {
    const unsigned char* base = FT_BIN_BASE;
    struct FtHeaderRaw hdr;
    unsigned int size;

    /* We don't know the full blob size here; rely on header bounds for sanity checks. */
    if (parse_header(base, sizeof(hdr), &hdr) != 0) {
        return -1;
    }

    ft_total_size = sizeof(struct FtHeaderRaw) + hdr.entry_count * sizeof(struct FtEntryRaw) + hdr.strings_size;

    /* Copy function table to destination address space */
    if (FT_BIN_DEST + ft_total_size > _start + CFG_ARM2_RESERVED_SIZE) {
        return -2;
    }
    memcpy(FT_BIN_DEST, FT_BIN_BASE, ft_total_size);

    ft_hdr = (const struct FtHeaderRaw*)FT_BIN_DEST;
    ft_entry_count = hdr.entry_count;
    ft_strings_size = hdr.strings_size;
    ft_entries = (const struct FtEntryRaw*)(FT_BIN_DEST + sizeof(struct FtHeaderRaw));
    ft_strings = (const char*)(FT_BIN_DEST + sizeof(struct FtHeaderRaw) + (size_t)hdr.entry_count * sizeof(struct FtEntryRaw));
    return 0;
}

/*
 * func_table_deinit - reset in-place view to an uninitialized state
 */
void func_table_deinit(void) {
    ft_hdr = FT_INVALID_POINT;
    ft_entries = FT_INVALID_POINT;
    ft_strings = FT_INVALID_POINT;
    ft_entry_count = FT_INVALID_U16;
    ft_strings_size = FT_INVALID_U32;
}

/*
 * lookup_name - fetch a NUL-terminated string from the strings blob
 * @name_off: offset into the strings blob
 *
 * Return: pointer to string on success, NULL on failure.
 */
static const char* lookup_name(uint32_t name_off) {
    if (ft_strings == NULL || name_off >= ft_strings_size)
        return NULL;
    const char* s = ft_strings + name_off;
    size_t max = ft_strings_size - name_off;
    const void* nul = memchr(s, '\0', max);
    return nul ? s : NULL;
}

/*
 * addr2func - map an address to a preferred function name
 * @addr: instruction address to resolve
 *
 * Preference: non-inline entry if present; otherwise first inline name.
 *
 * Return: pointer to string on success, or NULL if not found.
 */
const char* addr2func(uint32_t addr) {
    const char* first_inline = NULL;
    if (ft_entries == FT_INVALID_POINT)
        return NULL;
    for (uint16_t i = 0; i < ft_entry_count; ++i) {
        const struct FtEntryRaw* e = &ft_entries[i];
        if (addr < e->start || addr >= e->end)
            continue;
        const char* name = lookup_name(e->name_off);
        if (!name)
            continue;
        if (((uint8_t)e->flags & FT_FLAG_INLINE) == 0) {
            return name; /* prefer non-inline */
        } else if (!first_inline) {
            first_inline = name;
        }
    }
    return first_inline;
}

/*
 * addr2func_chain - collect the full inline chain at an address
 * @addr:  instruction address to resolve
 * @names: output array of pointers to function names
 * @flags: output array of flags for each name (may be NULL)
 * @max:   maximum number of frames to write
 *
 * Returns the number of frames written (<= max).
 */
size_t addr2func_chain(uint32_t addr, const char** names, uint8_t* flags, size_t max) {
    size_t n = 0;
    if (ft_entries == FT_INVALID_POINT)
        return 0;
    for (uint16_t i = 0; i < ft_entry_count; ++i) {
        const struct FtEntryRaw* e = &ft_entries[i];
        if (addr < e->start || addr >= e->end)
            continue;
        const char* name = lookup_name(e->name_off);
        if (!name)
            continue;
        if (n < max) {
            names[n] = name;
            if (flags)
                flags[n] = (uint8_t)e->flags;
            n++;
        } else {
            break;
        }
    }
    return n;
}

/*
 * ft_get_total_size - get function table information size.
 *
 * Return: 0 on failure or correct size on pass.
 */
unsigned int ft_get_total_size(void) {
    if (ft_total_size == FT_INVALID_U32)
        return 0;
    return ft_total_size;
}
/* No test harness for bare-metal build; use func_table_init() at startup
   and then call addr2func()/addr2func_chain(). */
