obj-$(CONFIG_ATC_THERMAL_AC823X) += thermal.o thermal_ac823x.o

ccflags-y := -Idrivers/misc/atc/libosal/ac823x/inc -Idrivers/misc/atc/inc -Idrivers/misc/atc/private_inc 
ccflags-y += -Idrivers/misc/atc/include
