package com.hcn.autoeq.util;

public interface ConstantCscAsp {
    //总频段数目
    int BAND_TOTAL = 36;

    //增益值的范围
    int DEFINE_SEEKBAR_MAX = 15;
    int DEFINE_SEEKBAR_MIN = -15;


    // q值低音默认值
    int DEF_CSC_ASP_QVALUE = 1; // q值默认值
    // q值高音默认值
    int DEF_CSC_ASP_HIGH_QVALUE = 1;

    //csc_asp响度, loudness强度设置，0-10，0级为loudness关闭，1-10效果模式  default:0
    int CSC_ASP_DEFAULT_LOUDNESS = 0;
    int CSC_ASP_LOW_LOUDNESS = 3;
    int CSC_ASP_MIDDLE_LOUDNESS = 6;
    int CSC_ASP_HIGH_LOUDNESS = 10;


    /**
     * CSC_DSP模式数量
     */
    int EXT_CSC_ASP_REVERB_NEWS = 0;
    int EXT_CSC_ASP_REVERB_JAZZ = 1;
    int EXT_CSC_ASP_REVERB_CITY = 2;
    int EXT_CSC_ASP_REVERB_POP = 3;
    int EXT_CSC_ASP_REVERB_CLASSIZ = 4;
    int EXT_CSC_ASP_REVERB_MOVIE = 5;
    int EXT_DSP_REVERB_ROCK = 6;
    int EXT_CSC_ASP_REVERB_SIZE = 7;
    int EXT_CSC_ASP_REVERB_USER0 = 8;
    int EXT_CSC_ASP_REVERB_USER1 = 9;
    int DEF_CSC_ASP_EQ_REVERB = EXT_CSC_ASP_REVERB_NEWS;

    float DEF_CSC_ASP_EQ_36_BANDS_VALUES[][][] = new float[][][]{
            {
                    //mNewsEqBandsValues
                    {0, -2, 0, 2, 0, 2, 4, 6, 8, 6, 4, 0,
                            6, 8, 6, 6, 4, 6, 2, 0, 0, 0, 2, 0,
                            0, 0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0},
                    {DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE,
                            DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE,
                            DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE}
            },
            {
                    //mJazzEqBandsValues
                    {0, 4, 6, 2, 2, 0, -4, -2, -4, -4, -2, 0,
                            -4, -2, -4, -4, -8, -10, -6, 0, 0, -6, -4, -6,
                            0, -4, -6, 0, 2, 0, 0, 2, 2, 2, 0, 0},
                    {DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE}
            },
            {
                    //mCityEqBandsValues
                    {0, -4, -4, -2, 0, 2, 4, 4, 2, 4, 6, 0,
                            4, 6, 6, 8, 6, 4, 2, 2, 2, 4, 6, 2,
                            0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0},
                    {DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE}
            },
            {
                    //mPopEqBandsValues
                    {0, -2, 0, 2, 4, 6, 8, 6, 8, 8, 8, 0,
                            6, 6, 6, 4, 0, -4, -4, -2, -2, -4, -2, -4,
                            0, -2, -4, -2, 0, 0, -2, -2, 0, 0, 0, 0},
                    {DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE}
            },
            {
                    //mClassicEqBandsValues
                    {0, 0, 0, -2, -2, 0, 0, -2, -2, -2, 0, 0,
                            0, 0, 0, 0, 0, -10, -8, -8, -10, -12, -12, -8,
                            0, -6, -6, -8, -8, -8, -8, -10, -10, -10, -10, 0},
                    {DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE}
            },
            {
                    //mMovieEqBandsValues
                    {0, 10, 6, 8, 10, 8, 6, 4, 6, 4, 6, 0,
                            4, 0, 2, -6, -4, -4, 0, 0, -4, -4, -4, -2,
                            0, -4, 0, 2, 0, 2, 0, 2, 0, 2, 2, 0},
                    {DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE}
            },
            {
                    //mRockEqBandsValues
                    {0, 4, 2, 4, 0, 2, -8, -6, -8, -4, -8, 0,
                            -4, -6, -4, 0, 4, 6, 4, 2, 8, 8, 6, 4,
                            0, 2, 8, 6, 4, 4, 6, 6, 4, 8, 4, 0},
                    {DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE
                            , DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE, DEF_CSC_ASP_QVALUE}
            }
    };
}
