#  /etc/syslog.conf Configuration file for busybox's syslogd utility
#
# #######Log Level Define {
# emerg, alert, crit, err, warning, notice, info, debug 
# #######Log Level Define }

# Indicates info level messages and higher ones go to the console
*.debug                /dev/console

# Indicates debug level messages and higher ones  go to the file
*.debug                /data/atclog/syslog.log

# Indicates all kernel log store in syslog.log.
# kern.debug             /data/atclog/syslog.log
