/*************************************************************************************
 *LEGAL DISCLAIMER
 *
 * (Header of AutoChips Software/Firmware Release or Documentation)
 *
 * BY OPENING OR USING THIS FILE, USER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND
 * AGREES THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AUTOCHIPS SOFTWARE")
 * ARE PROVIDED TO USER ON AN "AS-IS" BASIS ONLY. AUTOCHIPS EXPRESSLY DISCLAIMS
 * ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES AUTOCHIPS PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED
 * IN, OR SUPPLIED WITH THE AUTOCHIPS SOFTWARE, AND USER AGREES TO LOOK ONLY TO
 * SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AUTOCHIPS SHALL
 * ALSO NOT BE RESPONSIBLE FOR ANY AUTOCHIPS SOFTWARE RELEASES MADE TO USER'S
 * SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 * USER HEREBY ACKNOWLEDGES THE CONFIDENTIALITY OF AUTOCHIPS SOFTWARE AND AGREES
 * NOT TO DISCLOSE OR PERMIT DISCLOSURE OF ANY AUTOCHIPS SOFTWARE TO ANY THIRD
 * PARTY OR TO ANY OTHER PERSON, EXCEPT TO DIRECTORS, OFFICERS, EMPLOYEES OF
 * USER WHO ARE REQUIRED TO HAVE THE INFORMATION TO CARRY OUT THE PURPOSE OF
 * OPENING OR USING THIS FILE.
*************************************************************************************/


#ifndef DIGITAL_HAL_H_
#define DIGITAL_HAL_H_


#include <linux/module.h>
#include <linux/init.h>
#include <linux/types.h>


typedef enum {
	DIG_IN_TYPE_601_P_480,
	DIG_IN_TYPE_601_P_576,
	DIG_IN_TYPE_601_I_480,
	DIG_IN_TYPE_601_I_576,
	DIG_IN_TYPE_656_P_480,
	DIG_IN_TYPE_656_P_576,
	DIG_IN_TYPE_656_I_480,
	DIG_IN_TYPE_656_I_576,
	DIG_IN_TYPE_656_p_800_480,
	DIG_IN_TYPE_MAX,
} E_DIG_IN_TYPE_T;


int digital_start_video(int mDigInFmt);
int digital_stop_video(void);
int digital_select_video(int index);

#endif
