#ifndef PCM_AUDCONF_H
#define PCM_AUDCONF_H

#include "windev.h"

#define  PCM_DEV "/dev/pcm_aud"

typedef struct pcm_aud_conf {
	uint32_t SPH_DELAY;
	uint32_t SPH_16K_DELAY;
	uint32_t SPH_DMNR_EN;
	uint32_t SPH_PLC_EN;
	uint32_t EXT_MIC_EN;
	uint32_t EXT_MIC_I2S_PIN;
	uint32_t EXT_MIC_FS;
	uint32_t EXT_MIC_SRC_BIT_NUM;
	uint32_t SPH_MIC_GAIN;
	uint32_t SPH_BT_GAIN;
	uint32_t MAX_SPH_GAIN;
	uint32_t DEVICE_SPH_GAIN;
	uint32_t DSP_MIX;
	uint32_t DAC_TYPE;
	uint32_t MAX_DEVICE_GAIN;
	uint32_t RANGE_DEVICE_GAIN;
	uint32_t MAX_STREAM_GAIN;
	uint32_t RANGE_STREAM_GAIN;
	uint32_t PB_DEBUG_ENABLE;
	uint32_t PB_AOUT_COUNT;
	char	 SPH_SAVE_PATH[100];
	uint32_t SPH_DEBUG_ENABLE;
	uint32_t SPH_DEBUG_INDEX;
	uint32_t SPH_DL_USE_FILE;
	uint32_t SPH_UL_USE_FILE;
	uint32_t ASRC_DEBUG_ENABLE;
	int32_t  AEC_NDC_PARAM[28];
	int32_t  AEC_NDC_PARAM_ERR_FLAG;
	int32_t  AEC_NDC_PARAM2[28];
	int32_t  AEC_NDC_PARAM2_ERR_FLAG;
	int32_t  ABF_CAL_DATA_PARAM[96];
	int32_t  AEC_COM_RX_PARAM[22];
	int32_t  AEC_COM_TX_PARAM[22];
	int32_t  AEC_NDC_PARAM_16k[28];
	int32_t  DMNR_PARAM_16K[76];
	int32_t  COMPEN_FILTER_PARAM_16k[270];
} PCMAUD_CONF;

typedef struct pcm_cust_conf {
	uint32_t u4SphDelay;
	uint32_t u4SphMicGain;
} PCM_CUST_CONF;

typedef struct pcm_dtmf_conf {
	uint32_t u4Param1;
	uint32_t u4Param2;
} PCM_DTMF_CONF;

typedef struct pcm_dtmf_threshold {
	double dlLowThreshold;
	double dlHighThreshold;
} PCM_DTMF_THRESHOLD;

typedef struct pcm_speech_conf {
	int32_t enhance_pars[28];
	int32_t error_flag;
	int32_t enhance_pars2[28];
	int32_t error_flag2;
	int16_t ABF_cal_data[96];
	int16_t aec_com_rx[22];
	int16_t aec_com_tx[22];
} PCM_SPEECH_CONF;

typedef struct pcm_speech_16k_conf {
	int32_t enhance_16k_pars[28];
        int32_t enhance_16k_comm_pars[12];
	int16_t dmnr_16k_pars[76];
} PCM_SPEECH_16K_CONF;

typedef struct pcm_volume {
	int32_t u4LVolume;
	int32_t u4RVolume;
	int32_t policy;
} PCM_VOLUME;


#define PCM_AUD_IOCTRL_ID_START			0x600

#define DEFINE_PCM_AUD_IOCTRL(ID)				\
	CTL_CODE(FILE_DEVICE_UNKNOWN, (ID), METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SET_SPH_DELAY							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x00)

#define GET_SPH_DELAY							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x01)

#define SET_SPH_DMNR_EN							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x02)

#define GET_SPH_DMNR_EN							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x04)

#define SET_SPH_MIC_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x05)

#define GET_SPH_MIC_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x06)

#define SET_MAX_SPH_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x07)

#define GET_MAX_SPH_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x08)

#define SET_DEVICE_SPH_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x09)

#define GET_DEVICE_SPH_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x0A)

#define SET_DSP_MIX_CH							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x0B)

#define GET_DSP_MIX_CH							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x0C)

#define SET_DAC_TYPE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x0D)

#define GET_DAC_TYPE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x0E)

#define SET_MAX_DEVICE_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x0F)

#define GET_MAX_DEVICE_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x10)

#define SET_DEVICE_GAIN_RANGE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x11)

#define GET_DEVICE_GAIN_RANGE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x12)

#define SET_MAX_STREAM_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x13)

#define GET_MAX_STREAM_GAIN						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x14)

#define SET_STREAM_GAIN_RANGE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x15)

#define GET_STREAM_GAIN_RANGE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x16)

#define SET_PB_DEBUG_ENABLE						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x17)

#define GET_PB_DEBUG_ENABLE						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x18)

#define SET_PB_AOUT_COUNT						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x19)

#define GET_PB_AOUT_COUNT						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x1A)

#define SET_SPEECH_SAVE_PATH					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x1B)

#define GET_SPEECH_SAVE_PATH					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x1C)

#define SET_SPEECH_DEBUG_ENABLE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x1D)

#define GET_SPEECH_DEBUG_ENABLE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x1E)

#define SET_SPEECH_DEBUG_INDEX					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x1F)

#define GET_SPEECH_DEBUG_INDEX					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x20)

#define SET_ASRC_DEBUG_ENABLE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x21)

#define GET_ASRC_DEBUG_ENABLE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x22)

#define SET_AEC_NDC_PARAM						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x23)

#define GET_AEC_NDC_PARAM						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x24)

#define SET_DMNR_PARAM							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x25)

#define GET_DMNR_PARAM							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x26)

#define BT_SCO_ENABLE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x27)

#define BT_SCO_DISABLE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x28)

#define BT_DUMP_REG								\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x29)

#define AOUT_DUMP_REG							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x30)

#define MIC_DUMP_REG							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x31)

#define ASRC_DUMP_REG							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x32)

#define SET_BT_SPH_GAIN							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x33)

#define GET_BT_SPH_GAIN							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x34)

#define SET_DL_USE_FILE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x40)

#define SET_UL_USE_FILE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x41)

#define SET_BT_SPH_PLC							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x42)

#define SET_BT_SPH_DUMP							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x43)

#define SET_MIC_MUTE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x44)

#define SET_PRIMARY_MIC							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x45)

#define SET_MIC_TYPE							\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x46)

#define SET_SPH_16K_DELAY						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x47)

#define GET_SPH_16K_DELAY						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x48)

#define SET_AEC_NDC_16K_PARAM					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x49)

#define GET_AEC_NDC_16K_PARAM					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x50)

#define SET_PCM_LOG								\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x60)

#define SET_PCM_DTMF_CTRL						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x70)

#define SET_PCM_DTMF_THRESHOLD					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x71)

#define SET_PCM_DTMF_NOISE_RATIO				\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x72)

#define SET_PCM_DTMF_VALID_TIME					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x73)

#define SET_PCM_DTMF_INVALID_TIME				\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x74)

#define SET_PCM_DTMF_NEW_SAMPLES				\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x75)

#define SET_PCM_DTMF_MAX_SCALE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x76)

#define GET_PCM_DTMF_PARAM						\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x7D)

#define SET_PCM_DTMF_LOG_RANGE					\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x7E)

#define SET_PCM_DTMF_TEST_USE_FILE				\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x7F)

#define SET_PCM_DTMF_INFO_SENDER_EN				\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x80)

#define SET_PCM_DTMF_INFO_SENDER_WRITE			\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x81)

#define SET_CAPTURE_NDC_ENABLE			\
	DEFINE_PCM_AUD_IOCTRL(PCM_AUD_IOCTRL_ID_START + 0x82)

int32_t pcm_audconf_set(void);
int32_t pcm_audconf_read(uint32_t context, void *pBuffer, uint32_t dwCount);
int32_t pcm_audconf_write(uint32_t context, void *pBuffer, uint32_t dwCount);
int32_t pcm_audconf_ioctl(uint32_t context, uint32_t code, void *pBuffer, uint32_t dwCount);

#endif
