#ccflags-y += -I$(srctree)/drivers/misc/atc/inc
#ccflags-y += -I$(srctree)/drivers/misc/atc/include/
#ccflags-y += -I$(srctree)/drivers/misc/atc/libosal/$(CONFIG_ATC_PLATFORM)/inc

obj-y := cpufreq-dt-ac823x.o
