obj-y				+= osal_mod.o
obj-y               += osal_compat.o
obj-y				+= osai/
obj-y				+= dbg_utility/

ccflags-y += -I$(srctree)/drivers/misc/atc/inc
ccflags-y += -I$(srctree)/drivers/misc/atc/private_inc
ccflags-y += -I$(srctree)/drivers/misc/atc/libosal/ac823x/inc