#ifndef _CHIP_TEST_H_
#define _CHIP_TEST_H_



typedef struct 
{
	char name[30];
 	void (* test_fn)(UINT32 cpu);
}TEST_ITEM_t;

# define __used			__attribute__((__used__))


#define DECLARE_TEST_ITEM(_name,_fn)     \
	 static TEST_ITEM_t TEST_ITEM_##_fn  \
	 __attribute__((__section__(".test_item_list")))  \
	 __used = { \
	    .name = _name,                                   \
	    .test_fn = _fn                                      \
};	    



#define SINGLE_RW_U8_TEST	(1 << 0)
#define SINGLE_RW_U16_TEST	(1 << 1)
#define SINGLE_RW_U32_TEST	(1 << 2)



extern void Chip_Test(UINT32 cpu);
extern void Dramk_Move(UINT32 cpu);


#define MAX_BUF_SIZE  0x80
#define DRAMA_BASE_ADDR 0xC0000000

#define FLASHA_BASE_ADDR 0xF8000000 
#define FLASHA_SIZE       0x0004000/* 16K */
#define FLASHA_GOLDEN_ADDR	0x0FF80000  // 255MB

#define CPU0_TEST_FLASHA_BASE_ADDR FLASHA_BASE_ADDR 
#define CPU0_TEST_FLASHA_SIZE       (FLASHA_SIZE >> 1)/* 16K */
#define CPU0_TEST_FLASHA_GOLDEN_ADDR	FLASHA_GOLDEN_ADDR  // 255MB
#define CPU1_TEST_FLASHA_BASE_ADDR (FLASHA_BASE_ADDR+CPU0_TEST_FLASHA_SIZE) 
#define CPU1_TEST_FLASHA_SIZE       (FLASHA_SIZE >> 1)/* 16K */
#define CPU1_TEST_FLASHA_GOLDEN_ADDR	(FLASHA_GOLDEN_ADDR+CPU0_TEST_FLASHA_SIZE)  // 255MB



#define FLASHBOOT_BASE_ADDR  0x0
#define FLASHBOOT_SIZE	 0x0004000/* 16K */
#define FLASHBOOT_GOLDEN_ADDR	0x0FF80000  // 255MB


#define SRAM_BASE_ADDR	0xF4000000
#define SRAM_SIZE		0x10000  //64K

#define CPU0_TEST_SRAM_BASE_ADDR  SRAM_BASE_ADDR
#define CPU0_TEST_SRAM_SIZE		  (SRAM_SIZE>>1)
#define CPU1_TEST_SRAM_BASE_ADDR  (SRAM_BASE_ADDR+CPU0_TEST_SRAM_SIZE)
#define CPU1_TEST_SRAM_SIZE		  (SRAM_SIZE - (SRAM_SIZE>>1))

#define ROM_BASE_ADDR	0xC0000000
#define ROM_SIZE		0x4000    //16k
#define ROM_GOLDEN_ADDR	0x0FF80000  // 255MB

#define CPU0_TEST_ROM_BASE_ADDR	  ROM_BASE_ADDR
#define CPU0_TEST_ROM_SIZE		(ROM_SIZE >> 1)    //16k
#define CPU0_TEST_ROM_GOLDEN_ADDR	ROM_GOLDEN_ADDR  // 255MB
#define CPU1_TEST_ROM_BASE_ADDR	  (ROM_BASE_ADDR+CPU0_TEST_ROM_SIZE)
#define CPU1_TEST_ROM_SIZE		(ROM_SIZE >> 1)    //16k
#define CPU1_TEST_ROM_GOLDEN_ADDR	(ROM_GOLDEN_ADDR+CPU0_TEST_ROM_SIZE)  // 255MB


#define DRAMB_BASE_ADDR 0x00000000
#define DRAM_SIZE       0x0ff00000 /* 255M */
//#define DRAM_SIZE       0x00001000 /* 255M */

#define CPU0_TEST_DRAMB_BASE_ADDR    DRAMB_BASE_ADDR
#define CPU0_TEST_DRAM_SIZE       	 (DRAM_SIZE >> 1)
#define CPU1_TEST_DRAMB_BASE_ADDR    (DRAMB_BASE_ADDR + CPU0_TEST_DRAM_SIZE)
#define CPU1_TEST_DRAM_SIZE       	 (DRAM_SIZE >> 1)


#define GPR_BASE_ADDR	0xf0008110
#define GPR_SIZE		0x18		

#define CPU0_TEST_GPR_BASE_ADDR		GPR_BASE_ADDR
#define CPU0_TEST_GPR_SIZE			(GPR_SIZE >> 1)
#define CPU1_TEST_GPR_BASE_ADDR		(GPR_BASE_ADDR + CPU0_TEST_GPR_SIZE)
#define CPU1_TEST_GPR_SIZE			(GPR_SIZE >> 1)


#define MCUSYS_BASE_ADDR   0xf0055000
#define MCUSYS_SIZE		0x1000
#define MCUSYS_GOLDEN_ADDR	0x0FF90000  // 255MB
#define MCUSYS_BITMASK_ADDR 0x0FFA0000

#define CPU0_TEST_MCUSYS_BASE_ADDR   MCUSYS_BASE_ADDR
#define CPU0_TEST_MCUSYS_SIZE		(MCUSYS_SIZE >> 1)
#define CPU0_TEST_MCUSYS_GOLDEN_ADDR	MCUSYS_GOLDEN_ADDR 
#define CPU0_TEST_MCUSYS_BITMASK_ADDR   MCUSYS_BITMASK_ADDR
#define CPU1_TEST_MCUSYS_BASE_ADDR   (MCUSYS_BASE_ADDR + CPU0_TEST_MCUSYS_SIZE)
#define CPU1_TEST_MCUSYS_SIZE		(MCUSYS_SIZE >> 1)
#define CPU1_TEST_MCUSYS_GOLDEN_ADDR	(MCUSYS_GOLDEN_ADDR+ CPU0_TEST_MCUSYS_SIZE) 
#define CPU1_TEST_MCUSYS_BITMASK_ADDR   (MCUSYS_BITMASK_ADDR+ CPU0_TEST_MCUSYS_SIZE)



extern UINT32 testBuf1[MAX_BUF_SIZE];
extern UINT32 testBuf2[MAX_BUF_SIZE];
extern UINT32 testBuf3[MAX_BUF_SIZE];
extern UINT32 testBuf4[MAX_BUF_SIZE];
extern UINT32 testBuf5[MAX_BUF_SIZE];
extern UINT32 testBuf6[MAX_BUF_SIZE];

extern UINT32 Stop_Test;

#endif

