/* Copyright Statement:
 *
 * This software/firmware and related documentation ("AutoChips Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to AutoChips Inc. and/or its licensors. Without
 * the prior written permission of AutoChips inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of AutoChips Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * AutoChips Inc. (C) 2016. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AUTOCHIPS SOFTWARE")
 * RECEIVED FROM AUTOCHIPS AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. AUTOCHIPS EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES AUTOCHIPS PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE AUTOCHIPS SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN AUTOCHIPS
 * SOFTWARE. AUTOCHIPS SHALL ALSO NOT BE RESPONSIBLE FOR ANY AUTOCHIPS SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AUTOCHIPS'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE AUTOCHIPS SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT AUTOCHIPS'S OPTION, TO REVISE OR REPLACE THE
 * AUTOCHIPS SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO AUTOCHIPS FOR SUCH AUTOCHIPS SOFTWARE AT ISSUE.
 */

#if ! defined(DRV_CONFIG_H)
#define DRV_CONFIG_H

//#include "section.h"
//#include "drv_def.h"

#define CONFIG_DRV_QUICK_START_BOOT 0

#define CONFIG_DRV_FPGA_BOARD 0
#define CONFIG_DRV_ONLY 0
#define CONFIG_DRV_VERIFY_SUPPORT 0
#define CONFIG_DRV_SEMIHOSTING_SUPPORT 0
#define CONFIG_DRV_BLACKSCREEN_PROC 1

//#if CONFIG_SECTION_BUILD_ARM2
#if CONFIG_DRV_MT8520
#define DEFAULT_ARM2
#define DSP_CLK_256M
#define CONFIG_DRV_NR_SUPPORT 0
#else
#define CONFIG_DRV_NR_SUPPORT 1
#endif
//#endif

#define CONFIG_DRV_SHUT_DOWN_ARM2     0
#define CONFIG_DRV_ENABLE_DCM   0
#define CONFIG_DRV_ENABLE_POST_PROC   0

#define CONFIG_DRV_HDWN_SUPPORT		1
#define CONFIG_DRV_WIFI_SUPPORT		0
#define CONFIG_DRV_ALTHD_SUPPORT	0
#define CONFIG_DRV_IFCON_AV_OUT   0

#define CC_EMULATION			0
#define __MODEL_slt__			0
#define ENABLE_MULTIMEDIA		1
#define SYNC_PES_HEADER		1
#define CONFIG_DRV_PCR_VERIFY		0
#define DEMOD_VERIFY			0
#define PLAYCARD_VERIFY		0
#define PVR_ISR_QUEUE_SUPPORT   0
#define PVR_FIFO_WATER_LV       0

#define CONFIG_DRV_KEYBOARD_SUPPORT		0
#define CONFIG_DRV_AUDIO_IN_SUPPORT		0
#define CONFIG_SONY_DRV_AUDIO_IN_SUPPORT		0
#define CONFIG_SONY_DRV_TVS_SUPPORT 0
#define CONFIG_DRV_SPDIF_TYPE_LC89058  0
#define CONFIG_DRV_SPDIF_TYPE_CS8415   1
#define CONFIG_DRV_SPDIF_TYPE_CS8422   2
#define CONFIG_DRV_HDMI_RX_IN_SUPPORT		0
#define CONFIG_DRV_MIC_SUPPORT		0
#define CONFIG_AUD_IN_CS8422_SUPPORT 0

#if (CONFIG_AUD_IN_CS8422_SUPPORT)
#define CONFIG_DRV_SPDIF_TYPE   CONFIG_DRV_SPDIF_TYPE_CS8422
#else
#define CONFIG_DRV_SPDIF_TYPE   CONFIG_DRV_SPDIF_TYPE_LC89058
#endif

#define CONFIG_DRV_LINUX   0
#define CONFIG_DRV_LINUX_DATA_CONSISTENCY    0

#define	CONFIG_DRV_ACON_STANDBY	0
#define	CONFIG_DRV_DISABLE_ARM2	0
#define	CONFIG_MINI_OS	0

#define CONFIG_DRV_FAST_LOGO 0
#define CONFIG_DRV_FASTBOOT_LOGS_OFF  0
#define CONFIG_DRV_CUSTOMER_FASTLOGO 0
#define CONFIG_DRV_BONDING_ENABLE 0
#define CONFIG_DRV_AVM_ENABLE 0
#define CONFIG_DRV_ANIMATION_ENABLE 0
#define CONFIG_DRV_SUSPEND_TO_DRAM 0
#define CONFIG_DRV_OPWRSB_PU 0
#define CONFIG_DRV_TRAY_IN_ACON 0
#define CONFIG_DRV_FAST_EJECT 0

// Audio Sound Effects config version 2
#define CONFIG_SCC_AUD_SE_SUPPORT 0
// (aud_se_v2)
#define CONFIG_AUD_SE_V2_EN 0

#define CONFIG_AUD_SE_MW_CLI_SUPPORT 0

#define CONFIG_DRV_SUPPORT_DVD_AUDIO 0

#define CONFIG_DRV_HIGH_BITRATE_SPECIAL_PROC 0

#define CONFIG_DRV_DVD_24P_SUPPORT 0
#define CONFIG_DRV_SUPPORT_PARTY 0

#define CONFIG_SUPPORT_MCU_SIF 0

#define CONFIG_DRV_SUPPORT_LINUX_DLL_SPLITTER 0

#define CONFIG_OSD5_SUPPORT 0

#define CONFIG_DRV_VIRTUAL_ADDR 1

#define CONFIG_CCIR_COMPANION_CHIP 0

#define CONFIG_DRV_SUPPORT_FLV 0

#define CONFIG_DRV_SUPPORT_SORENSON_H263 0

#define CONFIG_DRV_SUPPORT_RM 0

#define CONFIG_DRV_PWMDAC_SUPPORT 0

#define CONFIG_DRV_LINEIN_PWMDAC_SUPPORT 0

#define CONFIG_DRV_ISPDIF_IN_SUPPORT 0

#define CONFIG_DRV_ISPDIF_IN_MASTERMODE_SUPPORT 0

#define CONFIG_START_BIT 0
#define CONFIG_SUPPORT_MICOM  0
#define	CONFIG_DRV_MP_ICE 0

#define CONFIG_DRV_OPWRSB_PU_SUPPORT 0

#define CONFIG_PQ_CLI_SUPPORT 0

#define CONFIG_DRV_YMH_SUPPORT 0

#define CONFIG_DRV_SSH_SUPPORT 0

#define CONFIG_DRV_ALSA_SOUND_SUPPORT 0


#define CONFIG_DRV_V4L2_SUPPORT 0

//for Streaming button sound
#define CONFIG_AUD_BTN_MEM_PHASE3 0

#define CONFIG_AUD_CD_RIPPING_EN 0

#define CONFIG_AUD_HDMI_CLK_SUPPORT 0

#define CONFIG_DUALCORE_ARM2   0

#define CONFIG_DRAM256_MODEL   0

#define CONFIG_8555_DRAM384_MODEL 0

#if (CONFIG_DUALCORE_ARM2 && CONFIG_DRAM256_MODEL)
#error "Dram256 Model isn't enough to support DualCore!!"
#endif

#define CONFIG_DRV_FPORTABLE_SUPPORT 0

#define CONFIG_DRV_PAS45_SUPPORT 0

#define CONFIG_AUD_WORKBUF_384M_EN 0

#define CONFIG_LOGO_AUTO_PARSE_SUPPORT 0

#define CONFIG_EXT_VIDEO_CHIP_SUPPORT 0

#define CONFIG_DRAM256_PLUS_NEWFEATURE 0

#define CONFIG_DRV_NEW_SD_MODE_SUPPORT 0

#define CONFIG_SIMPLE_UPG_SUPPORT 0

#define CONFIG_FAST_POWER_DOWN  0  
 
#define CONFIG_DRV_CEC_PULLUP_SUPPORT 0

#define CONFIG_DRV_FTS_SUPPORT 0

#define CONFIG_DRV_QUICKSTARTMODE_AVMUTE 0

#define CONFIG_FASTBOOT_MULTI_PHASE_INIT_DRIVER_EN 0

#define CONFIG_PHILIPS_DRV_HTS 0

#define CONFIG_DRV_FTS_SUPPORT 0

#endif //DRV_COMMON_H

