include ':app'
include ':app-overlay'
include ':app-language'
include ':for_build'
include ':test'
include ':mcc202'
include ':mcx'
include ':mcx_exdsp'
include ':mcc400_asp'
include ':mcc405_mnc24'
include ':mcc400_mnc045'
include ':sa133'
include ':sa135'
include ':sa143'
include ':sa155'
include ':xt510'
include ':xt510_asp'
include ':xt540'
include ':xt516'
include ':xt516_f'
include ':xt516_s'
include ':xt758'
include ':za09'
include ':za10'
include ':za12'
include ':za33'
include ':za36'
include ':za37'
include ':za37_asp'
include ':gb01'
include ':gb03'
include ':za39'
include ':csc_asp'
include ':rk02'
include ':gb04'
include ':hcn_library'
include ':mcc602_asp'
