apply plugin: 'com.android.library'

android {
    namespace 'media.lang'
    compileSdk project.compileSdk as int

    defaultConfig {
        minSdk project.minSdk as int
        //noinspection OldTargetApi
        targetSdk project.targetSdk as int

        consumerProguardFiles "consumer-rules.pro"

        flavorDimensions.add("language")
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }

    productFlavors {
        media {
            versionName  "media.lang" \
                + "-" + new Date().format("yyyyMMdd")
            dimension "language"
        }

        skinx {
            versionName  "skinx.lang" \
                + "-" + new Date().format("yyyyMMdd")
            dimension "language"
        }
    }

    sourceSets {
        media {
            jniLibs.srcDirs = ['libs']

            res {
                srcDirs += "src/main/res-common"
                srcDirs += "src/main/res-pool"
                srcDirs += "src/media/res-app"
            }
        }

        skinx {
            jniLibs.srcDirs = ['libs']

            res {
                srcDirs += "src/main/res-common"
                srcDirs += "src/skinx/res-ext"
                srcDirs += "src/skinx/res-ext-pool"
            }
        }
    }

    libraryVariants.configureEach { variant ->
        def releaseDir = rootProject.getRootDir().getAbsolutePath() + "/release/lang/";
        def buildType = variant.buildType.name
        def fileName

        variant.outputs.each {
            if (buildType == "release") {
                def flavorName = variant.flavorName
                fileName = flavorName + "-lang-${buildType}.aar"
                it.outputFileName = fileName
            }
        }

        variant.getAssembleProvider().configure() {
            it.doLast {
                File out = new File(releaseDir)
                copy {
                    variant.outputs.forEach { file ->
                        copy {
                            from file.outputFile
                            into out
                        }
                    }
                }
            }
        }
    }
}

dependencies {
    // 单纯的语言 apk 不需要依赖外部代码库
}