obj-y				+= os_linux_util.o
obj-y				+= os_linux_event.o
obj-y				+= os_linux_ev_grp.o
obj-y				+= os_linux_msg_q.o

ccflags-y += -I$(srctree)/drivers/misc/atc/inc
ccflags-y += -I$(srctree)/drivers/misc/atc/private_inc
ccflags-y += -I$(srctree)/drivers/misc/atc/libosal/ac83xx/inc
