plugins {
    id 'com.android.library'
}

apply plugin: 'update-media-api-doc'

document {
    apiReadmeFile file('./README.md')
    apiDocumentFile file('../docs/MEDIA_API.md')
}

android {
    namespace 'com.hcn.media.api'
    compileSdk project.compileSdk as int

    defaultConfig {
        minSdk project.minSdk as int
        targetSdk project.targetSdk as int

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    libraryVariants.configureEach { variant ->
        def releaseDir = rootProject.getRootDir().getAbsolutePath() + "/release/";
        def buildType = variant.buildType.name
        def fileName

        variant.outputs.each {
            if (buildType == "release") {
                fileName = "media-api-${buildType}.aar"
                it.outputFileName = fileName
            }
        }

        variant.getAssembleProvider().configure() {
            it.doLast {
                File out = new File(releaseDir)
                copy {
                    variant.outputs.forEach { file ->
                        copy {
                            from file.outputFile
                            into out
                        }
                    }
                }
            }
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }
    
    buildFeatures {
        aidl true
    }
}

dependencies {
    compileOnly BuildConfig.libs.androidx_appcompat.path
    compileOnly BuildConfig.libs.common_utils.path
    compileOnly BuildConfig.libs.mediaservice_api.path

    compileOnly files('../release/media-view-release.aar')
}