/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of AutoChips Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AutoChips SOFTWARE") RECEIVED
 *     FROM AutoChips AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. AutoChips EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES AutoChips PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE AutoChips SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. AutoChips SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY AutoChips SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND AutoChips'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE AutoChips SOFTWARE RELEASED HEREUNDER WILL BE, AT AutoChips'S OPTION,
 *     TO REVISE OR REPLACE THE AutoChips SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO AutoChips FOR SUCH AutoChips SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/

/******************************************************************************
*[File]             apcm_ioctrl.h
*[Author]           atc6013
*[Description]
*
******************************************************************************/
#ifndef __APCM_IOCTRL_H_
#define __APCM_IOCTRL_H_

#include "apcm_define.h"

#include "apcm_stream.h"

#include "apcm_ut_comm.h"
#include "apcm_ut_hw.h"


#define APCM_IOCTRL_BASE			0x1000

#define APCM_IOCTRL_GRP_OFFSET			0x20

#define APCM_IOCTRL_HW_GRP			(APCM_IOCTRL_BASE   + 0x00)

	#define APCM_IOCTRL_MIX_CH		(APCM_IOCTRL_HW_GRP + 0x01)
	#define APCM_IOCTRL_PRIMARY_MIC		(APCM_IOCTRL_HW_GRP + 0x02)
	#define APCM_IOCTRL_SET_MIC_HW_GAIN	(APCM_IOCTRL_HW_GRP + 0x03)
	#define APCM_IOCTRL_SET_OUTHW_GAIN	(APCM_IOCTRL_HW_GRP + 0x04)


#define APCM_IOCTRL_SPH_GRP			(APCM_IOCTRL_BASE   + 0x20)

	#define APCM_IOCTRL_BT_ENHANCE		(APCM_IOCTRL_SPH_GRP + 0x01)
	#define APCM_IOCTRL_BT_DUMP_ENABLE	(APCM_IOCTRL_SPH_GRP + 0x02)
	#define APCM_IOCTRL_BT_DBG_FLAG		(APCM_IOCTRL_SPH_GRP + 0x03)


#define APCM_IOCTRL_DBG_GRP			(APCM_IOCTRL_BASE   + 0x100)

	#define APCM_IOCTRL_VER			(APCM_IOCTRL_DBG_GRP + 0x01)
	#define APCM_IOCTRL_LOG			(APCM_IOCTRL_DBG_GRP + 0x02)

	#define APCM_IOCTRL_DUMP_OUT_FILE	(APCM_IOCTRL_DBG_GRP + 0x03)

	#define APCM_IOCTRL_DUMP_MIC_REG	(APCM_IOCTRL_DBG_GRP + 0x04)
	#define APCM_IOCTRL_DUMP_TXRX_REG	(APCM_IOCTRL_DBG_GRP + 0x05)
	#define APCM_IOCTRL_DUMP_ASRC_REG	(APCM_IOCTRL_DBG_GRP + 0x06)

	#define APCM_IOCTRL_LOG_BUF		(APCM_IOCTRL_DBG_GRP + 0x0F)


#define APCM_IOCTRL_UT_GRP			(APCM_IOCTRL_BASE   + 0x120)

	#define APCM_IOCTRL_UT_COMM		(APCM_IOCTRL_UT_GRP + 0x01)
	#define APCM_IOCTRL_UT_OUTHW		(APCM_IOCTRL_UT_GRP + 0x02)
	#define APCM_IOCTRL_UT_MIC		(APCM_IOCTRL_UT_GRP + 0x03)
	#define APCM_IOCTRL_UT_TXRX		(APCM_IOCTRL_UT_GRP + 0x04)
	#define APCM_IOCTRL_UT_ASRC		(APCM_IOCTRL_UT_GRP + 0x05)

	#define APCM_IOCTRL_UT_MAO		(APCM_IOCTRL_UT_GRP + 0x06)
	#define APCM_IOCTRL_UT_SPH		(APCM_IOCTRL_UT_GRP + 0x07)


void ioctrl_cli_srv(u32 type, u32 arg1, u32 arg2, u32 arg3, const s8 **pfilename);

#endif // __APCM_IOCTRL_H_


