obj-y				+= bsp_linux_bsp_if.o
obj-y				+= bsp_linux_bsp_timer.o
obj-y				+= bsp_linux_hal_1176.o
obj-y				+= bsp_mod.o
obj-y				+= bsp_linux_bim_if.o
obj-y				+= bsp_reserved_memory.o
ccflags-y += -I$(srctree)/drivers/misc/atc/inc/
ccflags-y += -I$(srctree)/drivers/misc/atc/private_inc/