#ifndef _PLATFORM_CONFIG_H_
#define _PLATFORM_CONFIG_H_

/* ================= msdc slot_0 configs =============== */

/* step1: function configs */
#define DMSDC0_HOST_FUNCTION		MSDC_EMMC
#define DMSDC0_BOOT_FLAG			MSDC_BOOT_EN

/* step2: timing & I/O configs */
#define DMSDC0_CLK_SRC			MSDC_CLKSRC_196MHZ 
#define DMSDC0_MAXCLK_MHZ		200
#define DMSDC0_CMD_EDGE			MSDC_SMPL_FALLING
#define DMSDC0_RDATA_EDGE		MSDC_SMPL_FALLING
#define DMSDC0_WDATA_EDGE		MSDC_SMPL_FALLING
#define DMSDC0_CLK_DRV_33		0x1F
#define DMSDC0_CMD_DRV_33		0x2F
#define DMSDC0_DAT_DRV_33		0x2F
#define DMSDC0_CLK_DRV_18		0x4
#define DMSDC0_CMD_DRV_18		0x4
#define DMSDC0_DAT_DRV_18		0x4
#define DMSDC0_CLK_DRV_18_SDR50		0x4
#define DMSDC0_CMD_DRV_18_SDR50		0x4
#define DMSDC0_DAT_DRV_18_SDR50		0x4
#define DMSDC0_CLK_DRV_18_DDR50		0x4
#define DMSDC0_CMD_DRV_18_DDR50		0x4
#define DMSDC0_DAT_DRV_18_DDR50		0x4
#define DMSDC0_DAT_PINS			8
#define DMSDC0_TUNING_METHOD	TUNE_EACH_DAT_LINE //TUNE_ALL_DAT_LINE //TUNE_EACH_DAT_LINE 

#define DMSDC0_DAT0_RDDLY		0x0
#define DMSDC0_DAT1_RDDLY		0x0
#define DMSDC0_DAT2_RDDLY		0x0
#define DMSDC0_DAT3_RDDLY		0x0
#define DMSDC0_DAT4_RDDLY		0x0
#define DMSDC0_DAT5_RDDLY		0x0
#define DMSDC0_DAT6_RDDLY		0x0
#define DMSDC0_DAT7_RDDLY		0x0

#define DMSDC0_DAT_WRDDLY		0
#define DMSDC0_CMD_RRDDLY		0
#define DMSDC0_CMD_RDDLY		0
#define DMSDC0_SLEW_RATE					(0x00)
#define DMSDC0_CLK_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC0_CMD_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC0_DAT_RESISTOR					(MSDC_RESISTOR_50K)

#if 1 //============================== Parameter For 162 ====================================
#define DMSDC0_READ_PRE_SETTING_EN			(1) //Enable Read Pre-Setting
#define DMSDC0_READ_DAT_LATCH_CK_SEL		(0)
#define DMSDC0_READ_CKGEN_DELAY_SEL			(7)
#define DMSDC0_READ_SAMPL_EDGE				(0)
#define DMSDC0_READ_PAD_DELAY				(1)
#define DMSDC0_DDR_READ_DAT_LATCH_CK_SEL	(5)
#define DMSDC0_DDR_READ_CKGEN_DELAY_SEL 	(15)

#define DMSDC0_WRITE_PRE_SETTING_EN 		(1)	//Enable Write Pre-Setting
#define DMSDC0_WRITE_DAT_LATCH_CK_SEL		(0)
#define DMSDC0_WRITE_CKGEN_DELAY_SEL		(7)
#define DMSDC0_WRITE_SAMPLE_EDGE 			(0)
#define DMSDC0_WRITE_PAD_DELAY				(3)	// 3
#define DMSDC0_WRITE_INTERNAL_DELAY			(25)
#define DMSDC0_DDR_WRITE_DAT_LATCH_CK_SEL	(5)
#define DMSDC0_DDR_WRITE_CKGEN_DELAY_SEL	(15)

#else  //==================================================================

#define DMSDC0_READ_PRE_SETTING_EN			(1) //Enable Read Pre-Setting
#define DMSDC0_READ_DAT_LATCH_CK_SEL		(0)
#define DMSDC0_READ_CKGEN_DELAY_SEL			(7)
#define DMSDC0_READ_SAMPL_EDGE				(0)
#define DMSDC0_READ_PAD_DELAY				(1)
#define DMSDC0_DDR_READ_DAT_LATCH_CK_SEL	(5)
#define DMSDC0_DDR_READ_CKGEN_DELAY_SEL 	(15)

#define DMSDC0_WRITE_PRE_SETTING_EN 		(1)	//Enable Write Pre-Setting
#define DMSDC0_WRITE_DAT_LATCH_CK_SEL		(0)
#define DMSDC0_WRITE_CKGEN_DELAY_SEL		(5)
#define DMSDC0_WRITE_SAMPLE_EDGE 			(0)
#define DMSDC0_WRITE_PAD_DELAY				(3)	// 3
#define DMSDC0_WRITE_INTERNAL_DELAY			(31)
#define DMSDC0_DDR_WRITE_DAT_LATCH_CK_SEL	(5)
#define DMSDC0_DDR_WRITE_CKGEN_DELAY_SEL	(15)

#endif //==================================================================
#define DMSDC0_CD_METHOD					MSDC_CD_METHOD_NONE



/* ================== msdc slot_1 configs ================ */

/* step1: function configs */
#define DMSDC1_HOST_FUNCTION		MSDC_SD
#define DMSDC1_BOOT_FLAG		0

/* step2: timing & I/O configs */
#define DMSDC1_CLK_SRC			MSDC_CLKSRC_108MHZ
#define DMSDC1_MAXCLK_MHZ		54
#define DMSDC1_CMD_EDGE			MSDC_SMPL_FALLING
#define DMSDC1_RDATA_EDGE		MSDC_SMPL_FALLING
#define DMSDC1_WDATA_EDGE		MSDC_SMPL_FALLING

#define DMSDC1_CLK_DRV_33		0x7
#define DMSDC1_CMD_DRV_33		0xC
#define DMSDC1_DAT_DRV_33		0xC

#define DMSDC1_CLK_DRV_18		0x4
#define DMSDC1_CMD_DRV_18		0x4
#define DMSDC1_DAT_DRV_18		0x4
#define DMSDC1_CLK_DRV_18_SDR50		0x4
#define DMSDC1_CMD_DRV_18_SDR50		0x4
#define DMSDC1_DAT_DRV_18_SDR50		0x4
#define DMSDC1_CLK_DRV_18_DDR50		0x4
#define DMSDC1_CMD_DRV_18_DDR50		0x4
#define DMSDC1_DAT_DRV_18_DDR50		0x4
#define DMSDC1_DAT_PINS			4
#define DMSDC1_TUNING_METHOD	TUNE_EACH_DAT_LINE //TUNE_ALL_DAT_LINE //TUNE_EACH_DAT_LINE 
#define DMSDC1_DAT0_RDDLY		0
#define DMSDC1_DAT1_RDDLY		0
#define DMSDC1_DAT2_RDDLY		0
#define DMSDC1_DAT3_RDDLY		0
#define DMSDC1_DAT4_RDDLY		0
#define DMSDC1_DAT5_RDDLY		0
#define DMSDC1_DAT6_RDDLY		0
#define DMSDC1_DAT7_RDDLY		0
#define DMSDC1_DAT_WRDDLY		0
#define DMSDC1_CMD_RRDDLY		0
#define DMSDC1_CMD_RDDLY		0
#define DMSDC1_SLEW_RATE					(0)
#define DMSDC1_CLK_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC1_CMD_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC1_DAT_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC1_READ_PRE_SETTING_EN			(1)
#define DMSDC1_READ_DAT_LATCH_CK_SEL		(0)
#define DMSDC1_READ_CKGEN_DELAY_SEL			(12)
#define DMSDC1_READ_SAMPL_EDGE				(1)
#define DMSDC1_READ_PAD_DELAY				(12)
#define DMSDC1_DDR_READ_DAT_LATCH_CK_SEL	(5)
#define DMSDC1_DDR_READ_CKGEN_DELAY_SEL 	(15)
#define DMSDC1_WRITE_PRE_SETTING_EN 		(1)
#define DMSDC1_WRITE_DAT_LATCH_CK_SEL		(0)
#define DMSDC1_WRITE_CKGEN_DELAY_SEL		(12)
#define DMSDC1_WRITE_SAMPLE_EDGE 			(1)
#define DMSDC1_WRITE_PAD_DELAY				(12)
#define DMSDC1_WRITE_INTERNAL_DELAY			(12)
#define DMSDC1_DDR_WRITE_DAT_LATCH_CK_SEL	(5)
#define DMSDC1_DDR_WRITE_CKGEN_DELAY_SEL	(15)
#define DMSDC1_CD_METHOD					MSDC_CD_METHOD_INTERRUPT


/* ===================== msdc slot_2 configs ================= */

/* step1: function configs */
#define DMSDC2_HOST_FUNCTION		MSDC_SD
#define DMSDC2_BOOT_FLAG		0

/* step2: timing & I/O configs */
#define DMSDC2_CLK_SRC			MSDC_CLKSRC_108MHZ
#define DMSDC2_MAXCLK_MHZ		54
#define DMSDC2_CMD_EDGE			MSDC_SMPL_FALLING
#define DMSDC2_RDATA_EDGE		MSDC_SMPL_FALLING
#define DMSDC2_WDATA_EDGE		MSDC_SMPL_FALLING

#if 0
#define DMSDC2_CLK_DRV_33		0x5
#define DMSDC2_CMD_DRV_33		0x5
#define DMSDC2_DAT_DRV_33		0x5
#else
#define DMSDC2_CLK_DRV_33		0x7
#define DMSDC2_CMD_DRV_33		0xC
#define DMSDC2_DAT_DRV_33		0xC
#endif

#define DMSDC2_CLK_DRV_18		0x4
#define DMSDC2_CMD_DRV_18		0x4
#define DMSDC2_DAT_DRV_18		0x4
#define DMSDC2_CLK_DRV_18_SDR50		0x4
#define DMSDC2_CMD_DRV_18_SDR50		0x4
#define DMSDC2_DAT_DRV_18_SDR50		0x4
#define DMSDC2_CLK_DRV_18_DDR50		0x4
#define DMSDC2_CMD_DRV_18_DDR50		0x4
#define DMSDC2_DAT_DRV_18_DDR50		0x4
#define DMSDC2_DAT_PINS			4
#define DMSDC2_TUNING_METHOD	TUNE_ALL_DAT_LINE //TUNE_EACH_DAT_LINE 
#define DMSDC2_DAT0_RDDLY		0
#define DMSDC2_DAT1_RDDLY		0
#define DMSDC2_DAT2_RDDLY		0
#define DMSDC2_DAT3_RDDLY		0
#define DMSDC2_DAT4_RDDLY		0
#define DMSDC2_DAT5_RDDLY		0
#define DMSDC2_DAT6_RDDLY		0
#define DMSDC2_DAT7_RDDLY		0
#define DMSDC2_DAT_WRDDLY		0
#define DMSDC2_CMD_RRDDLY		0
#define DMSDC2_CMD_RDDLY		0
#define DMSDC2_SLEW_RATE					(0)
#define DMSDC2_CLK_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC2_CMD_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC2_DAT_RESISTOR					(MSDC_RESISTOR_50K)
#define DMSDC2_READ_PRE_SETTING_EN			(1)
#define DMSDC2_READ_DAT_LATCH_CK_SEL		(0)
#define DMSDC2_READ_CKGEN_DELAY_SEL			(12)
#define DMSDC2_READ_SAMPL_EDGE				(1)
#define DMSDC2_READ_PAD_DELAY				(12)
#define DMSDC2_DDR_READ_DAT_LATCH_CK_SEL	(5)
#define DMSDC2_DDR_READ_CKGEN_DELAY_SEL 	(15)
#define DMSDC2_WRITE_PRE_SETTING_EN 		(1)
#define DMSDC2_WRITE_DAT_LATCH_CK_SEL		(0)
#define DMSDC2_WRITE_CKGEN_DELAY_SEL		(12)
#define DMSDC2_WRITE_SAMPLE_EDGE 			(1)
#define DMSDC2_WRITE_PAD_DELAY				(12)
#define DMSDC2_WRITE_INTERNAL_DELAY			(12)
#define DMSDC2_DDR_WRITE_DAT_LATCH_CK_SEL	(5)
#define DMSDC2_DDR_WRITE_CKGEN_DELAY_SEL	(15)
#define DMSDC2_CD_METHOD					MSDC_CD_METHOD_INTERRUPT

#endif

