#ifndef HMI_ELEMENT_ID_H
#define HMI_ELEMENT_ID_H	

#ifndef HMI_ENGINE_C
#define EXTERN	extern
#else
#define EXTERN	
#endif

/*All element ID   */
enum
{
/*Dynamic element ID   */
/*Static page dynamic x,y   */
/*Static page static x,y   */
	 HMI_CLASSIC_PAGE=0
	,HMI_MOTION_PAGE/* 1 */
/*Static ImageList Dyn prop ID     */
	,HMI_SPEED_MOTION_100_IMAGE_LIST/* 2 */
	,HMI_SPEED_MOTION_10_IMAGE_LIST/* 3 */
	,HMI_SPEED_MOTION_1_IMAGE_LIST/* 4 */
/*Static ImageList static prop ID     */
	,HMI_RPM_IMAGE_LIST/* 5 */
	,HMI_SPEED_TEN_IMAGE_LIST/* 6 */
	,HMI_SPEED_ZERO_IMAGE_LIST/* 7 */
	,HMI_SPEED_HUNDRED_IMAGE_LIST/* 8 */
	,HMI_SPEED_MOTION_RIGHT_100_IMAGE_LIST_IMAGE_LIST/* 9 */
/*Static scroll Dyn prop ID     */
/*Static scroll static prop ID     */
/*Static Button Dyn prop ID     */
/*Static Button static prop ID     */
/*Editable text dynamic x,y   */
	,HMI_FUEL_TEXT/* 10 */
	,HMI_RPM_TEXT20/* 11 */
	,HMI_QD_TEXT/* 12 */
/*Editable text static x,y   */
	,HMI_SPEED_TEXT/* 13 */
	,HMI_KM_TEXT/* 14 */
	,HMI_NEW_TEXT22/* 15 */
	,HMI_BOTTOM_TEXT/* 16 */
	,HMI_BOTTOM_TOTAL_TEXT32/* 17 */
	,HMI_DATE_TEXT/* 18 */
	,HMI_TIME_TEXT/* 19 */
	,HMI_SPEED_DANG_TEXT/* 20 */
	,HMI_NORMAL_TEXT/* 21 */
	,HMI_KM_TEXT45/* 22 */
	,HMI_NEW_TEXT15/* 23 */
	,HMI_TIME_TEXT_TEXT51/* 24 */
	,HMI_TEMP_TEXT/* 25 */
	,HMI_LEFT_ARROW_TIP_TEXT/* 26 */
	,HMI_RIGHT_ARROW_TIP_TEXT/* 27 */
	,HMI_DIRECT_ARROW_TIP_TEXT/* 28 */
	,HMI_NEW_TEXT5/* 29 */
/*Dyn container ID     */
	,HMI_DYN_FUEL_CONTAINER/* 30 */
	,HMI_DYN_RIGHT_FUEL_CONTAINER/* 31 */
	,HMI_DYN_MIDDLE_CONTAINER/* 32 */
	,HMI_DYN_MIDDLE_OPTION_CONTAINER/* 33 */
	,HMI_DYN_LIGHT_CONTAINER/* 34 */
	,HMI_DYN_UPPER_CONTAINER/* 35 */
	,HMI_DYN_RIGHT_FUEL_CONTAINER_CONTAINER25/* 36 */
	,HMI_DYN_LEFT_CONTAINER/* 37 */
	,HMI_DYN_RIGHT_CONTAINER/* 38 */
	,HMI_DYN_MOTION_MENU_CONTAINER/* 39 */
	,HMI_DYN_NAVI_MOTION_CONTAINER/* 40 */
	,HMI_DYN_ROAD_ARROW_CONTAINER/* 41 */
	,HMI_DYN_FAR_NEAR_LIGHT_CONTAINER/* 42 */
	,HMI_DYN_FAR_NEAR_LIGHT_CONTAINER_CONTAINER16/* 43 */
	,HMI_DYN_NAVI_DISTANCE_CONTAINER/* 44 */
	,HMI_DYN_NAVI_ARROW_CONTAINER/* 45 */
	,HMI_DYN_HEV_CONTAINER/* 46 */
/*Dynamic fill ID   */
	,HMI_NAVI_CAMERA_FILL/* 47 */
	,HMI_DXY_FILL/* 48 */
	,HMI_CAMERA_LEFT_CLUSTER_FILL/* 49 */
	,HMI_CAMERA_RIGHT_CLUSTER_FILL/* 50 */
	,HMI_CAMERA_CAR_3D_FILL/* 51 */
	,HMI_NAVI_PRISM_CAMERA_FILL/* 52 */
	,HMI_CAMERA_NAVI_FILL/* 53 */
	,HMI_SPEED_FILL/* 54 */
	,HMI_RPM_FILL/* 55 */
/*Dynamic gridient fill ID   */
/*Static cube dynamic x,y   */
/*Static 3D model dynamic x,y   */
/*Language ID*/
	,HMI_LANGUAGE/* 56 */
/*Static container Dyn prop ID     */
	,HMI_DXY_MIDDLE_ZONE_CONTAINER/* 57 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER260/* 58 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER200/* 59 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER140/* 60 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER100/* 61 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER60/* 62 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER40/* 63 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER20/* 64 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER0/* 65 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER7_CONTAINER/* 66 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER6_CONTAINER/* 67 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER5_CONTAINER/* 68 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER4_CONTAINER/* 69 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER3_CONTAINER/* 70 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER2_CONTAINER/* 71 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER0_CONTAINER/* 72 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER1_CONTAINER/* 73 */
	,HMI_POINTER_FUEL_MOTION_CONTAINER/* 74 */
	,HMI_POINTER_WATER_MOTION_CONTAINER/* 75 */
	,HMI_POINTER_WATER_CONTAINER/* 76 */
	,HMI_POINTER_FULE_LEFT_CONTAINER/* 77 */
/*Static image dynamic x,y   */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY/* 78 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY/* 79 */
	,HMI_LEFT_ARRAY_IMAGE_DXY/* 80 */
	,HMI_NAVI_CAR_IMAGE/* 81 */
/*Static image dynamic x,y   */
	,HMI_POINTER_IMAGE/* 82 */
	,HMI_RIGHT_POINTER_IMAGE/* 83 */
	,HMI_LEFT_MOTION_POINTER_IMAGE/* 84 */
	,HMI_RIGHT_WATER_POINTER_IMAGE/* 85 */
	,HMI_FUEL_POINTER_IMAGE/* 86 */
	,HMI_POINTER_WATER_IMAGE/* 87 */
/*Dxy mul point spline */
/*Dxy one point spline */
/*Sxy mul point spline */
/*Sxy one point spline */
/*Custom dynamic x,y   */
	,HMI_LEFT_FOLLOW_MOTION_LIB/* 88 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB/* 89 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB/* 90 */
	,HMI_WATER_FOLLOW_MOTION_LIB/* 91 */
	,HMI_SIMPLE_NAVI_LIB116/* 92 */
/*uneditable text dynamic x,y   */
/*uneditable text static x,y   */
/*All BIN Segment   */
	,HMI_SEGMENT1/* 93 */
	,HMI_SEGMENT2/* 94 */
/*Static container Dyn prop ID     */
	/* _X */
	,HMI_DXY_MIDDLE_ZONE_CONTAINER_X/* 95 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER260_X/* 96 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER200_X/* 97 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER140_X/* 98 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER100_X/* 99 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER60_X/* 100 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER40_X/* 101 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER20_X/* 102 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER0_X/* 103 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER7_CONTAINER_X/* 104 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER6_CONTAINER_X/* 105 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER5_CONTAINER_X/* 106 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER4_CONTAINER_X/* 107 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER3_CONTAINER_X/* 108 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER2_CONTAINER_X/* 109 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER0_CONTAINER_X/* 110 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER1_CONTAINER_X/* 111 */
	,HMI_POINTER_FUEL_MOTION_CONTAINER_X/* 112 */
	,HMI_POINTER_WATER_MOTION_CONTAINER_X/* 113 */
	,HMI_POINTER_WATER_CONTAINER_X/* 114 */
	,HMI_POINTER_FULE_LEFT_CONTAINER_X/* 115 */
	/* _Y */
	,HMI_DXY_MIDDLE_ZONE_CONTAINER_Y/* 116 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER260_Y/* 117 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER200_Y/* 118 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER140_Y/* 119 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER100_Y/* 120 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER60_Y/* 121 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER40_Y/* 122 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER20_Y/* 123 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER0_Y/* 124 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER7_CONTAINER_Y/* 125 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER6_CONTAINER_Y/* 126 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER5_CONTAINER_Y/* 127 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER4_CONTAINER_Y/* 128 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER3_CONTAINER_Y/* 129 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER2_CONTAINER_Y/* 130 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER0_CONTAINER_Y/* 131 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER1_CONTAINER_Y/* 132 */
	,HMI_POINTER_FUEL_MOTION_CONTAINER_Y/* 133 */
	,HMI_POINTER_WATER_MOTION_CONTAINER_Y/* 134 */
	,HMI_POINTER_WATER_CONTAINER_Y/* 135 */
	,HMI_POINTER_FULE_LEFT_CONTAINER_Y/* 136 */
	/* _W */
	,HMI_DXY_MIDDLE_ZONE_CONTAINER_W/* 137 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER260_W/* 138 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER200_W/* 139 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER140_W/* 140 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER100_W/* 141 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER60_W/* 142 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER40_W/* 143 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER20_W/* 144 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER0_W/* 145 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER7_CONTAINER_W/* 146 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER6_CONTAINER_W/* 147 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER5_CONTAINER_W/* 148 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER4_CONTAINER_W/* 149 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER3_CONTAINER_W/* 150 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER2_CONTAINER_W/* 151 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER0_CONTAINER_W/* 152 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER1_CONTAINER_W/* 153 */
	,HMI_POINTER_FUEL_MOTION_CONTAINER_W/* 154 */
	,HMI_POINTER_WATER_MOTION_CONTAINER_W/* 155 */
	,HMI_POINTER_WATER_CONTAINER_W/* 156 */
	,HMI_POINTER_FULE_LEFT_CONTAINER_W/* 157 */
	/* _H */
	,HMI_DXY_MIDDLE_ZONE_CONTAINER_H/* 158 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER260_H/* 159 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER200_H/* 160 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER140_H/* 161 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER100_H/* 162 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER60_H/* 163 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER40_H/* 164 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER20_H/* 165 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER0_H/* 166 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER7_CONTAINER_H/* 167 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER6_CONTAINER_H/* 168 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER5_CONTAINER_H/* 169 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER4_CONTAINER_H/* 170 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER3_CONTAINER_H/* 171 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER2_CONTAINER_H/* 172 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER0_CONTAINER_H/* 173 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER1_CONTAINER_H/* 174 */
	,HMI_POINTER_FUEL_MOTION_CONTAINER_H/* 175 */
	,HMI_POINTER_WATER_MOTION_CONTAINER_H/* 176 */
	,HMI_POINTER_WATER_CONTAINER_H/* 177 */
	,HMI_POINTER_FULE_LEFT_CONTAINER_H/* 178 */
	/* _ALPHA */
	,HMI_DXY_MIDDLE_ZONE_CONTAINER_ALPHA/* 179 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER260_ALPHA/* 180 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER200_ALPHA/* 181 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER140_ALPHA/* 182 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER100_ALPHA/* 183 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER60_ALPHA/* 184 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER40_ALPHA/* 185 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER20_ALPHA/* 186 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER0_ALPHA/* 187 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER7_CONTAINER_ALPHA/* 188 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER6_CONTAINER_ALPHA/* 189 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER5_CONTAINER_ALPHA/* 190 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER4_CONTAINER_ALPHA/* 191 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER3_CONTAINER_ALPHA/* 192 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER2_CONTAINER_ALPHA/* 193 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER0_CONTAINER_ALPHA/* 194 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER1_CONTAINER_ALPHA/* 195 */
	,HMI_POINTER_FUEL_MOTION_CONTAINER_ALPHA/* 196 */
	,HMI_POINTER_WATER_MOTION_CONTAINER_ALPHA/* 197 */
	,HMI_POINTER_WATER_CONTAINER_ALPHA/* 198 */
	,HMI_POINTER_FULE_LEFT_CONTAINER_ALPHA/* 199 */
	/* _SCALE */
	,HMI_DXY_MIDDLE_ZONE_CONTAINER_SCALE/* 200 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER260_SCALE/* 201 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER200_SCALE/* 202 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER140_SCALE/* 203 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER100_SCALE/* 204 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER60_SCALE/* 205 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER40_SCALE/* 206 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER20_SCALE/* 207 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER0_SCALE/* 208 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER7_CONTAINER_SCALE/* 209 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER6_CONTAINER_SCALE/* 210 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER5_CONTAINER_SCALE/* 211 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER4_CONTAINER_SCALE/* 212 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER3_CONTAINER_SCALE/* 213 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER2_CONTAINER_SCALE/* 214 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER0_CONTAINER_SCALE/* 215 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER1_CONTAINER_SCALE/* 216 */
	,HMI_POINTER_FUEL_MOTION_CONTAINER_SCALE/* 217 */
	,HMI_POINTER_WATER_MOTION_CONTAINER_SCALE/* 218 */
	,HMI_POINTER_WATER_CONTAINER_SCALE/* 219 */
	,HMI_POINTER_FULE_LEFT_CONTAINER_SCALE/* 220 */
	/* _X */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_X/* 221 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_X/* 222 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_X/* 223 */
	,HMI_NAVI_CAR_IMAGE_X/* 224 */
	,HMI_POINTER_IMAGE_X/* 225 */
	,HMI_RIGHT_POINTER_IMAGE_X/* 226 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_X/* 227 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_X/* 228 */
	,HMI_FUEL_POINTER_IMAGE_X/* 229 */
	,HMI_POINTER_WATER_IMAGE_X/* 230 */
	/* _Y */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_Y/* 231 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_Y/* 232 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_Y/* 233 */
	,HMI_NAVI_CAR_IMAGE_Y/* 234 */
	,HMI_POINTER_IMAGE_Y/* 235 */
	,HMI_RIGHT_POINTER_IMAGE_Y/* 236 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_Y/* 237 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_Y/* 238 */
	,HMI_FUEL_POINTER_IMAGE_Y/* 239 */
	,HMI_POINTER_WATER_IMAGE_Y/* 240 */
	/* _W */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_W/* 241 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_W/* 242 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_W/* 243 */
	,HMI_NAVI_CAR_IMAGE_W/* 244 */
	,HMI_POINTER_IMAGE_W/* 245 */
	,HMI_RIGHT_POINTER_IMAGE_W/* 246 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_W/* 247 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_W/* 248 */
	,HMI_FUEL_POINTER_IMAGE_W/* 249 */
	,HMI_POINTER_WATER_IMAGE_W/* 250 */
	/* _H */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_H/* 251 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_H/* 252 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_H/* 253 */
	,HMI_NAVI_CAR_IMAGE_H/* 254 */
};

enum
{
	 HMI_POINTER_IMAGE_H=255
	,HMI_RIGHT_POINTER_IMAGE_H/* 256 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_H/* 257 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_H/* 258 */
	,HMI_FUEL_POINTER_IMAGE_H/* 259 */
	,HMI_POINTER_WATER_IMAGE_H/* 260 */
	/* _ALPHA */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_ALPHA/* 261 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_ALPHA/* 262 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_ALPHA/* 263 */
	,HMI_NAVI_CAR_IMAGE_ALPHA/* 264 */
	,HMI_POINTER_IMAGE_ALPHA/* 265 */
	,HMI_RIGHT_POINTER_IMAGE_ALPHA/* 266 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_ALPHA/* 267 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_ALPHA/* 268 */
	,HMI_FUEL_POINTER_IMAGE_ALPHA/* 269 */
	,HMI_POINTER_WATER_IMAGE_ALPHA/* 270 */
	/* _ANGEL */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_ANGEL/* 271 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_ANGEL/* 272 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_ANGEL/* 273 */
	,HMI_NAVI_CAR_IMAGE_ANGEL/* 274 */
	,HMI_POINTER_IMAGE_ANGEL/* 275 */
	,HMI_RIGHT_POINTER_IMAGE_ANGEL/* 276 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_ANGEL/* 277 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_ANGEL/* 278 */
	,HMI_FUEL_POINTER_IMAGE_ANGEL/* 279 */
	,HMI_POINTER_WATER_IMAGE_ANGEL/* 280 */
	/* _BLUR */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_BLUR/* 281 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_BLUR/* 282 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_BLUR/* 283 */
	,HMI_NAVI_CAR_IMAGE_BLUR/* 284 */
	,HMI_POINTER_IMAGE_BLUR/* 285 */
	,HMI_RIGHT_POINTER_IMAGE_BLUR/* 286 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_BLUR/* 287 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_BLUR/* 288 */
	,HMI_FUEL_POINTER_IMAGE_BLUR/* 289 */
	,HMI_POINTER_WATER_IMAGE_BLUR/* 290 */
	/* _TRAIL */
	,HMI_REAR_LIGHT_LEFT_IMAGE_DXY_TRAIL/* 291 */
	,HMI_REAR_LIGHT_RIGHT_IMAGE_DXY_TRAIL/* 292 */
	,HMI_LEFT_ARRAY_IMAGE_DXY_TRAIL/* 293 */
	,HMI_NAVI_CAR_IMAGE_TRAIL/* 294 */
	,HMI_POINTER_IMAGE_TRAIL/* 295 */
	,HMI_RIGHT_POINTER_IMAGE_TRAIL/* 296 */
	,HMI_LEFT_MOTION_POINTER_IMAGE_TRAIL/* 297 */
	,HMI_RIGHT_WATER_POINTER_IMAGE_TRAIL/* 298 */
	,HMI_FUEL_POINTER_IMAGE_TRAIL/* 299 */
	,HMI_POINTER_WATER_IMAGE_TRAIL/* 300 */
/*Static page dynamic x,y   */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _ALPHA */
/*Static ImageList Dyn prop ID     */
	/* _X */
	,HMI_SPEED_MOTION_100_IMAGE_LIST_X/* 301 */
	,HMI_SPEED_MOTION_10_IMAGE_LIST_X/* 302 */
	,HMI_SPEED_MOTION_1_IMAGE_LIST_X/* 303 */
	/* _Y */
	,HMI_SPEED_MOTION_100_IMAGE_LIST_Y/* 304 */
	,HMI_SPEED_MOTION_10_IMAGE_LIST_Y/* 305 */
	,HMI_SPEED_MOTION_1_IMAGE_LIST_Y/* 306 */
	/* _W */
	,HMI_SPEED_MOTION_100_IMAGE_LIST_W/* 307 */
	,HMI_SPEED_MOTION_10_IMAGE_LIST_W/* 308 */
	,HMI_SPEED_MOTION_1_IMAGE_LIST_W/* 309 */
	/* _H */
	,HMI_SPEED_MOTION_100_IMAGE_LIST_H/* 310 */
	,HMI_SPEED_MOTION_10_IMAGE_LIST_H/* 311 */
	,HMI_SPEED_MOTION_1_IMAGE_LIST_H/* 312 */
	/* _ALPHA */
	,HMI_SPEED_MOTION_100_IMAGE_LIST_ALPHA/* 313 */
	,HMI_SPEED_MOTION_10_IMAGE_LIST_ALPHA/* 314 */
	,HMI_SPEED_MOTION_1_IMAGE_LIST_ALPHA/* 315 */
/*Static scroll Dyn prop ID     */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _ALPHA */
/*Static Button Dyn prop ID     */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _ALPHA */
/*uneditable text dynamic x,y   */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _COLOUR */
/*Editable text dynamic x,y   */
	/* _X */
	,HMI_FUEL_TEXT_X/* 316 */
	,HMI_RPM_TEXT20_X/* 317 */
	,HMI_QD_TEXT_X/* 318 */
	/* _Y */
	,HMI_FUEL_TEXT_Y/* 319 */
	,HMI_RPM_TEXT20_Y/* 320 */
	,HMI_QD_TEXT_Y/* 321 */
	/* _W */
	,HMI_FUEL_TEXT_W/* 322 */
	,HMI_RPM_TEXT20_W/* 323 */
	,HMI_QD_TEXT_W/* 324 */
	/* _H */
	,HMI_FUEL_TEXT_H/* 325 */
	,HMI_RPM_TEXT20_H/* 326 */
	,HMI_QD_TEXT_H/* 327 */
	/* _COLOUR */
	,HMI_FUEL_TEXT_COLOUR/* 328 */
	,HMI_RPM_TEXT20_COLOUR/* 329 */
	,HMI_QD_TEXT_COLOUR/* 330 */
/*Dynamic fill ID   */
	/* _X */
	,HMI_NAVI_CAMERA_FILL_X/* 331 */
	,HMI_DXY_FILL_X/* 332 */
	,HMI_CAMERA_LEFT_CLUSTER_FILL_X/* 333 */
	,HMI_CAMERA_RIGHT_CLUSTER_FILL_X/* 334 */
	,HMI_CAMERA_CAR_3D_FILL_X/* 335 */
	,HMI_NAVI_PRISM_CAMERA_FILL_X/* 336 */
	,HMI_CAMERA_NAVI_FILL_X/* 337 */
	,HMI_SPEED_FILL_X/* 338 */
	,HMI_RPM_FILL_X/* 339 */
	/* _Y */
	,HMI_NAVI_CAMERA_FILL_Y/* 340 */
	,HMI_DXY_FILL_Y/* 341 */
	,HMI_CAMERA_LEFT_CLUSTER_FILL_Y/* 342 */
	,HMI_CAMERA_RIGHT_CLUSTER_FILL_Y/* 343 */
	,HMI_CAMERA_CAR_3D_FILL_Y/* 344 */
	,HMI_NAVI_PRISM_CAMERA_FILL_Y/* 345 */
	,HMI_CAMERA_NAVI_FILL_Y/* 346 */
	,HMI_SPEED_FILL_Y/* 347 */
	,HMI_RPM_FILL_Y/* 348 */
	/* _W */
	,HMI_NAVI_CAMERA_FILL_W/* 349 */
	,HMI_DXY_FILL_W/* 350 */
	,HMI_CAMERA_LEFT_CLUSTER_FILL_W/* 351 */
	,HMI_CAMERA_RIGHT_CLUSTER_FILL_W/* 352 */
	,HMI_CAMERA_CAR_3D_FILL_W/* 353 */
	,HMI_NAVI_PRISM_CAMERA_FILL_W/* 354 */
	,HMI_CAMERA_NAVI_FILL_W/* 355 */
	,HMI_SPEED_FILL_W/* 356 */
	,HMI_RPM_FILL_W/* 357 */
	/* _H */
	,HMI_NAVI_CAMERA_FILL_H/* 358 */
	,HMI_DXY_FILL_H/* 359 */
	,HMI_CAMERA_LEFT_CLUSTER_FILL_H/* 360 */
	,HMI_CAMERA_RIGHT_CLUSTER_FILL_H/* 361 */
	,HMI_CAMERA_CAR_3D_FILL_H/* 362 */
	,HMI_NAVI_PRISM_CAMERA_FILL_H/* 363 */
	,HMI_CAMERA_NAVI_FILL_H/* 364 */
	,HMI_SPEED_FILL_H/* 365 */
	,HMI_RPM_FILL_H/* 366 */
	/* _COLOUR */
	,HMI_NAVI_CAMERA_FILL_COLOUR/* 367 */
	,HMI_DXY_FILL_COLOUR/* 368 */
	,HMI_CAMERA_LEFT_CLUSTER_FILL_COLOUR/* 369 */
	,HMI_CAMERA_RIGHT_CLUSTER_FILL_COLOUR/* 370 */
	,HMI_CAMERA_CAR_3D_FILL_COLOUR/* 371 */
	,HMI_NAVI_PRISM_CAMERA_FILL_COLOUR/* 372 */
	,HMI_CAMERA_NAVI_FILL_COLOUR/* 373 */
	,HMI_SPEED_FILL_COLOUR/* 374 */
	,HMI_RPM_FILL_COLOUR/* 375 */
	/* _Z */
	,HMI_NAVI_CAMERA_FILL_Z/* 376 */
	,HMI_DXY_FILL_Z/* 377 */
	,HMI_CAMERA_LEFT_CLUSTER_FILL_Z/* 378 */
	,HMI_CAMERA_RIGHT_CLUSTER_FILL_Z/* 379 */
	,HMI_CAMERA_CAR_3D_FILL_Z/* 380 */
	,HMI_NAVI_PRISM_CAMERA_FILL_Z/* 381 */
	,HMI_CAMERA_NAVI_FILL_Z/* 382 */
	,HMI_SPEED_FILL_Z/* 383 */
	,HMI_RPM_FILL_Z/* 384 */
/*Dynamic gridient fill ID   */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _COLOR1 */
	/* _COLOR2 */
	/* _Z */
/*Static cube dynamic x,y   */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _BUMP */
	/* _ANGEL */
	/* _PRI_ANGEL */
	/* _Z */
	/* _SCALE */
/*Static 3D model dynamic x,y   */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _BUMP */
	/* _ANGEL */
	/* _PRI_ANGEL */
	/* _Z */
	/* _SCALE */
/*Editable text dynamic x,y   */
	/* _SCROLL */
	,HMI_FUEL_TEXT_SCROLL/* 385 */
	,HMI_RPM_TEXT20_SCROLL/* 386 */
	,HMI_QD_TEXT_SCROLL/* 387 */
/*Editable text static x,y   */
	/* _SCROLL */
	,HMI_SPEED_TEXT_SCROLL/* 388 */
	,HMI_KM_TEXT_SCROLL/* 389 */
	,HMI_NEW_TEXT22_SCROLL/* 390 */
	,HMI_BOTTOM_TEXT_SCROLL/* 391 */
	,HMI_BOTTOM_TOTAL_TEXT32_SCROLL/* 392 */
	,HMI_DATE_TEXT_SCROLL/* 393 */
	,HMI_TIME_TEXT_SCROLL/* 394 */
	,HMI_SPEED_DANG_TEXT_SCROLL/* 395 */
	,HMI_NORMAL_TEXT_SCROLL/* 396 */
	,HMI_KM_TEXT45_SCROLL/* 397 */
	,HMI_NEW_TEXT15_SCROLL/* 398 */
	,HMI_TIME_TEXT_TEXT51_SCROLL/* 399 */
	,HMI_TEMP_TEXT_SCROLL/* 400 */
	,HMI_LEFT_ARROW_TIP_TEXT_SCROLL/* 401 */
	,HMI_RIGHT_ARROW_TIP_TEXT_SCROLL/* 402 */
	,HMI_DIRECT_ARROW_TIP_TEXT_SCROLL/* 403 */
	,HMI_NEW_TEXT5_SCROLL/* 404 */
	/* _X */
	/* _Y */
	/* _W */
	/* _H */
	/* _SCALE */
/*Custom dynamic x,y   */
	/* _X */
	,HMI_LEFT_FOLLOW_MOTION_LIB_X/* 405 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_X/* 406 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_X/* 407 */
	,HMI_WATER_FOLLOW_MOTION_LIB_X/* 408 */
	,HMI_SIMPLE_NAVI_LIB116_X/* 409 */
	/* _Y */
	,HMI_LEFT_FOLLOW_MOTION_LIB_Y/* 410 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_Y/* 411 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_Y/* 412 */
	,HMI_WATER_FOLLOW_MOTION_LIB_Y/* 413 */
	,HMI_SIMPLE_NAVI_LIB116_Y/* 414 */
	/* _Z */
	,HMI_LEFT_FOLLOW_MOTION_LIB_Z/* 415 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_Z/* 416 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_Z/* 417 */
	,HMI_WATER_FOLLOW_MOTION_LIB_Z/* 418 */
	,HMI_SIMPLE_NAVI_LIB116_Z/* 419 */
	/* _W */
	,HMI_LEFT_FOLLOW_MOTION_LIB_W/* 420 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_W/* 421 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_W/* 422 */
	,HMI_WATER_FOLLOW_MOTION_LIB_W/* 423 */
	,HMI_SIMPLE_NAVI_LIB116_W/* 424 */
	/* _H */
	,HMI_LEFT_FOLLOW_MOTION_LIB_H/* 425 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_H/* 426 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_H/* 427 */
	,HMI_WATER_FOLLOW_MOTION_LIB_H/* 428 */
	,HMI_SIMPLE_NAVI_LIB116_H/* 429 */
	/* _P1 */
	,HMI_LEFT_FOLLOW_MOTION_LIB_P1/* 430 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_P1/* 431 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_P1/* 432 */
	,HMI_WATER_FOLLOW_MOTION_LIB_P1/* 433 */
	,HMI_SIMPLE_NAVI_LIB116_P1/* 434 */
	/* _P2 */
	,HMI_LEFT_FOLLOW_MOTION_LIB_P2/* 435 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_P2/* 436 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_P2/* 437 */
	,HMI_WATER_FOLLOW_MOTION_LIB_P2/* 438 */
	,HMI_SIMPLE_NAVI_LIB116_P2/* 439 */
	/* _P3 */
	,HMI_LEFT_FOLLOW_MOTION_LIB_P3/* 440 */
	,HMI_RIGHT_FOLLOW_MOTION_LIB_P3/* 441 */
	,HMI_FUEL_LEFT_FOLLOW_MOTION_LIB_P3/* 442 */
	,HMI_WATER_FOLLOW_MOTION_LIB_P3/* 443 */
	,HMI_SIMPLE_NAVI_LIB116_P3/* 444 */
/*Static element ID   */
/*Static fill ID   */
	,HMI_NEW_FILL38/* 445 */
	,HMI_CAR_AMBIENT_FILL/* 446 */
	,HMI_CAR_DIFFUSE_FILL/* 447 */
	,HMI_CAR_SPECULAR_FILL/* 448 */
	,HMI_EF_COLOR_FILL/* 449 */
	,HMI_NEW_FILL6/* 450 */
	,HMI_NEW_FILL7/* 451 */
	,HMI_NEW_FILL8/* 452 */
	,HMI_NEW_FILL9/* 453 */
	,HMI_NEW_FILL10/* 454 */
	,HMI_NEW_FILL11/* 455 */
	,HMI_NEW_FILL118/* 456 */
	,HMI_POINT_TRAIL_FILL/* 457 */
	,HMI_MOTION_TRAIL_FILL/* 458 */
	,HMI_NEW_FILL15/* 459 */
	,HMI_NEW_FILL115/* 460 */
	,HMI_NEW_FILL1116/* 461 */
	,HMI_NEW_FILL5/* 462 */
/*Static gridient fill ID   */
/*Static cube static x,y   */
/*Static 3D model static x,y   */
	,HMI_NUMBER_IMAGE0/* 463 */
	,HMI_NUMBER_IMAGE30/* 464 */
	,HMI_NUMBER_IMAGE60/* 465 */
	,HMI_NUMBER_IMAGE90/* 466 */
	,HMI_NUMBER_IMAGE120/* 467 */
	,HMI_NUMBER_IMAGE150/* 468 */
	,HMI_NUMBER_IMAGE180/* 469 */
	,HMI_NUMBER_IMAGE210/* 470 */
	,HMI_NUMBER_IMAGE240/* 471 */
	,HMI_NUMBER_IMAGE270/* 472 */
	,HMI_FUEL_BCK_IMAGE/* 473 */
	,HMI_FUEL_LOGO_IMAGE/* 474 */
	,HMI_RIGHT_CLUSTER_IMAGE0/* 475 */
	,HMI_RIGHT_CLUSTER_IMAGE1/* 476 */
	,HMI_RIGHT_CLUSTER_IMAGE2/* 477 */
	,HMI_RIGHT_CLUSTER_IMAGE3/* 478 */
	,HMI_RIGHT_CLUSTER_IMAGE4/* 479 */
	,HMI_RIGHT_CLUSTER_IMAGE5/* 480 */
	,HMI_RIGHT_CLUSTER_IMAGE6/* 481 */
	,HMI_RIGHT_CLUSTER_IMAGE7/* 482 */
	,HMI_RIGHT_CLUSTER_IMAGE8/* 483 */
	,HMI_RIGHT_CLUSTER_IMAGE9/* 484 */
	,HMI_EMPTY_IMAGE1/* 485 */
	,HMI_FULL_IMAGE1/* 486 */
	,HMI_MIDDLE_BCK_IMAGE34/* 487 */
	,HMI_CAR_IMAGE/* 488 */
	,HMI_CAR_LIGHT_IMAGE/* 489 */
	,HMI_HEV_IMAGE/* 490 */
	,HMI_CHARGE_IMAGE/* 491 */
	,HMI_RIGHT_ARRAY_GREY_IMAGE/* 492 */
	,HMI_NEAR_IMAGE/* 493 */
	,HMI_NEAR_IMAGE_IMAGE19/* 494 */
	,HMI_SHADER_MAP_IMAGE/* 495 */
	,HMI_NAVI_ARROW_IMAGE/* 496 */
	,HMI_ARROW_GO_AHEAD_IMAGE/* 497 */
	,HMI_NAVI_DISTANCE_BCK_IMAGE/* 498 */
	,HMI_NAVI_ARROW_LEFT_IMAGE/* 499 */
	,HMI_NAVI_ARROW_RIGHT_IMAGE/* 500 */
	,HMI_NAVI_ARROW_DIRECT_IMAGE/* 501 */
	,HMI_BCK_LEFT_MOTION_IMAGE/* 502 */
	,HMI_LEFT_MOTION_NUMBER_IMAGE260/* 503 */
	,HMI_LEFT_MOTION_NUMBER_IMAGE200/* 504 */
	,HMI_LEFT_MOTION_NUMBER_IMAGE140/* 505 */
	,HMI_LEFT_MOTION_NUMBER_IMAGE100/* 506 */
	,HMI_LEFT_MOTION_NUMBER_IMAGE60/* 507 */
	,HMI_LEFT_MOTION_NUMBER_IMAGE40/* 508 */
	,HMI_LEFT_MOTION_NUMBER_IMAGE20/* 509 */
};

enum
{
	 HMI_LEFT_MOTION_NUMBER_IMAGE0=510
	,HMI_RIGHT_MOTION_NUMBER_IMAGE7_IMAGE/* 511 */
	,HMI_RIGHT_MOTION_NUMBER_IMAGE6_IMAGE/* 512 */
	,HMI_RIGHT_MOTION_NUMBER_IMAGE5_IMAGE/* 513 */
	,HMI_RIGHT_MOTION_NUMBER_IMAGE4_IMAGE/* 514 */
	,HMI_RIGHT_MOTION_NUMBER_IMAGE3_IMAGE/* 515 */
	,HMI_RIGHT_MOTION_NUMBER_IMAGE2_IMAGE/* 516 */
	,HMI_RIGHT_MOTION_NUMBER_IMAGE1_IMAGE/* 517 */
	,HMI_RIGHT_MOTION_NUMBER_IMAGE0_IMAGE/* 518 */
	,HMI_FUEL_MOTION_BCK_IMAGE_IMAGE/* 519 */
	,HMI_FUEL_MOTION_FLAG_IMAGE_IMAGE/* 520 */
	,HMI_WATER_BCK_IMAGE/* 521 */
	,HMI_WATER_TEM_FLAG_IMAGE/* 522 */
	,HMI_BCK_RIGHT_MOTION_IMAGE/* 523 */
	,HMI_RIGHT_MOTION_TRAIL_IMAGE_IMAGE/* 524 */
	,HMI_LEFT_MOTION_TRAIL_IMAGE/* 525 */
	,HMI_TRAIL_IMAGE/* 526 */
	,HMI_BCK_RIGHT_IMAGE/* 527 */
	,HMI_BCK_LEFT_IMAGE/* 528 */
	,HMI_UPPER_ZONE_IMAGE/* 529 */
	,HMI_UPPER_BOTTOM_IMAGE/* 530 */
	,HMI_FUEL_TRAIL_IMAGE/* 531 */
	,HMI_TRAIL_WATER_IMAGE/* 532 */
/*Custom static x,y   */
	,HMI_PREFIX_COLOR_ALPHA_LIB4/* 533 */
	,HMI_PREFIX_COLOR_ALPHA_LIB5/* 534 */
	,HMI_PREFIX_COLOR_ALPHA_LIB3/* 535 */
/*Static container static prop ID     */
	,HMI_LEFT_CLUSTER_CONTAINER/* 536 */
	,HMI_NEW_CONTAINER22/* 537 */
	,HMI_LEFT_CLUSTER_NO_CONTAINER/* 538 */
	,HMI_FUEL_CONTAINER/* 539 */
	,HMI_FUEL_CONTAINER4/* 540 */
	,HMI_FUEL_CONTAINER3/* 541 */
	,HMI_FUEL_CONTAINER2/* 542 */
	,HMI_FUEL_CONTAINER1/* 543 */
	,HMI_LEFT_CLUSTER_SPEED_NUM_CONTAINER/* 544 */
	,HMI_NEW_CONTAINER43/* 545 */
	,HMI_RIGHT_CLUSTER_CONTAINER/* 546 */
	,HMI_RIGHT_CLUSTER_NO_CONTAINER/* 547 */
	,HMI_RIGHT_FUEL_CONTAINER/* 548 */
	,HMI_MIDDLE_CONTAINER0/* 549 */
	,HMI_MIDDLE_CONTAINER1/* 550 */
	,HMI_BOTTOM_CONTAINER30/* 551 */
	,HMI_UPPER_CONTAINER33/* 552 */
	,HMI_CAR_CONTAINER/* 553 */
	,HMI_PRE_LIGHT_CONTAINER/* 554 */
	,HMI_REAR_LIGHT_CONTAINER/* 555 */
	,HMI_UPPER_ZONE_CONTAINER/* 556 */
	,HMI_CAR_INFI_CONTAINER/* 557 */
	,HMI_FUEL_CONTAINER4_CONTAINER26/* 558 */
	,HMI_FUEL_CONTAINER3_CONTAINER27/* 559 */
	,HMI_FUEL_CONTAINER2_CONTAINER28/* 560 */
	,HMI_FUEL_CONTAINER1_CONTAINER29/* 561 */
	,HMI_FUEL_RIGHT_CONTAINER5/* 562 */
	,HMI_FUEL_RIGHT_CONTAINER4/* 563 */
	,HMI_FUEL_RIGHT_CONTAINER3/* 564 */
	,HMI_FUEL_RIGHT_CONTAINER2/* 565 */
	,HMI_FUEL_RIGHT_CONTAINER1/* 566 */
	,HMI_FUEL_RIGHT_CONTAINER0/* 567 */
	,HMI_FUEL_CONTAINER0/* 568 */
	,HMI_LEFT_CLUSTER_CONTAINER_CUBE/* 569 */
	,HMI_RIGHT_CLUSTER_CONTAINER_CUBE/* 570 */
	,HMI_BCK_MOTION_CONTAINER/* 571 */
	,HMI_LEFT_MOTION_CONTAINER/* 572 */
	,HMI_LEFT_MOTION_NUMBER_CONTAINER/* 573 */
	,HMI_SPEED_MOTION_CONTAINER/* 574 */
	,HMI_LEFT_MOTION_SMALL_CONTAINER/* 575 */
	,HMI_MOTION_MIDDLE_CONTAINER/* 576 */
	,HMI_MOTION_CIRCLE_MENU_CONTAINER/* 577 */
	,HMI_MOTION_PRISM_MENU_CONTAINER_NULL/* 578 */
	,HMI_NAVI_CONTAINER/* 579 */
	,HMI_MEDIA_CONTAINER/* 580 */
	,HMI_RIGHT_MOTION_CONTAINER/* 581 */
	,HMI_WATER_CONTAINER/* 582 */
	,HMI_TIMER_CONTAINER/* 583 */
	,HMI_MOTION_TIMER_CONTAINER/* 584 */
	,HMI_NAVI_ARROW_CONTAINER/* 585 */
	,HMI_TRAIL_WATER_CONTAINER/* 586 */
	,HMI_LIGHT_LEFT_CONTAINER1/* 587 */
	,HMI_NEAR_LIGHT_CONTAINER/* 588 */
	,HMI_FAR_LIGHT_CONTAINER/* 589 */
	,HMI_NEW_CONTAINER15/* 590 */
	,HMI_NEAR_LIGHT_CONTAINER_CONTAINER17/* 591 */
	,HMI_FAR_LIGHT_CONTAINER_CONTAINER18/* 592 */
	,HMI_NEW_CONTAINER25/* 593 */
	,HMI_RIGHT_MOTION_CONTAINER_CONTAINER/* 594 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER_CONTAINER/* 595 */
	,HMI_SPEED_MOTION_RIGHT_CONTAINER_CONTAINER/* 596 */
	,HMI_MOTION_TIMER_CONTAINER_CONTAINER/* 597 */
	,HMI_RIGHT_MOTION_NUMBER_CONTAINER8_CONTAINER/* 598 */
	,HMI_LEFT_MOTION_TRAIL_CONTAINER/* 599 */
	,HMI_RIGHT_MOTION_TRAIL_CONTAINER/* 600 */
	,HMI_CAR_3D_CONTAINER/* 601 */
	,HMI_FUEL_MOTION_CONTAINER/* 602 */
	,HMI_WATER_CONTAINER_CONTAINER5/* 603 */
	,HMI_TRAIL_FULE_SMALL_CONTAINER/* 604 */
	,HMI_DISTANCE_NAVI_CONTAINER/* 605 */
	,HMI_NAVI_ARROW_LEFT_CONTAINER/* 606 */
	,HMI_NAVI_ARROW_RIGHT_CONTAINER/* 607 */
	,HMI_DISTANCE_NAVI_CONTAINER_NULL/* 608 */
	,HMI_NEW_CONTAINER3/* 609 */
	,HMI_NAVI_ARROW_DIRECT_CONTAINER/* 610 */
	,HMI_CIRCLE_LIST_CONTAINER/* 611 */
	,HMI_NAVI_MENU__CONTAINER5/* 612 */
	,HMI_NAVI_MENU__CONTAINER0/* 613 */
	,HMI_NAVI_MENU__CONTAINER1/* 614 */
	,HMI_NAVI_MENU__CONTAINER2/* 615 */
	,HMI_NAVI_MENU__CONTAINER3/* 616 */
	,HMI_NAVI_MENU__CONTAINER4/* 617 */
	,HMI_MOTION_PRISM_MENU_CONTAINER/* 618 */
	,HMI_MOTION_LAYOUT_MENU_CONTAINER/* 619 */
	,HMI_CLASSIC_PAGE_BCK_CONTAINER/* 620 */
	,HMI_NEW_CONTAINER4/* 621 */
	,HMI_LEFT_CLUSTER_CONTAINER_XY_ZERO/* 622 */
	,HMI_LEFT_CUBE_CONTAINER/* 623 */
	,HMI_RIGHT_CLUSTER_CONTAINER_XY/* 624 */
	,HMI_RIGHT_CLUSTER_CUBE_CONTAINER/* 625 */
	,HMI_NAVI_MAP_CONTAINER/* 626 */
	,HMI_NAVI_CUBE_CONTAINER/* 627 */
	,HMI_NAVI_MAP_CUBE_CONTAINER/* 628 */
	,HMI_NAVI_MAP_CONTAINER_XY/* 629 */
	,HMI_QD_MOTION_CONTAINER/* 630 */
	,HMI_QD_CLASSIC_CONTAINER/* 631 */
	,HMI_HEV_CONTAINER7/* 632 */
	,HMI_HEV_CONTAINER_NULL/* 633 */
	,HMI_MAIN_CONTAINER/* 634 */
	,HMI_MOTION_MAIN_CONTAINER/* 635 */
	,HMI_NEW_CONTAINER5/* 636 */
	,HMI_NEW_CONTAINER7/* 637 */
	,HMI_SIMPLE_NAVI_CONTAINER/* 638 */
	,HMI_RIGHT_FOLLOW_CONTAINER/* 639 */
/*All language ID   */
	,HMI_ENGLISH/* 640 */
/*Stand event element ID   */
	/*Run element ID   */
	/*Program control element ID   */
	/*Button press element ID   */
	/*Button up element ID   */
	/*Buttong long press element ID   */
	/*Button repeat element ID   */
	/*Page on element ID   */
	/*Page of element ID   */
/*Custom event element ID   */
/*Action entry element ID   */
	,HMI_CLASSIC_PAGE_ACTION_ENTRY/* 641 */
	,HMI_LEFT_MOTION_ACTION_ENTRY/* 642 */
	,HMI_DYN_LEFT_CUBE_ACTION_ENTRY/* 643 */
	,HMI_DYN_LEFT_CUBE_ACTION_BCK_ENTRY/* 644 */
	,HMI_DYN_RIGHT_CUBE_ACTION_ENTRY/* 645 */
	,HMI_DYN_RIGHT_CUBE_ACTION_BCK_ENTRY/* 646 */
	,HMI_MOVE_MAP_ACTION_ENTRY/* 647 */
	,HMI_SCROLL_TEXT_QD_ACTION_ENTRY/* 648 */
	,HMI_DYN_NAVI_CUBE_ACTION_ENTRY/* 649 */
	,HMI_LEFT_MOTION_BCK_ACTION_ENTRY/* 650 */
	,HMI_LEFT_FUEL_ACTION_ENTRY/* 651 */
	,HMI_LEFT_BCK_FUEL_ACTION_ENTRY/* 652 */
	,HMI_NAVI_MENUCIRCLE_ACTION_ENTRY/* 653 */
	,HMI_NAVI_MENUPRISM_ACTION_ENTRY/* 654 */
	,HMI_LAYOUT_ACTION_ENTRY/* 655 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY0/* 656 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY20/* 657 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY40/* 658 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY60/* 659 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY100/* 660 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY140/* 661 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY200/* 662 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY260/* 663 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY0S/* 664 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY20S/* 665 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY40S/* 666 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY60S/* 667 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY100S/* 668 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY140S/* 669 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY200S/* 670 */
	,HMI_LEFT_NUM_SCALE_ACTION_ENTRY260S/* 671 */
	,HMI_RIGH_NUM_ACTION_ENTRY6/* 672 */
	,HMI_RIGH_NUM_ACTION_ENTRY5/* 673 */
	,HMI_RIGH_NUM_ACTION_ENTRY4/* 674 */
	,HMI_RIGH_NUM_ACTION_ENTRY1/* 675 */
	,HMI_RIGH_NUM_ACTION_ENTRY3/* 676 */
	,HMI_RIGH_NUM_ACTION_ENTRY2/* 677 */
	,HMI_RIGH_NUM_ACTION_ENTRY0/* 678 */
	,HMI_RIGH_NUM_ACTION_ENTRY6S/* 679 */
	,HMI_RIGH_NUM_ACTION_ENTRY5S/* 680 */
	,HMI_RIGH_NUM_ACTION_ENTRY4S/* 681 */
	,HMI_RIGH_NUM_ACTION_ENTRY1S/* 682 */
	,HMI_RIGH_NUM_ACTION_ENTRY3S/* 683 */
	,HMI_RIGH_NUM_ACTION_ENTRY2S/* 684 */
	,HMI_RIGH_NUM_ACTION_ENTRY0S/* 685 */
	,HMI_POINTER_ACTION_ENTRY4/* 686 */
	,HMI_POINTER_BCK_ACTION_ENTRY/* 687 */
	,HMI_NAVI_SCALE_ACTION_ENTRY/* 688 */
	,HMI_NAVI_Y_ACTION_ENTRY/* 689 */
/*Timer action element ID   */
	/*Repeat element ID   */
	,HMI_POINTER_TIMER_ACTION/* 690 */
	,HMI_REPEAT_LEFT_ARRAY_TIMER_ACTION/* 691 */
	,HMI_FUEL_TIMER_ACTION/* 692 */
	,HMI_WATER_TIMER_ACTION/* 693 */
	,HMI_REPEAT_TIMER_TIMER_ACTION/* 694 */
	,HMI_REPEAT_TOTAL_TIMER_ACTION/* 695 */
	/*One time element ID   */
	,HMI_FUEL1_TIMER_ACTION/* 696 */
	,HMI_FUEL2_TIMER_ACTION/* 697 */
	,HMI_FUEL3_TIMER_ACTION/* 698 */
	,HMI_FUEL4_TIMER_ACTION/* 699 */
	,HMI_WATER1_TIMER_ACTION/* 700 */
	,HMI_WATER2_TIMER_ACTION/* 701 */
	,HMI_WATER3_TIMER_ACTION/* 702 */
	,HMI_WATER4_TIMER_ACTION/* 703 */
	,HMI_SECOND_1_TIMER_ACTION/* 704 */
	,HMI_SECOND_2_TIMER_ACTION/* 705 */
	,HMI_TOTAL_10S_TIMER_ACTION/* 706 */
	,HMI_SET_LEFT_DYN_TIMER_ACTION/* 707 */
	,HMI_DELAY_10S_TIMER_ACTION/* 708 */
	,HMI_NEW_TIMER_ACTION9/* 709 */
	,HMI_DYN_CUBE_CONTAINER_TIMER_ACTION/* 710 */
	,HMI_SET_LEFT_DYN_CON_TIMER_ACTION/* 711 */
	,HMI_SET_RIGHT_DYN_CON_TIMER_ACTION/* 712 */
	,HMI_NEW_TIMER_ACTION6/* 713 */
	/*Duration element ID   */
	,HMI_LEFT_POINTER_TIMER_ACTION/* 714 */
	,HMI_LEFT_POINTER_BCK_TIMER_ACTION/* 715 */
	,HMI_SCALE_MIDDLE_TIMER_ACTION/* 716 */
	,HMI_LEFT_ARRAY_2S_TIMER_ACTION/* 717 */
	,HMI_LEFT_MOTION_5_TIMER_ACTION/* 718 */
	,HMI_REPEAT_TIMER_ACTION8/* 719 */
	,HMI_MOVE_LEFT_CAMERA_TIMER_ACTION/* 720 */
	,HMI_MOVE_LEFT_CAMERA_BCK_TIMER_ACTION/* 721 */
	,HMI_MOVE_RIGHT_CAMERA_TIMER_ACTION/* 722 */
	,HMI_MOVE_RIGHT_CAMERA_BCK_TIMER_ACTION/* 723 */
	,HMI_MOVE_MAP_TIMER_ACTION/* 724 */
	,HMI_MOVE_NAVI_CAMERA_TIMER_ACTION/* 725 */
	,HMI_SCROLL_TEXT_6_TIMER_ACTION/* 726 */
	,HMI_LEFT_MOTION_BCK_5_TIMER_ACTION/* 727 */
	,HMI_LEFT_FULE_TIMER_3S_ACTION/* 728 */
	,HMI_LEFT_FULE_BCK_TIMER_3S_ACTION/* 729 */
	,HMI_NAVI_MENUCIRCLE1_TIMER_ACTION/* 730 */
	,HMI_PRISM1_TIMER_ACTION/* 731 */
	,HMI_LAYOUT_TIMER_ACTION/* 732 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION0/* 733 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1/* 734 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION2/* 735 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION3/* 736 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION4/* 737 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION5/* 738 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION6/* 739 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION7/* 740 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1112/* 741 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1115/* 742 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1118/* 743 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1121/* 744 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1124/* 745 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1127/* 746 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1130/* 747 */
	,HMI_LEFT_NUM_SCALE_TIMER_ACTION1133/* 748 */
	,HMI_RIGHT_NUM_TIMER_ACTION/* 749 */
	,HMI_RIGHT_NUM_TIMER_ACTION139/* 750 */
	,HMI_RIGHT_NUM_TIMER_ACTION142/* 751 */
	,HMI_RIGHT_NUM_TIMER_ACTION145/* 752 */
	,HMI_RIGHT_NUM_TIMER_ACTION148/* 753 */
	,HMI_RIGHT_NUM_TIMER_ACTION151/* 754 */
	,HMI_RIGHT_NUM_TIMER_ACTION154/* 755 */
	,HMI_RIGHT_NUM_TIMER_ACTION157/* 756 */
	,HMI_RIGHT_NUM_TIMER_ACTION139160/* 757 */
	,HMI_RIGHT_NUM_TIMER_ACTION142163/* 758 */
	,HMI_RIGHT_NUM_TIMER_ACTION145166/* 759 */
	,HMI_RIGHT_NUM_TIMER_ACTION148169/* 760 */
	,HMI_RIGHT_NUM_TIMER_ACTION151172/* 761 */
	,HMI_RIGHT_NUM_TIMER_ACTION154175/* 762 */
	,HMI_NEW_TIMER_ACTION21/* 763 */
	,HMI_NEW_TIMER_ACTION22/* 764 */
	/*Dyn duration element ID   */
/*Action entry element ID   */
	/*Set position action element ID   */
	/*Set position action element ID   */
};

enum
{
	 HMI_SPEED_SET_ACTION=765
	,HMI_SPEED_BCK_SET_ACTION/* 766 */
	,HMI_WATER_TEMP_SET_ACTION/* 767 */
	,HMI_FUEL_SET_ACTION/* 768 */
	,HMI_WATER_SET_ACTION/* 769 */
	,HMI_FUEL_SMALL_LEFT_SET_ACTION/* 770 */
	,HMI_MOVE_LEFT_CUBE_CAMERA_SET_ACTION/* 771 */
	,HMI_MOVE_LEFT_CUBE_CAMERA_BCK_SET_ACTION/* 772 */
	,HMI_MOVE_LEFT_CONTAINER_SET_ACTION/* 773 */
	,HMI_MOVE_RIGHT_CUBE_CAMERA_SET_ACTION/* 774 */
	,HMI_MOVE_RIGHT_CUBE_CAMERA_BCK_SET_ACTION/* 775 */
	,HMI_MOVE_NAVI_CUBE_CAMERA_SET_ACTION/* 776 */
	,HMI_SET_SPEED_FILL_SET_ACTION/* 777 */
	,HMI_SET_SPEED_FILL_BCK_SET_ACTION/* 778 */
	,HMI_NEW_SET_ACTION7/* 779 */
	,HMI_NEW_SET_ACTION4/* 780 */
	,HMI_NEW_SET_ACTION5/* 781 */
	,HMI_NEW_SET_ACTION6/* 782 */
	/*Set position action element ID   */
	/*Set delta position action element ID   */
	/*Set width height action element ID   */
	/*Set width height action element ID   */
	/*Set width height action element ID   */
	/*Set delta w/h action element ID   */
	/*Set dynamic widget action element ID   */
	,HMI_FUEL_1_SET_ACTION/* 783 */
	,HMI_FUEL_2_SET_ACTION/* 784 */
	,HMI_FUEL_3_SET_ACTION/* 785 */
	,HMI_FUEL_4_SET_ACTION/* 786 */
	,HMI_WATER_1_SET_ACTION/* 787 */
	,HMI_WATER_2_SET_ACTION/* 788 */
	,HMI_WATER_3_SET_ACTION/* 789 */
	,HMI_WATER_4_SET_ACTION/* 790 */
	,HMI_SET_DYN_LEFT_CUBE_ACTION/* 791 */
	,HMI_SET_DYN_LEFT_CONTAINER_ACTION/* 792 */
	,HMI_SET_DYN_RIGHT_CUBE_ACTION/* 793 */
	,HMI_SET_DYN_RIGHT_CONTAINER_ACTION/* 794 */
	,HMI_SET_DYN_NAVI_CUBE_ACTION/* 795 */
	/*Set page on/off action element ID   */
	/*Set text buffer action element ID   */
	,HMI_FUEL1_TEXT_SET_ACTION/* 796 */
	,HMI_FUEL2_TEXT_SET_ACTION/* 797 */
	,HMI_FUEL3_TEXT_SET_ACTION/* 798 */
	,HMI_FUEL4_TEXT_SET_ACTION/* 799 */
	,HMI_RIGHT_FUEL1_TEXT_SET_ACTION/* 800 */
	,HMI_RIGHT_FUEL2_TEXT_SET_ACTION/* 801 */
	,HMI_RIGHT_FUEL3_TEXT_SET_ACTION/* 802 */
	,HMI_RIGHT_FUEL4_TEXT_SET_ACTION/* 803 */
	,HMI_TIMER_9_30_SET_ACTION/* 804 */
	,HMI_TIMER_9_30_2_SET_ACTION/* 805 */
	,HMI_FUEL_DIS_SET_ACTION1/* 806 */
	,HMI_FUEL_DIS_SET_ACTION2/* 807 */
	,HMI_FUEL_DIS_SET_ACTION3/* 808 */
	,HMI_FUEL_DIS_SET_ACTION4/* 809 */
	/*Set text scroll step action element ID   */
	,HMI_SCROLL_TEXT_SET_ACTION/* 810 */
	/*Set foreground color action element ID   */
	,HMI_SET_FUEL3_TEXT_COLOR_SET_ACTION/* 811 */
	,HMI_SET_FUEL_4_TEXT_COLOR_SET_ACTION/* 812 */
	,HMI_SET_FUEL2_TEXT_COLOR_SET_ACTION/* 813 */
	,HMI_SET_FUEL1_TEXT_COLOR_SET_ACTION/* 814 */
	,HMI_SET_RIGHT_FUEL1_TEXT_COLOR_SET_ACTION/* 815 */
	,HMI_SET_RIGHT_FUEL2_TEXT_COLOR_SET_ACTION/* 816 */
	,HMI_SET_RIGHT_FUEL3_TEXT_COLOR_SET_ACTION/* 817 */
	,HMI_SET_RIGHT_FUEL4_TEXT_COLOR_SET_ACTION/* 818 */
	/*Set foreground color action element ID   */
	/*Set foreground color action element ID   */
	/*Set P1 action element ID   */
	/*Set P1 action element ID   */
	,HMI_NEW_SET_ACTION3/* 819 */
	/*Set P1 action element ID   */
	/*Set P2 action element ID   */
	/*Set P2 action element ID   */
	,HMI_FOLLOW_MOTION_LEFT_SET_ACTION/* 820 */
	,HMI_FOLLOW_MOTION_RIGHT_SET_ACTION/* 821 */
	,HMI_FOLLOW_MOTION_BCK_LEFT_SET_ACTION/* 822 */
	,HMI_FOLLOW_MOTION_BCK_RIGHT_SET_ACTION/* 823 */
	,HMI_LEFT_FUEL_SET_ACTION11/* 824 */
	,HMI_RIGHT_WATER_SET_ACTION12/* 825 */
	,HMI_LEFT_FUEL_BCK_SET_ACTION11/* 826 */
	,HMI_RIGHT_WATER_BCK_SET_ACTION12/* 827 */
	/*Set P2 action element ID   */
	/*Set P3 action element ID   */
	/*Set P3 action element ID   */
	/*Set P3 action element ID   */
	/*Set send event action element ID   */
	/*Set call function action element ID   */
	,HMI_SPEED_SET_ACTION_F/* 828 */
	/*Set set image list status action element ID   */
	/*Set set image list status action element ID   */
	/*Set set image list status action element ID   */
	/*Set set scroll bar status action element ID   */
	/*Set set button status action element ID   */
	/*Set alpha action element ID   */
	/*Set alpha action element ID   */
	,HMI_LEFT_ARRAY_ALPHA_SET_ACTION/* 829 */
	,HMI_REAR_LIGHT_SET_ACTION/* 830 */
	,HMI_REAR_RIGHT_LIGHT_SET_ACTION/* 831 */
	/*Set alpha action element ID   */
	/*Set container scale action element ID   */
	/*Set container scale action element ID   */
	,HMI_SCALE_MIDDLE_SET_ACTION/* 832 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION0/* 833 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1/* 834 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION20/* 835 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION3/* 836 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION4/* 837 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION5/* 838 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION6/* 839 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION7/* 840 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1113/* 841 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1116/* 842 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1119/* 843 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1122/* 844 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1125/* 845 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1128/* 846 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1131/* 847 */
	,HMI_LEFT_NUM_SCALE_SET_ACTION1134/* 848 */
	,HMI_RIGHT_NUM_SET_ACTION/* 849 */
	,HMI_RIGHT_NUM_SET_ACTION140/* 850 */
	,HMI_RIGHT_NUM_SET_ACTION143/* 851 */
	,HMI_RIGHT_NUM_SET_ACTION146/* 852 */
	,HMI_RIGHT_NUM_SET_ACTION149/* 853 */
	,HMI_RIGHT_NUM_SET_ACTION152/* 854 */
	,HMI_RIGHT_NUM_SET_ACTION155/* 855 */
	,HMI_RIGHT_NUM_SET_ACTION158/* 856 */
	,HMI_RIGHT_NUM_SET_ACTION140161/* 857 */
	,HMI_RIGHT_NUM_SET_ACTION143164/* 858 */
	,HMI_RIGHT_NUM_SET_ACTION146167/* 859 */
	,HMI_RIGHT_NUM_SET_ACTION149170/* 860 */
	,HMI_RIGHT_NUM_SET_ACTION152173/* 861 */
	,HMI_RIGHT_NUM_SET_ACTION155176/* 862 */
	/*Set container scale action element ID   */
	/*Set angel action element ID   */
	/*Set angel action element ID   */
	,HMI_LEFT_POINTER_SET_ACTION/* 863 */
	,HMI_LEFT_POINTER_BCK_SET_ACTION/* 864 */
	,HMI_RIGHT_POINTER_SET_ACTION/* 865 */
	,HMI_RIGHT_POINTER_BCK_SET_ACTION/* 866 */
	,HMI_NEW_SET_ACTION8/* 867 */
	/*Set angel action element ID   */
	/*Dyn duration element ID prop start */
	/*Dyn duration element ID prop duration */
	/*Set position action element ID   */
	/*Set position action element ID   */
	/*Set width height action element ID   */
	/*Set width height action element ID   */
	/*Set foreground color action element ID   */
	/*Set foreground color action element ID   */
	/*Set set image list status action element ID   */
	/*Set set image list status action element ID   */
	/*Set alpha action element ID   */
	/*Set alpha action element ID   */
	/*Set container scale action element ID   */
	/*Set container scale action element ID   */
	/*Set angel action element ID   */
	/*Set angel action element ID   */
/*Status table ID   */
/*Single status ID no action ID */
/*Single status ID exist action ID */
/*Status table event ID  */

	,HMI_NB_ELEMENTS/* 868 */
};

#define HMI_GRAPHIC_OPENGLES                                     
#define HMI_PIX_FORMAT                                           HMI_BGR888
#define HMI_MAX_TEXT_LENGTH                                      40
#define HMI_ALL_OBJECT                                           868
#define HMI_NDXY_PAGES_NUMBER                                    0
#define HMI_VDXY_PAGES_NUMBER                                    0
#define HMI_DXY_PAGES_NUMBER                                     0
#define HMI_NSXY_PAGES_NUMBER                                    2
#define HMI_VSXY_PAGES_NUMBER                                    0
#define HMI_SXY_PAGES_NUMBER                                     2
#define HMI_PAGES_NUMBER                                         2
#define HMI_DXY_IMAGELIST_NUMBER                                 3
#define HMI_SXY_IMAGELIST_NUMBER                                 5
#define HMI_DXY_SCROLLBAR_NUMBER                                 0
#define HMI_SXY_SCROLLBAR_NUMBER                                 0
#define HMI_DXY_BUTTON_NUMBER                                    0
#define HMI_SXY_BUTTON_NUMBER                                    0
#define HMI_SXY_CUBE_NUMBER                                      0
#define HMI_SXY_3DCUBE_NUMBER                                    0
#define HMI_DXY_CUBE_NUMBER                                      0
#define HMI_DXY_3DCUBE_NUMBER                                    0
#define HMI_3D_MODEL_CUSTOM_NUMBER                               0
#define HMI_DYN_EDIT_TEXTS_NUMBER                                20
#define HMI_ALL_DYN_OBJECTS_NUMBER                               93
#define HMI_DYN_CONTAINERS_NUMBER                                17
#define HMI_SCENE_DYN_CONTAINERS_NUMBER                          0
#define HMI_NORMAL_DYN_CONTAINERS_NUMBER                         17
#define HMI_DYN_FILL_PAGES_NUMBER                                9
#define HMI_DYN_GFILL_NUMBER                                     0
#define HMI_DYN_LANGUAGE_NUMBER                                  1
#define HMI_DYN_LANGUAGE_INIT                                    HMI_ENGLISH
#define HMI_DXY_CONTAINERS_NUMBER                                21
#define HMI_DXY_CONTAINERS_SCALE_ALPHA_NUMBER                    17
#define HMI_DXY_CENTER_SINGLE_TEXTURE_BITMAPS_NUMBER             4
#define HMI_DXY_CENTER_MUL_TEXTURE_BITMAPS_NUMBER                0
#define HMI_DXY_CENTER_BITMAPS_NUMBER                            4
#define HMI_DXY_ROTATION_SINGLE_TEXTURE_BITMAPS_NUMBER           6
#define HMI_DXY_ROTATION_MUL_TEXTURE_BITMAPS_NUMBER              0
#define HMI_DXY_ROTATION_BITMAPS_NUMBER                          6
#define HMI_DXY_BITMAPS_NUMBER                                   10
#define HMI_DYN_XY_EDIT_TEXTS_NUMBER                             3
#define HMI_S_XY_EDIT_TEXTS_NUMBER                               17
#define HMI_STATIC_FILL_PAGES_NUMBER                             18
#define HMI_STATIC_GFILL_NUMBER                                  0
#define HMI_SXY_SINGLE_TEXTURE_BITMAPS_NUMBER                    70
#define HMI_SXY_MUL_TEXTURE_BITMAPS_NUMBER                       0
#define HMI_SXY_BITMAPS_NUMBER                                   70
#define HMI_SXY_CONTAINERS_NUMBER                                104
#define HMI_LANGUAGE_NUMBER                                      1
#define HMI_STATIC_TEXTS_NUMBER                                  0
#define HMI_UNEDIT_TEXTS_STATIC_XY_NUMBER                        0
#define HMI_UNEDIT_TEXTS_DYN_XY_NUMBER                           0
#define HMI_ALL_STATIC_OBJECTS_NUMBER                            193
#define HMI_DYN_TEXT_SCROLL_NUMBER                               20
#define HMI_BBITMAP_NUMBER                                       2
#define HMI_EVENT_STAND_NUMBER                                   0
#define HMI_EVENT_STAND_RUN_NUMBER                               0
#define HMI_EVENT_STAND_PRESS_NUMBER                             0
#define HMI_EVENT_STAND_UP_NUMBER                                0
#define HMI_EVENT_STAND_LONG_PRESS_NUMBER                        0
#define HMI_EVENT_REPEAT_NUMBER                                  0
#define HMI_EVENT_PAGE_ON_NUMBER                                 0
#define HMI_EVENT_PAGE_OFF_NUMBER                                0
#define HMI_EVENT_PROG_CONTROL_NUMBER                            0
#define HMI_EVENT_CUSTOM_NUMBER                                  0
#define HMI_ACTION_GROUP_NUMBER                                  49
#define HMI_TIMER_ACTION_NUMBER                                  75
#define HMI_TIMER_ACTION_REPEAT_NUMBER                           6
#define HMI_TIMER_ACTION_ONETIME_NUMBER                          18
#define HMI_TIMER_ACTION_DURATION_NUMBER                         51
#define HMI_DYN_TIMER_ACTION_DURATION_NUMBER                     0
#define HMI_S_TIMER_ACTION_DURATION_NUMBER                       51
#define HMI_SET_ACTION_NUMBER                                    103
#define HMI_SET_POS_NUMBER                                       18
#define HMI_NO_ANIM_SET_POS_NUMBER                               0
#define HMI_ANIM_STATIC_SET_POS_NUMBER                           18
#define HMI_ANIM_DYN_SET_POS_NUMBER                              0
#define HMI_SET_DELTA_POS_NUMBER                                 0
#define HMI_NO_ANIM_SET_P1_NUMBER                                0
#define HMI_ANIM_STATIC_SET_P1_NUMBER                            1
#define HMI_ANIM_DYN_SET_P1_NUMBER                               0
#define HMI_NO_ANIM_SET_P2_NUMBER                                0
#define HMI_ANIM_STATIC_SET_P2_NUMBER                            8
#define HMI_ANIM_DYN_SET_P2_NUMBER                               0
#define HMI_NO_ANIM_SET_P3_NUMBER                                0
#define HMI_ANIM_STATIC_SET_P3_NUMBER                            0
#define HMI_ANIM_DYN_SET_P3_NUMBER                               0
#define HMI_SET_W_H_NUMBER                                       0
#define HMI_SET_W_H_NO_ANIM_NUMBER                               0
#define HMI_ANIM_STATIC_SET_W_H_NUMBER                           0
#define HMI_ANIM_DYN_SET_W_H_NUMBER                              0
#define HMI_SET_DELTA_W_H_NUMBER                                 0
#define HMI_SET_DYN_CONTAINER_NUMBER                             13
#define HMI_SET_PAGE_ON_OFF_NUMBER                               0
#define HMI_SET_EDIT_TEXT_NUMBER                                 14
#define HMI_SET_TEXT_SCROLL_STEP_NUMBER                          1
#define HMI_SET_CALL_FUNC_NUMBER                                 1
#define HMI_SET_IMAGELIST_INDEX_NUMBER                           0
#define HMI_SET_IMAGELIST_INDEX_NO_ANIM_NUMBER                   0
#define HMI_ANIM_STATIC_SET_IMAGELIST_INDEX_NUMBER               0
#define HMI_ANIM_DYN_SET_IMAGELIST_INDEX_NUMBER                  0
#define HMI_SET_SCROLLBAR_RANGE_NUMBER                           0
#define HMI_SET_BUTTON_STATUS_NUMBER                             0
#define HMI_SET_SEND_EVENT_NUMBER                                0
#define HMI_SET_BTN_STATUS_NUMBER                                0
#define HMI_SET_FOR_COLOR_NUMBER                                 8
#define HMI_SET_FOR_COLOR_NO_ANIM_NUMBER                         8
#define HMI_ANIM_STATIC_SET_FOR_COLOR_NUMBER                     0
#define HMI_ANIM_DYN_SET_FOR_COLOR_NUMBER                        0
#define HMI_SET_P1_NUMBER                                        1
#define HMI_SET_P2_NUMBER                                        8
#define HMI_SET_P3_NUMBER                                        0
#define HMI_SET_BCK_COLOR_NUMBER                                 0
#define HMI_DXY_CUSTOM_CNT                                       5
#define HMI_SXY_CUSTOM_CNT                                       3
#define HMI_SET_ANGEL_NUMBER                                     5
#define HMI_SET_ANGEL_NO_ANIM_NUMBER                             0
#define HMI_ANIM_STATIC_SET_ANGEL_NUMBER                         5
#define HMI_ANIM_DYN_SET_ANGEL_NUMBER                            0
#define HMI_SET_ALPHA_NUMBER                                     3
#define HMI_SET_ALPHA_NO_ANIM_NUMBER                             0
#define HMI_ANIM_STATIC_SET_ALPHA_NUMBER                         3
#define HMI_ANIM_DYN_SET_ALPHA_NUMBER                            0
#define HMI_SET_SCALE_NUMBER                                     31
#define HMI_SET_SCALE_NO_ANIM_NUMBER                             0
#define HMI_ANIM_STATIC_SET_SCALE_NUMBER                         31
#define HMI_ANIM_DYN_SET_SCALE_NUMBER                            0
#define HMI_ALL_EVENT_NUMBER                                     0
#define HMI_ALL_ACTION_NUMBER                                    178
#define HMI_ANIM_NUMBER                                          66
#define HMI_LAYER_0_MAX_W_LENGTH                                 800
#define HMI_LAYER_0_MAX_H_LENGTH                                 480
#define HMI_LAYER_1_MAX_W_LENGTH                                 800
#define HMI_LAYER_1_MAX_H_LENGTH                                 480
#define HMI_MAX_WIDTH                                            (HMI_LAYER_1_MAX_W_LENGTH)
#define HMI_MAX_HEIGHT                                           (HMI_LAYER_1_MAX_H_LENGTH)
#define HMI_LAYER_0_HIGHEST_PRIORITY                             1
#define HMI_LAYER_1_HIGHEST_PRIORITY                             1
#define HMI_ALL_LAYERS_NUMBER                                    2
#define HMI_SCREEN0_ENABLE                                       1
#define HMI_SCREEN1_ENABLE                                       0
#define HMI_BIT_ORDER_LSB                                        1
#define HMI_SCROLL_TEXT_SUPPORT                                  (HMI_DYN_TEXT_SCROLL_NUMBER>0)
#define HMI_FRAME_PRE_SECOND                                     25
#define HMI_FONT_CODE                                            HMI_FONT_CODE_UNICODE
#define HMI_MCU_IMX6                                             
#define HMI_LINUX                                                 
#define HMI_TOOL_VERSION                                         3002
#define HMI_BTN_MAX_STATUS                                       0
#define HMI_IMGLIST_MAX_STATUS                                   10
#define HMI_SCROLLBAR_MAX_STATUS                                 0
#define HMI_JPG_BITMAPS_NUMBER                                   0
#define HMI_VIDEO_CAPTURE_ENABLE                                 0
#define HMI_EDIT_TEXT_DXY_DYN_FONT_NUM                           0
#define HMI_EDIT_TEXT_SXY_DYN_FONT_NUM                           0
#define HMI_UNEDIT_TEXT_DXY_DYN_FONT_NUM                         0
#define HMI_UNEDIT_TEXT_SXY_DYN_FONT_NUM                         0
#define HMI_GEN_ROM                                              1
#define HMI_EDIT_TEXT_MAX_SON_CNT                                0
#define HMI_UNEDIT_TEXT_MAX_SON_CNT                              0
#define HMI_DXY_IMAGE_MAX_SON_CNT                                0
#define HMI_SXY_IMAGE_MAX_SON_CNT                                0
#define HMI_DXY_IMAGE_LIST_MAX_SON_CNT                           0
#define HMI_SXY_IMAGE_LIST_MAX_SON_CNT                           0
#define HMI_DXY_BUTTON_MAX_SON_CNT                               0
#define HMI_SXY_BUTTON_MAX_SON_CNT                               0
#define HMI_DXY_SCROLLBAR_MAX_SON_CNT                            0
#define HMI_SXY_SCROLLBAR_MAX_SON_CNT                            0
#define HMI_DXY_FILL_MAX_SON_CNT                                 0
#define HMI_SXY_FILL_MAX_SON_CNT                                 0
#define HMI_SXY_SPLINE_MAX_SON_CNT                               0
#define HMI_DXY_SPLINE_MAX_SON_CNT                               0
#define HMI_SPRITE_MAX_CNT                                       30
#define HMI_TEXT_MAX_CNT                                         9
#define HMI_TEXT_CLIP_MAX_CNT                                    1
#define HMI_ENABLE_BIN                                           1
#define HMI_SEGMENT_MAX                                          2
#define HMI_MAX_SUB_TABLE_CNT                                    0
#define HMI_MAX_SINGLE_STAUS_CNT                                 0
#define HMI_MAX_SINGLE_ACT_STAUS_CNT                             0
#define HMI_MAX_SINGLE_NO_ACT_STAUS_CNT                          0
#define HMI_MAX_STATUS_EVENT_CNT                                 0
#define HMI_SXY_SPLINE_NUMBER                                    0
#define HMI_DXY_SPLINE_NUMBER                                    0
#define HMI_SXY_ONE_POINT_SPLINE_NUMBER                          0
#define HMI_DXY_ONE_POINT_SPLINE_NUMBER                          0
#define HMI_DXY_CUSTOM_WIDGET_LEN                                2
#define HMI_SXY_CUSTOM_WIDGET_LEN                                1
#define IMAGE_HEAD_INFO_ENABLE                                   0
#define HMI_SUPPORT_BIN_SHADER                                   0
#define HMI_FIXED_ELEMENT                                        0
#undef EXTERN
#endif
