#
# Makefile for the kernel bt drivers.
#

ccflags-y += -I$(srctree)/drivers/misc/atc/libosal/$(CONFIG_ATC_PLATFORM)/inc/
ccflags-y += -I$(srctree)/drivers/misc/atc/inc/

obj-$(CONFIG_ATC_BLUETOOTH) = btdrv.o 



