/*
* Copyright (c) 2016 AutoChips Inc.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 as
* published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
*/
/*
 *Department: ATC-SD-SD2
 *
 *Aurthor: yezhiqiang(atc0064)
 *
 *Date: 2017-03-10
 */
#ifndef _NR_HAL_H_
#define _NR_HAL_H_

#include "nr_drv.h"

#define NR_STRENGTH_OFF    0
#define NR_STRENGTH_LOW    1
#define NR_STRENGTH_MED    2
#define NR_STRENGTH_HIGH   3

#define ENABLE_3D 1

#define MODE_FRAME        0
#define MODE_FIELD        1
#define MODE_TOP_FIELD    2
#define MODE_BOT_FIELD    3

#define wReadNRQualityTable(wAddr)	 _bNRQtyTbl[wAddr]
typedef enum
{
    QUALITY_SNR_MESSSFT_SM_CO1MO,
    QUALITY_SNR_MESSTHL_SM_CO1MO,
    QUALITY_SNR_MESSSFT_MESS_CO1MO,
    QUALITY_SNR_MESSTHL_MESS_CO1MO,
    QUALITY_SNR_MESSSFT_EDGE_CO1MO,
    QUALITY_SNR_MESSTHL_EDGE_CO1MO,
    QUALITY_SNR_MESSSFT_MOS_CO1MO,
    QUALITY_SNR_MESSTHL_MOS_CO1MO,
    QUALITY_SNR_MESSSFT_SM_CO1ST,
    QUALITY_SNR_MESSTHL_SM_CO1ST,
    QUALITY_SNR_MESSSFT_MESS_CO1ST,
    QUALITY_SNR_MESSTHL_MESS_CO1ST,
    QUALITY_SNR_MESSSFT_EDGE_CO1ST,
    QUALITY_SNR_MESSTHL_EDGE_CO1ST,
    QUALITY_SNR_MESSSFT_MOS_CO1ST,
    QUALITY_SNR_MESSTHL_MOS_CO1ST,
    QUALITY_SNR_BLDLV_BK_CO1,
    QUALITY_SNR_BLDLV_SM_CO1,
    QUALITY_SNR_BLDLV_MESS_CO1,
    QUALITY_SNR_BLDLV_EDGE_CO1,
    QUALITY_SNR_BLDLV_MOS_CO1,
    QUALITY_SNR_MESSSFT_SM_CO2MO,
    QUALITY_SNR_MESSTHL_SM_CO2MO,
    QUALITY_SNR_MESSSFT_MESS_CO2MO,
    QUALITY_SNR_MESSTHL_MESS_CO2MO,
    QUALITY_SNR_MESSSFT_EDGE_CO2MO,
    QUALITY_SNR_MESSTHL_EDGE_CO2MO,
    QUALITY_SNR_MESSSFT_MOS_CO2MO,
    QUALITY_SNR_MESSTHL_MOS_CO2MO,
    QUALITY_SNR_MESSSFT_SM_CO2ST,
    QUALITY_SNR_MESSTHL_SM_CO2ST,
    QUALITY_SNR_MESSSFT_MESS_CO2ST,
    QUALITY_SNR_MESSTHL_MESS_CO2ST,
    QUALITY_SNR_MESSSFT_EDGE_CO2ST,
    QUALITY_SNR_MESSTHL_EDGE_CO2ST,
    QUALITY_SNR_MESSSFT_MOS_CO2ST,
    QUALITY_SNR_MESSTHL_MOS_CO2ST,
    QUALITY_SNR_BLDLV_BK_CO2,
    QUALITY_SNR_BLDLV_SM_CO2,
    QUALITY_SNR_BLDLV_MESS_CO2,
    QUALITY_SNR_BLDLV_EDGE_CO2,
    QUALITY_SNR_BLDLV_MOS_CO2,
    QUALITY_SNR_MESSSFT_SM_CO3MO,
    QUALITY_SNR_MESSTHL_SM_CO3MO,
    QUALITY_SNR_MESSSFT_MESS_CO3MO,
    QUALITY_SNR_MESSTHL_MESS_CO3MO,
    QUALITY_SNR_MESSSFT_EDGE_CO3MO,
    QUALITY_SNR_MESSTHL_EDGE_CO3MO,
    QUALITY_SNR_MESSSFT_MOS_CO3MO,
    QUALITY_SNR_MESSTHL_MOS_CO3MO,
    QUALITY_SNR_MESSSFT_SM_CO3ST,
    QUALITY_SNR_MESSTHL_SM_CO3ST,
    QUALITY_SNR_MESSSFT_MESS_CO3ST,
    QUALITY_SNR_MESSTHL_MESS_CO3ST,
    QUALITY_SNR_MESSSFT_EDGE_CO3ST,
    QUALITY_SNR_MESSTHL_EDGE_CO3ST,
    QUALITY_SNR_MESSSFT_MOS_CO3ST,
    QUALITY_SNR_MESSTHL_MOS_CO3ST,
    QUALITY_SNR_BLDLV_BK_CO3,
    QUALITY_SNR_BLDLV_SM_CO3,
    QUALITY_SNR_BLDLV_MESS_CO3,
    QUALITY_SNR_BLDLV_EDGE_CO3,
    QUALITY_SNR_BLDLV_MOS_CO3,
    QUALITY_SNR_MESSSFT_SM_FRST,
    QUALITY_SNR_MESSTHL_SM_FRST,
    QUALITY_SNR_MESSSFT_MESS_FRST,
    QUALITY_SNR_MESSTHL_MESS_FRST,
    QUALITY_SNR_MESSSFT_EDGE_FRST,
    QUALITY_SNR_MESSTHL_EDGE_FRST,
    QUALITY_SNR_MESSSFT_MOS_FRST,
    QUALITY_SNR_MESSTHL_MOS_FRST,
    QUALITY_SNR_BLDLV_BK_FRST,
    QUALITY_SNR_BLDLV_SM_FRST,
    QUALITY_SNR_BLDLV_MESS_FRST,
    QUALITY_SNR_BLDLV_EDGE_FRST,
    QUALITY_SNR_BLDLV_MOS_FRST,
    QUALITY_SNR_MESSSFT_SM_MO,
    QUALITY_SNR_MESSTHL_SM_MO,
    QUALITY_SNR_MESSSFT_MESS_MO,
    QUALITY_SNR_MESSTHL_MESS_MO,
    QUALITY_SNR_MESSSFT_EDGE_MO,
    QUALITY_SNR_MESSTHL_EDGE_MO,
    QUALITY_SNR_MESSSFT_MOS_MO,
    QUALITY_SNR_MESSTHL_MOS_MO,
    QUALITY_SNR_BLDLV_BK_MO,
    QUALITY_SNR_BLDLV_SM_MO,
    QUALITY_SNR_BLDLV_MESS_MO,
    QUALITY_SNR_BLDLV_EDGE_MO,
    QUALITY_SNR_BLDLV_MOS_MO,
    QUALITY_SNR_MESSSFT_SM_ST,
    QUALITY_SNR_MESSTHL_SM_ST,
    QUALITY_SNR_MESSSFT_MESS_ST,
    QUALITY_SNR_MESSTHL_MESS_ST,
    QUALITY_SNR_MESSSFT_EDGE_ST,
    QUALITY_SNR_MESSTHL_EDGE_ST,
    QUALITY_SNR_MESSSFT_MOS_ST,
    QUALITY_SNR_MESSTHL_MOS_ST,
    QUALITY_SNR_BLDLV_BK_ST,
    QUALITY_SNR_BLDLV_SM_ST,
    QUALITY_SNR_BLDLV_MESS_ST,
    QUALITY_SNR_BLDLV_EDGE_ST,
    QUALITY_SNR_BLDLV_MOS_ST,
    QUALITY_SNR_MESSSFT_SM_BK,
    QUALITY_SNR_MESSTHL_SM_BK,
    QUALITY_SNR_MESSSFT_MESS_BK,
    QUALITY_SNR_MESSTHL_MESS_BK,
    QUALITY_SNR_MESSSFT_EDGE_BK,
    QUALITY_SNR_MESSTHL_EDGE_BK,
    QUALITY_SNR_MESSSFT_MOS_BK,
    QUALITY_SNR_MESSTHL_MOS_BK,
    QUALITY_SNR_BLDLV_BK_BK,
    QUALITY_SNR_BLDLV_SM_BK,
    QUALITY_SNR_BLDLV_MESS_BK,
    QUALITY_SNR_BLDLV_EDGE_BK,
    QUALITY_SNR_BLDLV_MOS_BK,
    QUALITY_SNR_MESSSFT_SM_DEF,
    QUALITY_SNR_MESSTHL_SM_DEF,
    QUALITY_SNR_MESSSFT_MESS_DEF,
    QUALITY_SNR_MESSTHL_MESS_DEF,
    QUALITY_SNR_MESSSFT_EDGE_DEF,
    QUALITY_SNR_MESSTHL_EDGE_DEF,
    QUALITY_SNR_MESSSFT_MOS_DEF,
    QUALITY_SNR_MESSTHL_MOS_DEF,
    QUALITY_SNR_BLDLV_SM_DEF,
    QUALITY_SNR_BLDLV_MESS_DEF,
    QUALITY_SNR_BLDLV_EDGE_DEF,
    QUALITY_SNR_BLDLV_MOS_DEF,
    QUALITY_SNR_CUR_SM_NUM,
    QUALITY_SNR_CUR_SM_THR,
    QUALITY_SNR_NEAREDGE_SELWIDTH,
    QUALITY_SNR_NEAREDGE_EDGE_THR,
    QUALITY_SNR_GLOBAL_BLEND,
    QUALITY_TNR_REG_TBTHX1,
    QUALITY_TNR_REG_TBTHX2,
    QUALITY_TNR_REG_TBTHX3,
    QUALITY_TNR_REG_TBTHX4,
    QUALITY_TNR_REG_TBTHX5,
    QUALITY_TNR_REG_TBTHX6,
    QUALITY_TNR_REG_TBTHX7,
    QUALITY_TNR_REG_TBTHX8,
    QUALITY_TNR_DEF_TBL0,
    QUALITY_TNR_DEF_TBL1,
    QUALITY_TNR_DEF_TBL2,
    QUALITY_TNR_DEF_TBL3,
    QUALITY_TNR_DEF_TBL4,
    QUALITY_TNR_DEF_TBL5,
    QUALITY_TNR_DEF_TBL6,
    QUALITY_TNR_DEF_TBL7,
    QUALITY_TNR_CIIR_TBL0,
    QUALITY_TNR_CIIR_TBL1,
    QUALITY_TNR_CIIR_TBL2,
    QUALITY_TNR_CIIR_TBL3,
    QUALITY_TNR_CIIR_TBL4,
    QUALITY_TNR_CIIR_TBL5,
    QUALITY_TNR_CIIR_TBL6,
    QUALITY_TNR_CIIR_TBL7,
    QUALITY_NR_MAX
} NR_QUALITY_ITEM_T;

void _NrHwReset(void);
void _NrSetClk(unsigned int u4ClkSrc);
void _NrCloseClk(void);
void _NrParaInit(void);
void _NrParaSet(unsigned int u4Strength, unsigned int u4FNRStrength,
					unsigned int u4MNRStrength, unsigned int u4BNRStrength);
void _NrSetParam(NR_PRM_T * ptNrPrm);
void _NrSetBufTrigger(NR_BUFFER_T * ptNrBuf);
void _NrClearInterrupteStatus(void);
void _NrBypass(unsigned int fgBypass);
void _NrEnable3dFunc(unsigned int fgBypass);
void _NrSetSwapMode(unsigned int swapMode);
void _NrLevelSet(unsigned int u4Strength, unsigned int u4FNRStrength,
					unsigned int u4MNRStrength, unsigned int u4BNRStrength);


#endif
