/* Copyright Statement:
 *
 * This software/firmware and related documentation ("AutoChips Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to AutoChips Inc. and/or its licensors. Without
 * the prior written permission of AutoChips inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of AutoChips Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * AutoChips Inc. (C) 2016. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AUTOCHIPS SOFTWARE")
 * RECEIVED FROM AUTOCHIPS AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. AUTOCHIPS EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES AUTOCHIPS PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE AUTOCHIPS SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN AUTOCHIPS
 * SOFTWARE. AUTOCHIPS SHALL ALSO NOT BE RESPONSIBLE FOR ANY AUTOCHIPS SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AUTOCHIPS'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE AUTOCHIPS SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT AUTOCHIPS'S OPTION, TO REVISE OR REPLACE THE
 * AUTOCHIPS SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO AUTOCHIPS FOR SUCH AUTOCHIPS SOFTWARE AT ISSUE.
 */
#ifndef _BOOT_CFG_H_
#define _BOOT_CFG_H_

#include "x_typedef.h"

/* define */
#define BOOT_CFG_HEAD_SIG 0x706c6472
#define BOOT_CFG_END_SIG 0x62636667

/* struct */
typedef struct _boot_cfg
{
	UINT32 u4HeadSig;
	UINT32 u4AcOnStby;
	UINT32 u4FastLogo;
	UINT32 u4DisableArm2;
	UINT32 u4Avm;
	UINT32 u4SecureCheck;
	UINT32 u4CustSet;
	UINT32 u4ICEswitch;
	UINT32 u4EndSig;
} BOOT_CFG;

typedef enum
{
    BCFG_OFST_HeadSig		= 0x00,
    BCFG_OFST_AcOnStby		= 0x04,
    BCFG_OFST_FastLogo		= 0x08,
    BCFG_OFST_DisableArm2	= 0x0C,
    BCFG_OFST_Avm 			= 0x10,
    BCFG_OFST_SecureCheck	= 0x14,
    BCFG_OFST_CustSet		= 0x18,    
    BCFG_OFST_ICEswitch		= 0x1C,
    BCFG_OFST_EndSig		= 0x20,
}BOOT_CFG_OFFSET;

/* public variables */
extern BOOT_CFG r_boot_cfg;

/* public functions */
extern int i_boot_cfg_init(void);


#endif //_BOOT_CFG_H_


