/* Copyright Statement:
 *
 * This software/firmware and related documentation ("AutoChips Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to AutoChips Inc. and/or its licensors. Without
 * the prior written permission of AutoChips inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of AutoChips Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * AutoChips Inc. (C) 2016. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AUTOCHIPS SOFTWARE")
 * RECEIVED FROM AUTOCHIPS AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. AUTOCHIPS EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES AUTOCHIPS PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE AUTOCHIPS SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN AUTOCHIPS
 * SOFTWARE. AUTOCHIPS SHALL ALSO NOT BE RESPONSIBLE FOR ANY AUTOCHIPS SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AUTOCHIPS'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE AUTOCHIPS SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT AUTOCHIPS'S OPTION, TO REVISE OR REPLACE THE
 * AUTOCHIPS SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO AUTOCHIPS FOR SUCH AUTOCHIPS SOFTWARE AT ISSUE.
 */

#ifndef DUAL_CALLBACK_H
#define DUAL_CALLBACK_H

#include "x_typedef.h"

// #include "drv_dual.h"

//============================================================================
// Type definitions
//============================================================================
typedef void (*DUAL_CALLBACK)(UINT32 u4MoudleID, 
                              UINT32 u4P1, 
                              UINT32 u4P2, 
                              UINT32 u4P3);

typedef struct
{
  UINT32 u4MoudleID;
  DUAL_CALLBACK pDualCallBack;
} DUAL_ISR_CALLBACK_T;

#define INVALID_MESSAGE   (0)
#define ARM1TOARM2        (1)
#define ARM2TOARM1        (2)

#define MODULEIDMASK      (0xFF000000)
#define MODULEIDSHIFT     (24)

#define MESSAGEDIRMASK    (0x00FF0000)  //reserver
#define MESSAGEDIRSHIFT   (16)

#define MESSAGEIDMASK     (0x0000FFFF)

#define GETMODULEID(m)    ((m & MODULEIDMASK) >> MODULEIDSHIFT)
#define GETMESSAGEDIR(m)  ((m & MESSAGEDIRMASK) >> MESSAGEDIRSHIFT)
#define GETMESSAGEID(m)   (m & MESSAGEIDMASK)

#define DUAL_MAX_TASK        2

//EXTERN void vDualIsr(void);
EXTERN BOOL fgDualCallBackInit(void);

EXTERN BOOL fgRegisterCallBack(UINT32 u4MoudleID, void (*DUAL_CALLBACK)(UINT32 u4MoudleID, UINT32 u4P1, UINT32 u4P2, UINT32 u4P3));
EXTERN BOOL fgReleaseCallBack(UINT32 u4MoudleID);

#endif	// DUAL_CALLBACK_H
