/* Copyright Statement:
 *
 * This software/firmware and related documentation ("AutoChips Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to AutoChips Inc. and/or its licensors. Without
 * the prior written permission of AutoChips inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of AutoChips Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 * 
 * AutoChips Inc. (C) 2016. All rights reserved.
 * 
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("AUTOCHIPS SOFTWARE")
 * RECEIVED FROM AUTOCHIPS AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. AUTOCHIPS EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES AUTOCHIPS PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE AUTOCHIPS SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN AUTOCHIPS
 * SOFTWARE. AUTOCHIPS SHALL ALSO NOT BE RESPONSIBLE FOR ANY AUTOCHIPS SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AUTOCHIPS'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE AUTOCHIPS SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT AUTOCHIPS'S OPTION, TO REVISE OR REPLACE THE
 * AUTOCHIPS SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO AUTOCHIPS FOR SUCH AUTOCHIPS SOFTWARE AT ISSUE.
 */

#ifndef _LOADER_H_
#define _LOADER_H_

#include "x_typedef.h"
#include "secure_info_tbl.h"

#define UBOOT_ADDR		0x80100000


#define U_BOOT_SEARCH_LIMIT 0x00800000 /* 8M */
#define U_BOOT_SEARCH_INTERVAL 0x200  /* 4K */

/*
 * error code
 */
#define LD_OK 0
#define LD_FIND_U_BOOT_ERR 0x1d000001


/*
 * u-boot binary info
 */
typedef struct _bin_info
{
    UINT32 u4_str_sig;
    UINT32 u4_text_base;
    UINT32 u4_armboot_start;
    UINT32 u4_bss_base;
    UINT32 u4_bss_end;
    UINT32 u4_end_sig;
    UINT32 u4_sit_bin_size;
    CHAR   pc_fw_inte_sig[SIGNATURE_SIZE];
}BIN_INFO;

#define BIN_INFO_OFFSET  0x40
#define BI_U_STR_SIG     0x9B10ADE4
#define BI_U_END_SIG     0x4EDA01B9
typedef enum
{
    BI_OFST_U_STR_SIG   = BIN_INFO_OFFSET + 0x00,
    BI_OFST_U_TEXT_BASE = BIN_INFO_OFFSET + 0x04,
    BI_OFST_U_ARMBOOT   = BIN_INFO_OFFSET + 0x08,
    BI_OFST_U_BSS_BASE  = BIN_INFO_OFFSET + 0x0c,
    BI_OFST_U_BSS_END   = BIN_INFO_OFFSET + 0x10,
    BI_OFST_U_END_SIG   = BIN_INFO_OFFSET + 0x14,
}BIN_OFFSET;

/*
 * func
 */
typedef void (*FUNC_CALL)(void);

#endif //_LOADER_H_


