obj-y				+= drv_util_log.o
obj-y				+= ko_assert.o
obj-y				+= ko_printf.o

ccflags-y += -I$(srctree)/drivers/misc/atc/inc
ccflags-y += -I$(srctree)/drivers/misc/atc/private_inc
ccflags-y += -I$(srctree)/drivers/misc/atc/libosal/ac823x/inc