ctrl_interface=/var/run/wpa_supplicant/
driver_param=use_p2p_group_interface=1
update_config=1
uuid=12345678-9abc-def0-1234-56789abcdef0
device_name=Android_f094
manufacturer=MediaTek Inc.
model_name=MTK Wireless Model
model_number=1.0
serial_number=1.0
device_type=8-0050F204-2
os_version=01020300
config_methods=virtual_push_button physical_display keypad
p2p_ssid_postfix=-Android_f094
persistent_reconnect=1
p2p_group_idle=10
