# SPDX-License-Identifier: GPL-2.0
include $(srctree)/$(src)/atc_wlan_definitions.mk
obj-y += dummy.o
obj-$(CONFIG_ATC_COMBO) += atc_combo/
obj-$(CONFIG_ATC_WIFI_CHIP_MT6630_SDIO) += mt6630/
#obj-$(CONFIG_ATC_WIFI_CHIP_CYPRESS_PCIE) += cypress/
#obj-$(CONFIG_ATC_WIFI_CHIP_CYPRESS_SDIO) += cypress/
