obj-$(CONFIG_ARCH_AC823x) += thermal.o

ccflags-y := -Idrivers/misc/atc/libosai/ac823x/inc -Idrivers/misc/atc/inc -Idrivers/misc/atc/private_inc 
ccflags-$(CONFIG_ARM64) += -Idrivers/misc/atc/include
