#ifndef _IOCTL_IMGDEC_H
#define _IOCTL_IMGDEC_H

//#include <windows.h>
#include <windev.h>
#include "x_gfx.h"
#include "x_img_dec.h"
#include "x_img_gif_dec.h"
#include "x_jpg_hdr.h"

#define    FILE_DEVICE_JPG 0x00008801
#define    IOCTL_DRV_JPG_DEC_PREPARE               CTL_CODE(FILE_DEVICE_JPG, 0x0101, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_CLEAR                 CTL_CODE(FILE_DEVICE_JPG, 0x0102, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_SET_PARAM             CTL_CODE(FILE_DEVICE_JPG, 0x0103, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_PARSE_HDR             CTL_CODE(FILE_DEVICE_JPG, 0x0104, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_DO_DECODE             CTL_CODE(FILE_DEVICE_JPG, 0x0105, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_STOP_DEC              CTL_CODE(FILE_DEVICE_JPG, 0x0106, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_BUF_FILLED            CTL_CODE(FILE_DEVICE_JPG, 0x0107, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_GET_FINISH_STATE      CTL_CODE(FILE_DEVICE_JPG, 0x0108, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_GET_SRC_BUF           CTL_CODE(FILE_DEVICE_JPG, 0x0109, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_GET_DST_BUF           CTL_CODE(FILE_DEVICE_JPG, 0x010A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_GET_PICINFO_BUF       CTL_CODE(FILE_DEVICE_JPG, 0x010B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_GET_NFY_BUF           CTL_CODE(FILE_DEVICE_JPG, 0x010C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_GET_DST_YCBUF         CTL_CODE(FILE_DEVICE_JPG, 0x010D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_JPG_DEC_WAIT_DEC_DONE         CTL_CODE(FILE_DEVICE_JPG, 0x010E, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define    FILE_DEVICE_GIF 0x0000BB01
#define    IOCTL_DRV_GIF_DEC_PREPARE               CTL_CODE(FILE_DEVICE_GIF, 0x0101, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_CLEAR                 CTL_CODE(FILE_DEVICE_GIF, 0x0102, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_SET_PARAM             CTL_CODE(FILE_DEVICE_GIF, 0x0103, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_PARSE_HDR             CTL_CODE(FILE_DEVICE_GIF, 0x0104, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_DO_DECODE             CTL_CODE(FILE_DEVICE_GIF, 0x0105, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_STOP_DEC              CTL_CODE(FILE_DEVICE_GIF, 0x0106, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_BUF_FILLED            CTL_CODE(FILE_DEVICE_GIF, 0x0107, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_GET_FINISH_STATE      CTL_CODE(FILE_DEVICE_GIF, 0x0108, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_GET_SRC_BUF           CTL_CODE(FILE_DEVICE_GIF, 0x0109, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_GET_DST_BUF           CTL_CODE(FILE_DEVICE_GIF, 0x010A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_GET_PICINFO_BUF       CTL_CODE(FILE_DEVICE_GIF, 0x010B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_GIF_DEC_GET_NOTIFY_BUF        CTL_CODE(FILE_DEVICE_GIF, 0x010C, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define    FILE_DEVICE_PNG 0x0000DD01
#define    IOCTL_DRV_PNG_DEC_PREPARE               CTL_CODE(FILE_DEVICE_PNG, 0x0101, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_CLEAR                 CTL_CODE(FILE_DEVICE_PNG, 0x0102, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_SET_PARAM             CTL_CODE(FILE_DEVICE_PNG, 0x0103, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_PARSE_HDR             CTL_CODE(FILE_DEVICE_PNG, 0x0104, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_DO_DECODE             CTL_CODE(FILE_DEVICE_PNG, 0x0105, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_STOP_DEC              CTL_CODE(FILE_DEVICE_PNG, 0x0106, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_BUF_FILLED            CTL_CODE(FILE_DEVICE_PNG, 0x0107, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_GET_FINISH_STATE      CTL_CODE(FILE_DEVICE_PNG, 0x0108, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_GET_SRC_BUF           CTL_CODE(FILE_DEVICE_PNG, 0x0109, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_GET_DST_BUF           CTL_CODE(FILE_DEVICE_PNG, 0x010A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_GET_PICINFO_BUF       CTL_CODE(FILE_DEVICE_PNG, 0x010B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#ifdef __linux__
#define    IOCTL_DRV_PNG_DEC_GET_NOTIFY_BUF        CTL_CODE(FILE_DEVICE_PNG, 0x010C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define    IOCTL_DRV_PNG_DEC_GET_NPTC_BUF          CTL_CODE(FILE_DEVICE_PNG, 0x010D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

typedef enum _IMG_MW_EVT_ID_T
{
    IMG_MW_EVT_DEC_FINISH = 0,
    IMG_MW_EVT_TO_FILL_BUF = 1,
    IMG_MW_EVT_DRV_EVT_MAX = 2,
    IMG_MW_EVT_JUMP_DATA = IMG_MW_EVT_DRV_EVT_MAX,
    IMG_MW_EVT_BUF_FILLED,
    IMG_MW_EVT_ID_MAX,
} IMG_MW_EVT_ID_T;

typedef IMG_DEC_PREPARE_T IMG_MW_PREPARE_INFO_T;
typedef IMG_DEC_PARAM_T   IMG_MW_DEC_PARAM_INFO_T;

typedef IMG_DECODE_T IMG_MW_DECODE_INFO_T;
typedef IMG_GIF_DECODE_T IMG_MW_GIF_DECODE_INFO_T;
typedef IMG_BUF_FILLED_T IMG_MW_BUF_FILLED_INFO_T;
typedef IMG_GIF_BUF_FILLED_T IMG_MW_GIF_BUF_FILLED_INFO_T;

typedef struct _IMG_MW_BUF_INFO_T
{
    void   *pvVirAddr;
    __u64 u4BufPhyAdr;
    __u32 u4BufSz;
    bool   fgSelfAlloc;
} IMG_MW_BUF_INFO_T;

typedef struct _IMG_MW_YCBUF_INFO_T
{
    IMG_BUF_T ImgMwYBuf;
	IMG_BUF_T ImgMwCBuf;
	
} IMG_MW_YCBUF_INFO_T;

typedef struct
{
    uintptr_t u4UserAddr;
    uintptr_t u4NptcAddr;
    __u32 u4BufSz;
}IMG_MW_NPTC_BUF_T;
   
typedef struct _IMG_MW_DEC_FINISH_INFO_T
{
    IMG_DEC_FINISH_STATE_T eState;
} IMG_MW_DEC_FINISH_INFO_T;

#endif //_IOCTL_IMGDEC_H
