/*
* Copyright (c) 2016 AutoChips Inc.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 as
* published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
*/
#ifndef _X_PLANE_MXR_H_
#define _X_PLANE_MXR_H_


/*-----------------------------------------------------------------------------
                    include files
-----------------------------------------------------------------------------*/


/*-----------------------------------------------------------------------------
                    macros, defines, typedefs, enums
 ----------------------------------------------------------------------------*/

/* Get operations */
#define PLA_MXR_GET_TYPE_CTRL               (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 0))
#define PLA_MXR_GET_TYPE_BRIGHTNESS         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 1))
#define PLA_MXR_GET_TYPE_CONTRAST           (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 2))
#define PLA_MXR_GET_TYPE_HUE                (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 3))
#define PLA_MXR_GET_TYPE_SATURATION         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 4))
#define PLA_MXR_GET_TYPE_MAX_GAMMA_CURVE    (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 5))
#define PLA_MXR_GET_TYPE_GAMMA              (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 6))
#define PLA_MXR_GET_TYPE_ADJ_PLA_BY_PORT    (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 7))
#define PLA_MXR_GET_TYPE_ADJ_PLA_BY_ID_TYPE (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 8))
#define PLA_MXR_GET_TYPE_PLA_ORDER          (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 9))
#define PLA_MXR_GET_TYPE_CAPABILITY         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)10))
#define PLA_MXR_GET_TYPE_RESOLUTION         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)11))
#define PLA_MXR_GET_TYPE_OUTPUT_PORT        (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)13))
#define PLA_MXR_GET_TYPE_BG                 (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)14))
#define PLA_MXR_GET_TYPE_ASPECT_RATIO       (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)15))
#define PLA_MXR_GET_TYPE_DIGITAL_OUTPUT_FMT (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)16))
#define PLA_MXR_GET_TYPE_DITHER             (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)17))
#define PLA_MXR_GET_TYPE_DITHER_CAP         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)18))
#define PLA_MXR_GET_TYPE_MIN_MAX            (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)19))
#define PLA_MXR_GET_TYPE_COLOR_GAIN         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)20))
#define PLA_MXR_GET_TYPE_COLOR_GAIN_MAX     (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)21))
#define PLA_MXR_GET_TYPE_COLOR_GAIN_MIN     (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)22))
#define PLA_MXR_GET_TYPE_COLOR_OFFSET       (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)23))
#define PLA_MXR_GET_TYPE_COLOR_OFFSET_MAX   (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)24))
#define PLA_MXR_GET_TYPE_COLOR_OFFSET_MIN   (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)25))
#define PLA_MXR_GET_TYPE_BACK_LIGHT         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)26))
#define PLA_MXR_GET_TYPE_ADP_BACK_LIGHT     (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)27))
#define PLA_MXR_GET_TYPE_TV_MODE            (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)28))
#define PLA_MXR_GET_TYPE_MJC                (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)29))
#define PLA_MXR_GET_TYPE_TEST_PATTERN       (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)30))
#define PLA_MXR_GET_TYPE_HDMI_DEEP_COLOR    (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)31))
#define PLA_MXR_GET_TYPE_SHARPNESS          (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)32))
#define PLA_MXR_GET_TYPE_HDCP_ON_OFF        (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)33))
#define PLA_MXR_GET_TYPE_CLOSED_CAPTION_ON_OFF   (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)34))
#define PLA_MXR_GET_TYPE_EXTERNAL_CHIP_SETTING   (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)35))
#define PLA_MXR_GET_TYPE_COLOR_BAR               (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T)36))
#define PLA_MXR_GET_TYPE_MUTE               (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 37))
#define PLA_MXR_GET_TYPE_BLACK_LV           (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 38))
#define PLA_MXR_GET_TYPE_PLANE_SWAP         (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 39))
#define PLA_MXR_GET_TYPE_FORCE_CGMS		   (RM_GET_TYPE_LAST_ENTRY + ((DRV_GET_TYPE_T) 40))

/* Set operations */
#define PLA_MXR_SET_TYPE_CTRL              ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 0)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_BRIGHTNESS        ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 1)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_CONTRAST          ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 2)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_HUE               ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 3)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_SATURATION        ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 4)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_GAMMA             ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 5)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_PLA_ORDER          (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 6))
#define PLA_MXR_SET_TYPE_RESOLUTION         (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 7))
#define PLA_MXR_SET_TYPE_OUTPUT_PORT       ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 8)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_BG                 (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 9))
#define PLA_MXR_SET_TYPE_ASPECT_RATIO      ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)10)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_DIGITAL_OUTPUT_FMT ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)11)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_DITHER             (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)12))
#define PLA_MXR_SET_TYPE_COLOR_GAIN         (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)13))
#define PLA_MXR_SET_TYPE_COLOR_OFFSET       (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)14))
#define PLA_MXR_SET_TYPE_BACK_LIGHT         (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)15))
#define PLA_MXR_SET_TYPE_ADP_BACK_LIGHT     (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)16))
#define PLA_MXR_SET_TYPE_TV_MODE            (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)17))
#define PLA_MXR_SET_TYPE_MJC                (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)18))
#define PLA_MXR_SET_TYPE_TEST_PATTERN       (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)19))
#define PLA_MXR_SET_TYPE_HDMI_DEEP_COLOR   ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)20)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_SHARPNESS         ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)21)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_HDCP_ON_OFF       ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)22)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_CLOSED_CAPTION_ON_OFF ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)23)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_RESOLUTION_EX      (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)24))
#define PLA_MXR_SET_TYPE_ASPECT_RATIO_EX    (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)25))
#define PLA_MXR_SET_TYPE_EXTERNAL_CHIP_SETTING (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)26))
#define PLA_MXR_SET_TYPE_COLOR_BAR         ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 27)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_MUTE              ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 28)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_BLACK_LV           (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 29))
#define PLA_MXR_SET_TYPE_PLANE_SWAP         (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 30))
#if (1 == RM_LIGHT_SUPPORT)
#define PLA_MXR_SET_TYPE_CONNECT            (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 31))
#define PLA_MXR_SET_TYPE_DISCONNECT         (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 32))
#define PLA_MXR_SET_TYPE_OP_NFY_FCT         (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 33))
#endif
#define PLA_MXR_SET_TYPE_ORDER_VDP_COMP0   ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 34)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_FORCE_CGMS		   ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 35)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_MEDIA              ((RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T) 36)) | RM_SET_TYPE_ARG_NO_REF)
#define PLA_MXR_SET_TYPE_DIGEST_ASPECT_RATIO_EX    (RM_SET_TYPE_LAST_ENTRY + ((DRV_SET_TYPE_T)37))


/* Dither Capability types */
#define PLA_MXR_DITHER_CAP_NONE       ((UINT32) 0)
#define PLA_MXR_DITHER_CAP_1_BIT      MAKE_BIT_MASK_16(0)
#define PLA_MXR_DITHER_CAP_2_BITS     MAKE_BIT_MASK_16(1)
#define PLA_MXR_DITHER_CAP_3_BITS     MAKE_BIT_MASK_16(2)
#define PLA_MXR_DITHER_CAP_4_BITS     MAKE_BIT_MASK_16(3)
#define PLA_MXR_DITHER_CAP_5_BITS     MAKE_BIT_MASK_16(4)
#define PLA_MXR_DITHER_CAP_6_BITS     MAKE_BIT_MASK_16(5)
#define PLA_MXR_DITHER_CAP_7_BITS     MAKE_BIT_MASK_16(6)
#define PLA_MXR_DITHER_CAP_8_BITS     MAKE_BIT_MASK_16(7)
#define PLA_MXR_DITHER_CAP_9_BITS     MAKE_BIT_MASK_16(8)
#define PLA_MXR_DITHER_CAP_10_BITS    MAKE_BIT_MASK_16(9)
#define PLA_MXR_DITHER_CAP_11_BITS    MAKE_BIT_MASK_16(10)
#define PLA_MXR_DITHER_CAP_12_BITS    MAKE_BIT_MASK_16(11)
#define PLA_MXR_DITHER_CAP_13_BITS    MAKE_BIT_MASK_16(12)
#define PLA_MXR_DITHER_CAP_14_BITS    MAKE_BIT_MASK_16(13)
#define PLA_MXR_DITHER_CAP_15_BITS    MAKE_BIT_MASK_16(14)
#define PLA_MXR_DITHER_CAP_16_BITS    MAKE_BIT_MASK_16(15)


/* PLA_MXR_GET_TYPE_CTRL/PLA_MXR_SET_TYPE_CTRL data info *********************/
typedef enum
{
    PLA_MXR_CTRL_RESET = 0,
    PLA_MXR_CTRL_DISABLE,
    PLA_MXR_CTRL_ENABLE
}   PLA_MXR_CTRL_T;

/* PLA_MXR_GET_TYPE_COLOR_BAR/PLA_MXR_SET_TYPE_COLOR_BAR data info *********************/
typedef enum
{
    PLA_MXR_CB_RESERVE = 0,
    PLA_MXR_CB_DISABLE,
    PLA_MXR_CB_ENABLE
}   PLA_MXR_CB_T;

/* PLA_MXR_GET_TYPE_MUTE/PLA_MXR_SET_TYPE_MUTE data info *********************/
typedef enum
{
    PLA_MXR_MUTE_RESERVE = 0,
    PLA_MXR_MUTE_DISABLE,
    PLA_MXR_MUTE_ENABLE
}   PLA_MXR_MUTE_T;

/* PLA_MXR_GET_TYPE_FORCE_CGMS/PLA_MXR_SET_TYPE_FORCE_CGMS data info *********************/
typedef enum
{
    PLA_MXR_FORCE_CGMS_RESERVE = 0,
    PLA_MXR_FORCE_CGMS_DISABLE,
    PLA_MXR_FORCE_CGMS_ENABLE
}   PLA_MXR_FORCE_CGMS_T;

/* PLA_MXR_GET_TYPE_BLACK_LV/PLA_MXR_SET_TYPE_BLACK_LV data info *********************/
typedef enum
{
    PLA_MXR_BLACK_LV_NORMAL = 0,
    PLA_MXR_BLACK_LV_ENHANCE
}   PLA_MXR_BLACK_LV_OPT_T;

typedef struct _PLA_MXR_BLACK_LV_T
{
    PLA_MXR_BLACK_LV_OPT_T eCAVOpt;
    PLA_MXR_BLACK_LV_OPT_T eCVBSOpt;
}   PLA_MXR_BLACK_LV_T;

typedef enum
{
    PLA_MXR_SWAP_DISABLE = 0,
    PLA_MXR_SWAP_ENABLE
}   PLA_MXR_SWAP_T;

typedef enum
{
    PLA_MXR_PLANE_SWAP1_2 = 0,
    PLA_MXR_PLANE_SWAP3_4,
    PLA_MXR_PLANE_SWAP6_7,
    PLA_MXR_PLANE_SWAP4_7,
    PLA_MXR_PLANE_SWAP1_3,
    PLA_MXR_PLANE_SWAP5_8
}   PLA_MXR_PLANE_T;

typedef struct _PLA_MXR_PLANE_ORDER_T
{
    PLA_MXR_PLANE_T ePlane;
    PLA_MXR_SWAP_T eSwap;
}   PLA_MXR_PLANE_ORDER_T;

/* Availiabe z-orders ********************************************************/
#define PLA_MXR_Z_ORDER_UNKNOWN  ((UINT32) 0xFFFFFFFF)
#define PLA_MXR_Z_ORDER_0        ((UINT32) 0)
#define PLA_MXR_Z_ORDER_1        ((UINT32) 1)
#define PLA_MXR_Z_ORDER_2        ((UINT32) 2)
#define PLA_MXR_Z_ORDER_3        ((UINT32) 3)
#define PLA_MXR_Z_ORDER_4        ((UINT32) 4)
#define PLA_MXR_Z_ORDER_5        ((UINT32) 5)
#define PLA_MXR_Z_ORDER_6        ((UINT32) 6)
#define PLA_MXR_Z_ORDER_7        ((UINT32) 7)
#define PLA_MXR_Z_ORDER_8        ((UINT32) 8)
#define PLA_MXR_Z_ORDER_9        ((UINT32) 9)
#define PLA_MXR_Z_ORDER_10       ((UINT32)10)
#define PLA_MXR_Z_ORDER_11       ((UINT32)11)
#define PLA_MXR_Z_ORDER_12       ((UINT32)12)
#define PLA_MXR_Z_ORDER_13       ((UINT32)13)
#define PLA_MXR_Z_ORDER_14       ((UINT32)14)
#define PLA_MXR_Z_ORDER_15       ((UINT32)15)
#define PLA_MXR_Z_ORDER_16       ((UINT32)16)
#define PLA_MXR_Z_ORDER_17       ((UINT32)17)
#define PLA_MXR_Z_ORDER_18       ((UINT32)18)
#define PLA_MXR_Z_ORDER_19       ((UINT32)19)
#define PLA_MXR_Z_ORDER_20       ((UINT32)20)
#define PLA_MXR_Z_ORDER_21       ((UINT32)21)
#define PLA_MXR_Z_ORDER_22       ((UINT32)22)
#define PLA_MXR_Z_ORDER_23       ((UINT32)23)
#define PLA_MXR_Z_ORDER_24       ((UINT32)24)
#define PLA_MXR_Z_ORDER_25       ((UINT32)25)
#define PLA_MXR_Z_ORDER_26       ((UINT32)26)
#define PLA_MXR_Z_ORDER_27       ((UINT32)27)
#define PLA_MXR_Z_ORDER_28       ((UINT32)28)
#define PLA_MXR_Z_ORDER_29       ((UINT32)29)
#define PLA_MXR_Z_ORDER_30       ((UINT32)30)
#define PLA_MXR_Z_ORDER_31       ((UINT32)31)

/* bit mask of adjustable z-order ********************************************/
#define PLA_MXR_Z_ORDER_FLAG_UNKNOWN ((UINT32) 0)
#define PLA_MXR_Z_ORDER_FLAG_0   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_0)
#define PLA_MXR_Z_ORDER_FLAG_1   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_1)
#define PLA_MXR_Z_ORDER_FLAG_2   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_2)
#define PLA_MXR_Z_ORDER_FLAG_3   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_3)
#define PLA_MXR_Z_ORDER_FLAG_4   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_4)
#define PLA_MXR_Z_ORDER_FLAG_5   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_5)
#define PLA_MXR_Z_ORDER_FLAG_6   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_6)
#define PLA_MXR_Z_ORDER_FLAG_7   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_7)
#define PLA_MXR_Z_ORDER_FLAG_8   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_8)
#define PLA_MXR_Z_ORDER_FLAG_9   MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_9)
#define PLA_MXR_Z_ORDER_FLAG_10  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_10)
#define PLA_MXR_Z_ORDER_FLAG_11  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_11)
#define PLA_MXR_Z_ORDER_FLAG_12  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_12)
#define PLA_MXR_Z_ORDER_FLAG_13  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_13)
#define PLA_MXR_Z_ORDER_FLAG_14  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_14)
#define PLA_MXR_Z_ORDER_FLAG_15  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_15)
#define PLA_MXR_Z_ORDER_FLAG_16  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_16)
#define PLA_MXR_Z_ORDER_FLAG_17  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_17)
#define PLA_MXR_Z_ORDER_FLAG_18  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_18)
#define PLA_MXR_Z_ORDER_FLAG_19  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_19)
#define PLA_MXR_Z_ORDER_FLAG_20  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_20)
#define PLA_MXR_Z_ORDER_FLAG_21  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_21)
#define PLA_MXR_Z_ORDER_FLAG_22  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_22)
#define PLA_MXR_Z_ORDER_FLAG_23  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_23)
#define PLA_MXR_Z_ORDER_FLAG_24  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_24)
#define PLA_MXR_Z_ORDER_FLAG_25  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_25)
#define PLA_MXR_Z_ORDER_FLAG_26  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_26)
#define PLA_MXR_Z_ORDER_FLAG_27  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_27)
#define PLA_MXR_Z_ORDER_FLAG_28  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_28)
#define PLA_MXR_Z_ORDER_FLAG_29  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_29)
#define PLA_MXR_Z_ORDER_FLAG_30  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_30)
#define PLA_MXR_Z_ORDER_FLAG_31  MAKE_BIT_MASK_32(PLA_MXR_Z_ORDER_31)


/* PLA_MXR_GET_TYPE_ADJ_PLA_BY_PORT ******************************************/
typedef struct _PLA_MXR_ADJ_PLA_BY_PORT_INFO_T
{
    UINT8  ui1_port;       /* input */
    UINT32 ui4_adj_zorder; /* output, bit mask of adjustable z-order */
} PLA_MXR_ADJ_PLA_BY_PORT_INFO_T;




/* PLA_MXR_GET_TYPE_CAPABILITY data info *************************************/
/* plane mixer capabilities */
#define PLA_MXR_CAP_BRIGHTNESS            MAKE_BIT_MASK_32(0)
#define PLA_MXR_CAP_CONTRAST              MAKE_BIT_MASK_32(1)
#define PLA_MXR_CAP_HUE                   MAKE_BIT_MASK_32(2)
#define PLA_MXR_CAP_SATURATION            MAKE_BIT_MASK_32(3)
#define PLA_MXR_CAP_GAMMA                 MAKE_BIT_MASK_32(4)
#define PLA_MXR_CAP_ADJ_PLA               MAKE_BIT_MASK_32(5)
#define PLA_MXR_CAP_PLA_ORDER             MAKE_BIT_MASK_32(6)
#define PLA_MXR_CAP_RESOLUTION            MAKE_BIT_MASK_32(7)
#define PLA_MXR_CAP_DIGITAL_OUT           MAKE_BIT_MASK_32(8)
#define PLA_MXR_CAP_BG                    MAKE_BIT_MASK_32(9)
#define PLA_MXR_CAP_ASPECT_RATIO          MAKE_BIT_MASK_32(10)
#define PLA_MXR_CAP_DIGITAL_OUTPUT_FMT    MAKE_BIT_MASK_32(11)
#define PLA_MXR_CAP_DITHER                MAKE_BIT_MASK_32(12)
#define PLA_MXR_CAP_COLOR_GAIN            MAKE_BIT_MASK_32(13)
#define PLA_MXR_CAP_COLOR_OFFSET          MAKE_BIT_MASK_32(14)
#define PLA_MXR_CAP_BACK_LIGHT            MAKE_BIT_MASK_32(15)
#define PLA_MXR_CAP_ADP_BACK_LIGHT        MAKE_BIT_MASK_32(16)
#define PLA_MXR_CAP_HDMI_DEEP_COLOR       MAKE_BIT_MASK_32(17)
#define PLA_MXR_CAP_SHARPNESS             MAKE_BIT_MASK_32(18)
#define PLA_MXR_CAP_HDCP_ON_OFF           MAKE_BIT_MASK_32(19)
#define PLA_MXR_CAP_CLOSED_CAPTION_ON_OFF MAKE_BIT_MASK_32(20)

/* plane mixer capability info */
typedef UINT32     PLA_MXR_CAPABILITY_INFO_T;

typedef enum
{
    PLA_MXR_OUTPUT_FREQ_60 = 60,
    PLA_MXR_OUTPUT_FREQ_50 = 50,
    PLA_MXR_OUTPUT_FREQ_30 = 30,
    PLA_MXR_OUTPUT_FREQ_25 = 25,
    PLA_MXR_OUTPUT_FREQ_24 = 24,
    PLA_MXR_OUTPUT_FREQ_23_976 = 23,
    PLA_MXR_OUTPUT_FREQ_29_97 = 29,
}   PLA_MXR_OUTPUT_FREQ_T;

/* PLA_MXR_GET_TYPE_RESOLUTION/PLA_MXR_SET_TYPE_RESOLUTION data info *********/
typedef struct _PLA_MXR_RESOLUTION_INFO_T
{
    BOOL                 b_is_alternative_HD_output;
    BOOL                 b_is_OSD5Enable;
    UINT16               ui2_width;
    UINT16               ui2_height;
    BOOL                 b_is_progressive;
    PLA_MXR_OUTPUT_FREQ_T               ui2_v_freq; // 50, 25, 60, 30, 24 HZ
    BOOL                 b_tv_system_depend_on_src; // TRUE means UI Menu TV_SYSTEM is auto
    BOOL                 b_auto_resolution_on; // TRUE means auto resolution
    BOOL                 b_is_3d_mode; //TRUE means 3D mode
    BOOL			 b_is_ccir656;
} PLA_MXR_RESOLUTION_INFO_T;


typedef struct _PLA_MXR_RESOLUTION_INFO_EX_T
{
    BOOL        b_is_output;
    UINT16      ui2_width;
    UINT16      ui2_height;
    BOOL        b_is_progressive;
    BOOL        b_is_3d_mode;
    PLA_MXR_OUTPUT_FREQ_T      ui2_v_freq;
    BOOL			 b_is_ccir656;
} PLA_MXR_RESOLUTION_INFO_EX_T;

typedef enum
{
  PLA_MXR_NON_EXT_CHIP = 0,  
  PLA_MXR_EXT_SCL_EXT_TX,    // ccir/hdmi output FMT Res
  PLA_MXR_EXT_SCL_INT_TX     // ccir output FMT Res, HDMI output ccir in Res
  
} PLA_MXR_EXT_CHIP_USAGE_T;

typedef struct _PLA_MXR_OUTPUT_RESOLUTION_T
{
    BOOL                            b_is_alternative_HD_output;
    PLA_MXR_EXT_CHIP_USAGE_T        t_ext_scl;
    BOOL                            b_is_OSD5Enable;
    PLA_MXR_RESOLUTION_INFO_EX_T    t_ccir;
    PLA_MXR_RESOLUTION_INFO_EX_T    t_hdmi;
    PLA_MXR_RESOLUTION_INFO_EX_T    t_cav;
    PLA_MXR_RESOLUTION_INFO_EX_T    t_cvbs;
} PLA_MXR_OUTPUT_RESOLUTION_T;

/* PLA_MXR_GET_TYPE_OUTPUT_PORT/PLA_MXR_SET_TYPE_OUTPUT_PORT *****************/
/* bit-mask of output port */
#define PLA_MXR_OUTPUT_FLAG_DIGITAL     MAKE_BIT_MASK_32( 0 )
#define PLA_MXR_OUTPUT_FLAG_LVDS        MAKE_BIT_MASK_32( 1 )
#define PLA_MXR_OUTPUT_FLAG_CRT         MAKE_BIT_MASK_32( 2 )


/* PLA_MXR_GET_TYPE_BG/PLA_MXR_SET_TYPE_BG ***********************************/
typedef struct _PLA_MXR_BG_COLOR_T
{
    UINT8       ui1_r;
    UINT8       ui1_g;
    UINT8       ui1_b;
}   PLA_MXR_BG_COLOR_T;


/* PLA_MXR_GET_TYPE_ASPECT_RATIO/PLA_MXR_SET_TYPE_ASPECT_RATIO data info *****/
typedef enum
{
    PLA_MXR_ASPECT_RATIO_UNKNOWN = 0,
    PLA_MXR_ASPECT_RATIO_4_3_PS,
    PLA_MXR_ASPECT_RATIO_16_9_FULL,
    PLA_MXR_ASPECT_RATIO_2_21_1,
    PLA_MXR_ASPECT_RATIO_4_3_LB,
    PLA_MXR_ASPECT_RATIO_16_9_NORMAL
}   PLA_MXR_ASPECT_RATIO_T;

typedef struct _PLA_MXR_ASPECT_RATIO_EX_T
{
    PLA_MXR_ASPECT_RATIO_T e_aspect_ratio;
    BOOL                   b_apply_on_next;
} PLA_MXR_ASPECT_RATIO_EX_T;

typedef struct _PLA_MXR_DIGEST_ASPECT_RATIO_EX_T
{
    PLA_MXR_ASPECT_RATIO_T e_aspect_ratio;
    BOOL                   b_enable;
} PLA_MXR_DIGEST_ASPECT_RATIO_EX_T;


/* PLA_MXR_GET_TYPE_DIGITAL_OUTPUT_FMT/PLA_MXR_SET_TYPE_DIGITAL_OUTPUT_FMT ***/
typedef enum
{
    PLA_MXR_DIGITAL_OUTPUT_FMT_YBR,//YCbCr444
    PLA_MXR_DIGITAL_OUTPUT_FMT_RGB,//Limit RGB
    PLA_MXR_DIGITAL_OUTPUT_FMT_XVYCC,
    PLA_MXR_DIGITAL_OUTPUT_FMT_YBR422,//YCbCr422
    PLA_MXR_DIGITAL_OUTPUT_FMT_FULL_RGB,//FULL RGB
}   PLA_MXR_DIGITAL_OUTPUT_FMT_T;

/* PLA_MXR_GET_TYPE_MIN_MAX **************************************************/
typedef struct _PLA_MXR_MIN_MAX_INFO_T
{
    UINT32  e_get_type;
    UINT32  ui4_min_value;
    UINT32  ui4_max_value;
} PLA_MXR_MIN_MAX_INFO_T;


/* PLA_MXR_GET_TYPE_COLOR_GAIN_MAX/PLA_MXR_GET_TYPE_COLOR_GAIN_MIN ***********/
/* PLA_MXR_GET_TYPE_COLOR_GAIN/PLA_MXR_SET_TYPE_COLOR_GAIN *******************/
typedef struct _PLA_MXR_COLOR_GAIN_T
{
    BOOL        b_auto;
    UINT8       ui1_r_gain;
    UINT8       ui1_g_gain;
    UINT8       ui1_b_gain;
} PLA_MXR_COLOR_GAIN_T;

/* PLA_MXR_GET_TYPE_TV_MODE/PLA_MXR_SET_TYPE_TV_MODE *************************/
typedef enum
{
    PLA_MXR_TV_MODE_NORMAL = 0,
    PLA_MXR_TV_MODE_PIP,
    PLA_MXR_TV_MODE_POP
}   PLA_MXR_TV_MODE_T;

/* PLA_MXR_GET_TYPE_TEST_PATTERN/PLA_MXR_GET_TYPE_TEST_PATTERN ***************/
typedef enum
{
    PLA_MXR_TEST_PATTERN_DISABLE = 0,
    PLA_MXR_TEST_PATTERN_1,
    PLA_MXR_TEST_PATTERN_2,
    PLA_MXR_TEST_PATTERN_3,
    PLA_MXR_TEST_PATTERN_4,
    PLA_MXR_TEST_PATTERN_5,
    PLA_MXR_TEST_PATTERN_6,
    PLA_MXR_TEST_PATTERN_7,
    PLA_MXR_TEST_PATTERN_8
}   PLA_MXR_TEST_PATTERN_T;


/* PLA_MXR_GET_TYPE_HDMI_DEEP_COLOR/PLA_MXR_SET_TYPE_HDMI_DEEP_COLOR *************************/
typedef enum
{
	PLA_MXR_HDMI_DEEP_COLOR_AUTO = 0,
    PLA_MXR_HDMI_NO_DEEP_COLOR_24BIT,
    PLA_MXR_HDMI_DEEP_COLOR_30BIT,
    PLA_MXR_HDMI_DEEP_COLOR_36BIT,
    PLA_MXR_HDMI_DEEP_COLOR_48BIT,
}   PLA_MXR_HDMI_DEEP_COLOR_T;


/* PLA_MXR_GET_TYPE_HDCP_ON_OFF/PLA_MXR_SET_TYPE_HDCP_ON_OFF *************************/
typedef enum
{
	PLA_MXR_HDCP_ON = 0,
    PLA_MXR_HDCP_OFF,
    PLA_MXR_HDCP_LOGO_ON //only for SLT Test
}   PLA_MXR_HDCP_ON_OFF_T;


/* PLA_MXR_GET_TYPE_CLOSED_CAPTION_ON_OFF/PLA_MXR_SET_TYPE_CLOSED_CAPTION_ON_OFF *************************/
typedef enum
{
    PLA_MXR_CLOSED_CAPTION_OFF = 0,
	PLA_MXR_CLOSED_CAPTION_ON,
}   PLA_MXR_CLOSED_CAPTION_ON_OFF_T;


/* PLA_MXR_GET_TYPE_SHARPNESS/PLA_MXR_SET_TYPE_SHARPNESS *************************/
typedef enum
{
	PLA_MXR_DISP_SHARPNESS_LOW = 0,
    PLA_MXR_DISP_SHARPNESS_MIDDLE,
    PLA_MXR_DISP_SHARPNESS_HIGH
}   PLA_MXR_SHARPNESS_T;

typedef enum
{
    PLA_MXR_EXT_SHARPNESS = 0,
    PLA_MXR_EXT_BRIGHTNESS,
    PLA_MXR_EXT_CONTRAST,
    PLA_MXR_EXT_SATURATION,
    PLA_MXR_EXT_COLOR_SPACE,
    PLA_MXR_EXT_Y_C_DELAY,
    PLA_MXR_EXT_CUE_CORRECT,
    PLA_MXR_EXT_BORDER_LEVEL,
    PLA_MXR_EXT_DEINTERLACE_MODE,
    PLA_MXR_EXT_NOISE_REDUCTION,
    PLA_MXR_EXT_EDGE_ENHANCEMENT,
    PLA_MXR_EXT_DETAIL_ENHANCEMENT,
    PLA_MXR_EXT_ZOOM_IMAGE,
    PLA_MXR_EXT_GAMMA,
    PLA_MXR_EXT_DEEP_COLOR
} PLA_MXR_EXTERNAL_CHIP_SETTING_E;

/* PLA_MXR_SET_TYPE_MEDIA *************************/
typedef enum
{
    PLA_MXR_MEDIA_TYPE_INVAID =0,
    PLA_MXR_MEDIA_TYPE_BD,
    PLA_MXR_MEDIA_TYPE_BDRE,
    PLA_MXR_MEDIA_TYPE_DVD,
    PLA_MXR_MEDIA_TYPE_DVDCPRM
}   PLA_MXR_TYPE_MEDIA_T;

typedef struct _PLA_MXR_EXTERNAL_CHIP_SETTING_T
{
    PLA_MXR_EXTERNAL_CHIP_SETTING_E e_set_type;
    INT32                           i4_value;
} PLA_MXR_EXTERNAL_CHIP_SETTING_T;

#if (1 == RM_LIGHT_SUPPORT)
/* PLA_MXR_SET_TYPE_CONNECT & PLA_MXR_SET_TYPE_DISCONNECT ********************/
typedef struct _PLA_MXR_CONNECT_INFO_T
{
    DRV_TYPE_T e_plane_type;   /* input */
    UINT16     ui2_comp_id;    /* input */
} PLA_MXR_CONNECT_INFO_T;

/* PLA_MXR_SET_TYPE_OP_NFY_FCT ***********************************************/
typedef struct _PLA_MXR_OP_NFY_INFO_T
{
    DRV_SET_TYPE_T e_set_type; /* output */
} PLA_MXR_OP_NFY_INFO_T;
#endif

#endif /* _X_PLANE_MXR_H_ */
