
#
# Makefile for the framebuffer driver (for Linux Kernel 3.18)
# 
#

obj-$(CONFIG_COMMON_CLK_ATC) += clk-mux.o clk-pll.o clk-gate.o clk-divider.o
obj-$(CONFIG_COMMON_CLK_ATC_AC83XX) += $(CONFIG_ATC_PLATFORM)/
obj-$(CONFIG_COMMON_CLK_ATC_AC823X) += $(CONFIG_ATC_PLATFORM)/


