/**
 * 编译配置
 * <p> 用来管理项目构建中引入的各种插件和支持库；
 *
 * @author 86158
 */
class BuildConfig {
    // app info
    static applicationId = 'com.hcn.AutoMediaPlayer'
    static appName = 'HMediaPlayer'

    // compiler warning
    static xLintDeprecation = false
    static xLintUnchecked = false

    // publish to mavenLocal()
    static publishMavenLocal = false

    // support HBusPlugin inject
    static supportHBusPluginInject = true

    // support generate R2.java
    static supportGenR2Plugin = true

    // lib version
    static gradlePluginVersion = '7.4.1'
    static kotlinVersion = '1.8.22'
    static androidxVersion = '1.6.1'
    static androidxCoreVersion = '1.10.1'
    static androidMaterialVersion = '1.9.0'
    static androidGuavaVersion = '27.0.1-android'
    static androidxMediaVersion = '1.7.0-alpha01'
    static skinSupportVersion = '1.1.7@aar'
    static androidxRoomVersion = '2.5.2'
    static mmkvVersion = '1.3.1'
    static androidxDrawerLayoutVersion = '1.2.0'
    static androidxViewPager2Version = '1.1.0-beta02'
    static androidxSwipeRefreshLayoutVersion = '1.1.0'
    static reactiveStreamsVersion = '1.0.4'
    static androidxRecyclerviewVersion = '1.3.0'
    static androidxViewPagerVersion = '1.0.0'
    static androidxCardViewVersion = '1.0.0'

    static autoSdkVersion = '1.0.20240909@aar'
    static skinxBaseVersion = '1.1.6@aar'
    static mediaSkinxVersion = '1.2.4@aar'
    static autoCompatVersion = '1.1.9@aar'
    static commonUtilsVersion = '1.1.3@aar'
    static mediaserviceApiVersion = '1.1.0@aar'

    // libs definition
    static libs = [
        javapoet: new LibConfig(path: "com.squareup:javapoet:1.10.0"),

        kotlin_stdlib_jdk8: new LibConfig(
                path: "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"),

        reactive_streams: new LibConfig(
                path: "org.reactivestreams:reactive-streams:$reactiveStreamsVersion"),

        androidx_appcompat: new LibConfig(
                path: "androidx.appcompat:appcompat:$androidxVersion"),

        androidx_core : new LibConfig(
                path: "androidx.core:core:$androidxCoreVersion"),

        androidx_fragment: new LibConfig(
                path: "androidx.fragment:fragment:$androidxVersion"),

        androidx_material: new LibConfig(
                path: "com.google.android.material:material:$androidMaterialVersion"),

        androidx_recyclerview: new LibConfig(
                path: "androidx.recyclerview:recyclerview:$androidxRecyclerviewVersion"),

        android_guava: new LibConfig(
                path: "com.google.guava:guava:$androidGuavaVersion"),

        androidx_media: new LibConfig(
                path: "androidx.media:media:$androidxMediaVersion"),

        skin_support: new LibConfig(
                path: "com.hcn.libs:skin-support:$skinSupportVersion"),

        androidx_room_runtime: new LibConfig(
                path: "androidx.room:room-runtime:$androidxRoomVersion"),

        androidx_room_compiler: new LibConfig(
                path: "androidx.room:room-compiler:$androidxRoomVersion"),

        mmkv: new LibConfig(path: "com.tencent:mmkv:$mmkvVersion"),

        androidx_drawerlayout: new LibConfig(
                path: "androidx.drawerlayout:drawerlayout:$androidxDrawerLayoutVersion"),

        androidx_viewpager2: new LibConfig(
                path: "androidx.viewpager2:viewpager2:$androidxViewPager2Version"),

        androidx_viewpager: new LibConfig(
                path: "androidx.viewpager:viewpager:$androidxViewPagerVersion"),

        androidx_swiperefreshlayout: new LibConfig(
                path: "androidx.swiperefreshlayout:swiperefreshlayout:$androidxSwipeRefreshLayoutVersion"),

        androidx_cardview: new LibConfig(
                path: "androidx.cardview:cardview:$androidxCardViewVersion"),

        common_utils: new LibConfig(
                path: "com.hcn.libs:common-utils:$commonUtilsVersion"),

        auto_compat: new LibConfig(
                path: "com.hcn.libs:auto-compat:$autoCompatVersion"),

        skinx_base: new LibConfig(
                path: "com.hcn.libs:skinx-base:$skinxBaseVersion"),

        media_skinx: new LibConfig(
                path: "com.hcn.libs:media-skinx:$mediaSkinxVersion"),

        auto_sdk: new LibConfig(
                path: "com.hcn.libs:auto_sdk:$autoSdkVersion"),

        mediaservice_api: new LibConfig(
                path: "com.hcn.libs:mediaservice-api:$mediaserviceApiVersion"),

        commons_io: new LibConfig(path: "commons-io:commons-io:2.6"),

        asm: new LibConfig(path: "org.ow2.asm:asm:9.2"),
        asm_commons: new LibConfig(path: "org.ow2.asm:asm-commons:9.2"),

        google_gson: new LibConfig(path: "com.google.code.gson:gson:2.9.0"),
    ]

    // modules definition
    static modules = [
        /* Generated by "module_config.json" */
        plugin_bus_plugin : new ModuleConfig(
                isApply: true , useLocal: true ,
                localPath: "./media-plugin/bus-plugin"),

        plugin_base_transform : new ModuleConfig(
                isApply: true , useLocal: true ,
                localPath: "./media-plugin/base-lib/base-transform",
                remotePath: "com.hcn.base_transform:base-transform:1.0"),

        plugin_build_plugin : new ModuleConfig(
                isApply: true , useLocal: true ,
                localPath: "./media-plugin/build-plugin"),

        plugin_genr2_plugin : new ModuleConfig(
                isApply: true , useLocal: true ,
                localPath: "./media-plugin/genr2-plugin"),
    ]

    // plugins definition
    static plugins = [
        plugin_gradle: new PluginConfig(
                path: "com.android.tools.build:gradle:$gradlePluginVersion"),
        plugin_kotlin: new PluginConfig(
                path: "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"),

        // 上传到 maven
        plugin_maven: new PluginConfig(
                path: "com.github.dcendents:android-maven-gradle-plugin:2.1",
                id: "com.github.dcendents.android-maven"),

        plugin_bus: new PluginConfig(
                isApply: true, useLocal: true,
                path: "com.hcn.bus:bus-plugin:1.0",
                id: "com.hcn.bus"),

        plugin_build: new PluginConfig(
                isApply: false, useLocal: true,
                path: "com.hcn.build:build-plugin:1.0",
                id: "com.hcn.build"),

        plugin_genr2: new PluginConfig(
                isApply: true, useLocal: true,
                path: "com.hcn.gen_r2:genR2Plugin:1.0",
                id: "com.hcn.gen_r2"),
    ]
}